import re
from typing import Any, Dict, Set

PORTRAIT_PATTERN = re.compile(r"^(K|S)(\d+)_.*_Portrait", re.ASCII)

CANONICAL_DLC_INFO: Dict[str, Dict[str, Any]] = {
    "dwight fairfield": {
        "release_number": 1,
        "code_prefix": "S01",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight: Base Game",
        "chapter_number": "0",
        "dlc_type": "base_game",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "June 14, 2016",
        "dlc_counterparts": '["The Trapper", "The Wraith", "The Hillbilly", "Meg Thomas", "Claudette Morel", "Jake Park"]',
        "lore": "Dwight was not the typical high school athlete. Weak, awkward, and lacking in physical prowess, he was the target of relentless bullying. When his coworkers took him on a retreat into the woods and abandoned him with a bottle of spiked moonshine, Dwight wandered into the deep forest and was never seen again.",
    },
    "meg thomas": {
        "release_number": 2,
        "code_prefix": "S02",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight: Base Game",
        "chapter_number": "0",
        "dlc_type": "base_game",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "June 14, 2016",
        "dlc_counterparts": '["The Trapper", "The Wraith", "The Hillbilly", "Dwight Fairfield", "Claudette Morel", "Jake Park"]',
        "lore": "Perhaps it was her mother who instilled that fierce drive in her, or perhaps it was the relentless need to run. Meg gave up her track scholarship when her mother fell ill. During a long run deep in the woods to clear her head, Meg vanished into the thick fog.",
    },
    "claudette morel": {
        "release_number": 3,
        "code_prefix": "S03",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight: Base Game",
        "chapter_number": "0",
        "dlc_type": "base_game",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "June 14, 2016",
        "dlc_counterparts": '["The Trapper", "The Wraith", "The Hillbilly", "Dwight Fairfield", "Meg Thomas", "Jake Park"]',
        "lore": "From the day her parents gave her a first science kit, Claudette loved studying plants and botanical medicine. On a weekend bus ride home from university, the bus took a wrong turn into an unnatural mist, and Claudette never arrived at her destination.",
    },
    "jake park": {
        "release_number": 4,
        "code_prefix": "S04",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight: Base Game",
        "chapter_number": "0",
        "dlc_type": "base_game",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "June 14, 2016",
        "dlc_counterparts": '["The Trapper", "The Wraith", "The Hillbilly", "Dwight Fairfield", "Meg Thomas", "Claudette Morel"]',
        "lore": "Growing up the rebellious son of a wealthy CEO, Jake rejected high society to live off-grid in the remote forest. When search parties came looking after a harsh winter, they found his makeshift cabin deserted with no tracks leading away.",
    },
    "the trapper": {
        "release_number": 1,
        "code_prefix": "K01",
        "role": "Killer",
        "chapter_name": "Dead by Daylight: Base Game",
        "chapter_number": "0",
        "dlc_type": "base_game",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "June 14, 2016",
        "dlc_counterparts": '["Dwight Fairfield", "Meg Thomas", "Claudette Morel", "Jake Park"]',
        "lore": "Evan idolized his wealthy father Archie MacMillan. When Archie's mind cracked, Evan followed his father's orders to lead over a hundred miners into a deep shaft and detonate the explosives, sealing them in their tomb.",
    },
    "the wraith": {
        "release_number": 2,
        "code_prefix": "K02",
        "role": "Killer",
        "chapter_name": "Dead by Daylight: Base Game",
        "chapter_number": "0",
        "dlc_type": "base_game",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "June 14, 2016",
        "dlc_counterparts": '["Dwight Fairfield", "Meg Thomas", "Claudette Morel", "Jake Park"]',
        "lore": "Philip arrived in America with high hopes, taking a job at Autohaven Wreckers scrap yard. When he discovered he was unwittingly executing kidnapped people inside the car crusher, a violent frenzy overtook him.",
    },
    "the hillbilly": {
        "release_number": 3,
        "code_prefix": "K03",
        "role": "Killer",
        "chapter_name": "Dead by Daylight: Base Game",
        "chapter_number": "0",
        "dlc_type": "base_game",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "June 14, 2016",
        "dlc_counterparts": '["Dwight Fairfield", "Meg Thomas", "Claudette Morel", "Jake Park"]',
        "lore": "Born hideous and deformed, the un-named boy was locked in a bricked-up room on Coldwind Farm by his cruel parents. Years later, he broke free with a chainsaw and wrought brutal vengeance across the farm.",
    },
    "the nurse": {
        "release_number": 4,
        "code_prefix": "K04",
        "role": "Killer",
        "chapter_name": "Chapter 1: The Last Breath",
        "chapter_number": "1",
        "dlc_type": "free_update",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "August 18, 2016",
        "dlc_counterparts": '["Nea Karlsson"]',
        "lore": "Sally worked the graveyard shift at the Disturbed Ward of Crotus Prenn Asylum. After twenty years of witnessing misery, her mind fractured, and she cleansed the asylum of all breathing souls.",
    },
    "nea karlsson": {
        "release_number": 5,
        "code_prefix": "S05",
        "role": "Survivor",
        "chapter_name": "Chapter 1: The Last Breath",
        "chapter_number": "1",
        "dlc_type": "free_update",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "August 18, 2016",
        "dlc_counterparts": '["The Nurse"]',
        "lore": "Nea grew up in Sweden before her family relocated to the US. An urban tagger and skateboarder, Nea dared to tag the condemned Crotus Prenn Asylum and never came out.",
    },
    "the shape": {
        "release_number": 5,
        "code_prefix": "K05",
        "role": "Killer",
        "chapter_name": "Chapter 2: The Halloween Chapter",
        "chapter_number": "2",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2016,
        "release_date": "October 25, 2016",
        "dlc_counterparts": '["Laurie Strode"]',
        "lore": "Michael Myers is human only in form. Behind his blank white mask lies pure, unadulterated evil. Driven by an insatiable need to kill, he stalks his prey through Haddonfield with relentless patience.",
    },
    "laurie strode": {
        "release_number": 6,
        "code_prefix": "S06",
        "role": "Survivor",
        "chapter_name": "Chapter 2: The Halloween Chapter",
        "chapter_number": "2",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2016,
        "release_date": "October 25, 2016",
        "dlc_counterparts": '["The Shape"]',
        "lore": "The quintessential babysitter, Laurie thought Halloween would be a night of studying and quiet caretaking. Instead, she faced The Shape and fought desperately to survive.",
    },
    "the hag": {
        "release_number": 6,
        "code_prefix": "K06",
        "role": "Killer",
        "chapter_name": "Chapter 3: Of Flesh and Mud",
        "chapter_number": "3",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "December 8, 2016",
        "dlc_counterparts": '["Ace Visconti"]',
        "lore": "Kidnapped by cannibals and starved in a dark cellar, Lisa carved the elders' protective runes into the wooden floor with her bleeding fingers, awakening dark arcane forces.",
    },
    "ace visconti": {
        "release_number": 7,
        "code_prefix": "S07",
        "role": "Survivor",
        "chapter_name": "Chapter 3: Of Flesh and Mud",
        "chapter_number": "3",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2016,
        "release_date": "December 8, 2016",
        "dlc_counterparts": '["The Hag"]',
        "lore": "Ace is a charming high-rolling gambler who always believed his lucky streak would pull him through. When debt collectors closed in, he vanished without paying his tab.",
    },
    "william \"bill\" overbeck": {
        "release_number": 8,
        "code_prefix": "S08",
        "role": "Survivor",
        "chapter_name": "Left Behind (Left 4 Dead)",
        "chapter_number": "Free DLC",
        "dlc_type": "free_update",
        "is_licensed": True,
        "release_year": 2017,
        "release_date": "March 8, 2017",
        "dlc_counterparts": "[]",
        "lore": "A battle-hardened Vietnam veteran, Bill fought through hordes of infected zombies. Sacrificing himself to restart the bridge generator for his team, Bill awoke in The Fog.",
    },
    "the doctor": {
        "release_number": 7,
        "code_prefix": "K07",
        "role": "Killer",
        "chapter_name": "Chapter 4: Spark of Madness",
        "chapter_number": "4",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2017,
        "release_date": "May 11, 2017",
        "dlc_counterparts": '["Feng Min"]',
        "lore": "Recruited into the Léry Memorial secret research project, Dr. Carter pioneered electroconvulsive torture to extract thoughts from prisoners, descending into mad sadism.",
    },
    "feng min": {
        "release_number": 9,
        "code_prefix": "S09",
        "role": "Survivor",
        "chapter_name": "Chapter 4: Spark of Madness",
        "chapter_number": "4",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2017,
        "release_date": "May 11, 2017",
        "dlc_counterparts": '["The Doctor"]',
        "lore": "A top-tier esports athlete, Feng Min spent days streaming in internet cafes. Facing burnout and pressure, she wandered into the night and never returned to the arena.",
    },
    "the huntress": {
        "release_number": 8,
        "code_prefix": "K08",
        "role": "Killer",
        "chapter_name": "Chapter 5: A Lullaby for the Dark",
        "chapter_number": "5",
        "dlc_type": "free_update",
        "is_licensed": False,
        "release_year": 2017,
        "release_date": "July 27, 2017",
        "dlc_counterparts": '["David King"]',
        "lore": "Raised by her mother in the Russian taiga, Anna learned to hunt wild elk and soldiers. After her mother was killed by an elk, Anna survived alone in the freezing forest.",
    },
    "david king": {
        "release_number": 10,
        "code_prefix": "S10",
        "role": "Survivor",
        "chapter_name": "Chapter 5: A Lullaby for the Dark",
        "chapter_number": "5",
        "dlc_type": "free_update",
        "is_licensed": False,
        "release_year": 2017,
        "release_date": "July 27, 2017",
        "dlc_counterparts": '["The Huntress"]',
        "lore": "A former rugby star with a penchant for barroom brawls and collecting underworld debts, David fought hard and lived fast before vanishing after a rowdy pub night.",
    },
    "the cannibal": {
        "release_number": 9,
        "code_prefix": "K09",
        "role": "Killer",
        "chapter_name": "Paragraph: LEATHERFACE™",
        "chapter_number": "Paragraph",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2017,
        "release_date": "September 14, 2017",
        "dlc_counterparts": "[]",
        "lore": "Bubba kills not out of malice, but out of fear and love for his twisted family. Wielding a buzzing chainsaw and wearing a mask of human flesh, he protects his home at all costs.",
    },
    "the nightmare": {
        "release_number": 10,
        "code_prefix": "K10",
        "role": "Killer",
        "chapter_name": "Chapter 6: A Nightmare on Elm Street™",
        "chapter_number": "6",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2017,
        "release_date": "October 26, 2017",
        "dlc_counterparts": '["Quentin Smith"]',
        "lore": "Even death could not stop Freddy Krueger. Slain by vengeful parents, he returned in the dream world, tormenting the children of Springwood in their deepest sleep.",
    },
    "quentin smith": {
        "release_number": 11,
        "code_prefix": "S11",
        "role": "Survivor",
        "chapter_name": "Chapter 6: A Nightmare on Elm Street™",
        "chapter_number": "6",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2017,
        "release_date": "October 26, 2017",
        "dlc_counterparts": '["The Nightmare"]',
        "lore": "Fuelled by caffeine pills and adrenaline, Quentin fought sleep to stay alive and rescue Nancy from the clutches of Freddy Krueger.",
    },
    "the pig": {
        "release_number": 11,
        "code_prefix": "K11",
        "role": "Killer",
        "chapter_name": "Chapter 7: SAW™",
        "chapter_number": "7",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2018,
        "release_date": "January 23, 2018",
        "dlc_counterparts": '["Detective Tapp"]',
        "lore": "A disciple of the Jigsaw Killer, Amanda created unwinnable reverse bear-trap games to test human survival and purge guilt.",
    },
    "detective tapp": {
        "release_number": 12,
        "code_prefix": "S12",
        "role": "Survivor",
        "chapter_name": "Chapter 7: SAW™",
        "chapter_number": "7",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2018,
        "release_date": "January 23, 2018",
        "dlc_counterparts": '["The Pig"]',
        "lore": "Obsessed with capturing the Jigsaw killer, Detective Tapp ruined his career and marriage in pursuit of justice before vanishing into the shadows.",
    },
    "the clown": {
        "release_number": 12,
        "code_prefix": "K12",
        "role": "Killer",
        "chapter_name": "Chapter 8: Curtain Call",
        "chapter_number": "8",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2018,
        "release_date": "June 12, 2018",
        "dlc_counterparts": '["Kate Denson"]',
        "lore": "Traveling under the alias Jeffrey Hawk with carnivals, Kenneth mixed toxic anaesthetic tonics to drug and mutilate unsuspecting victims.",
    },
    "kate denson": {
        "release_number": 13,
        "code_prefix": "S13",
        "role": "Survivor",
        "chapter_name": "Chapter 8: Curtain Call",
        "chapter_number": "8",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2018,
        "release_date": "June 12, 2018",
        "dlc_counterparts": '["The Clown"]',
        "lore": "A soulful folk musician traveling in her trusty Chevy, Kate spread warmth and songs across small towns before the fog engulfed her camp.",
    },
    "the spirit": {
        "release_number": 13,
        "code_prefix": "K13",
        "role": "Killer",
        "chapter_name": "Chapter 9: Shattered Bloodline",
        "chapter_number": "9",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2018,
        "release_date": "September 18, 2018",
        "dlc_counterparts": '["Adam Francis"]',
        "lore": "Cut down by her father in their ancestral home, Rin pledged her dying vengeance to dark spirits in exchange for otherworldly power.",
    },
    "adam francis": {
        "release_number": 14,
        "code_prefix": "S14",
        "role": "Survivor",
        "chapter_name": "Chapter 9: Shattered Bloodline",
        "chapter_number": "9",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2018,
        "release_date": "September 18, 2018",
        "dlc_counterparts": '["The Spirit"]',
        "lore": "An ambitious teacher from Jamaica who moved to Kagoshima to teach English, Adam was riding the train home when it derailed in the dense mist.",
    },
    "the legion": {
        "release_number": 14,
        "code_prefix": "K14",
        "role": "Killer",
        "chapter_name": "Chapter 10: Darkness Among Us",
        "chapter_number": "10",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2018,
        "release_date": "December 11, 2018",
        "dlc_counterparts": '["Jeff Johansen"]',
        "lore": "Four delinquent teenagers from Ormond bound together by boredom and adrenaline, spiraling into a brutal thrill-kill spree.",
    },
    "jeff johansen": {
        "release_number": 15,
        "code_prefix": "S15",
        "role": "Survivor",
        "chapter_name": "Chapter 10: Darkness Among Us",
        "chapter_number": "10",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2018,
        "release_date": "December 11, 2018",
        "dlc_counterparts": '["The Legion"]',
        "lore": "A quiet heavy-metal artist and muralist, Jeff returned to his hometown of Ormond to sort out his past, only to be taken by The Fog.",
    },
    "the plague": {
        "release_number": 15,
        "code_prefix": "K15",
        "role": "Killer",
        "chapter_name": "Chapter 11: Demise of the Faithful",
        "chapter_number": "11",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2019,
        "release_date": "March 19, 2019",
        "dlc_counterparts": '["Jane Romero"]',
        "lore": "High Priestess of Babylon, Adiris led her people in prayer as a devastating plague struck, ultimately succumbing to the pestilence herself.",
    },
    "jane romero": {
        "release_number": 16,
        "code_prefix": "S16",
        "role": "Survivor",
        "chapter_name": "Chapter 11: Demise of the Faithful",
        "chapter_number": "11",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2019,
        "release_date": "March 19, 2019",
        "dlc_counterparts": '["The Plague"]',
        "lore": "An influential talk show host and advocate, Jane was driving home after a grueling broadcast when she swerved into a thick, unexplained fog.",
    },
    "ashley j. williams": {
        "release_number": 17,
        "code_prefix": "S17",
        "role": "Survivor",
        "chapter_name": "Paragraph: Ash vs Evil Dead",
        "chapter_number": "Paragraph",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2019,
        "release_date": "April 2, 2019",
        "dlc_counterparts": "[]",
        "lore": "Chainsaw-wielding, boomstick-toting savior of humanity against Deadites. Ash made a deal with a Sumerian demon and ended up in The Fog.",
    },
    "the ghost face": {
        "release_number": 16,
        "code_prefix": "K16",
        "role": "Killer",
        "chapter_name": "Chapter 12: Ghost Face®",
        "chapter_number": "12",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2019,
        "release_date": "June 18, 2019",
        "dlc_counterparts": "[]",
        "lore": "Working as a mild-mannered journalist by day, Danny investigated his own murders by night before vanishing into a new town.",
    },
    "the demogorgon": {
        "release_number": 17,
        "code_prefix": "K17",
        "role": "Killer",
        "chapter_name": "Chapter 13: Stranger Things",
        "chapter_number": "13",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2019,
        "release_date": "September 17, 2019",
        "dlc_counterparts": '["Steve Harrington", "Nancy Wheeler"]',
        "lore": "An apex predator from the Upside Down, driven by primal instincts to hunt and consume anything in its path.",
    },
    "steve harrington": {
        "release_number": 18,
        "code_prefix": "S18",
        "role": "Survivor",
        "chapter_name": "Chapter 13: Stranger Things",
        "chapter_number": "13",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2019,
        "release_date": "September 17, 2019",
        "dlc_counterparts": '["The Demogorgon", "Nancy Wheeler"]',
        "lore": "Former high school king turned loyal babysitter and protector, Steve never hesitates to throw himself into danger to save his friends.",
    },
    "nancy wheeler": {
        "release_number": 19,
        "code_prefix": "S19",
        "role": "Survivor",
        "chapter_name": "Chapter 13: Stranger Things",
        "chapter_number": "13",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2019,
        "release_date": "September 17, 2019",
        "dlc_counterparts": '["The Demogorgon", "Steve Harrington"]',
        "lore": "An aspiring investigative reporter from Hawkins High, Nancy pursues the truth no matter how terrifying the horrors in her way.",
    },
    "the oni": {
        "release_number": 18,
        "code_prefix": "K18",
        "role": "Killer",
        "chapter_name": "Chapter 14: Cursed Legacy",
        "chapter_number": "14",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2019,
        "release_date": "December 3, 2019",
        "dlc_counterparts": '["Yui Kimura"]',
        "lore": "Ancestor of the Yamaoka line, Kazan was an enraged samurai who slaughtered impostor lords across feudal Japan with brutal fury.",
    },
    "yui kimura": {
        "release_number": 20,
        "code_prefix": "S20",
        "role": "Survivor",
        "chapter_name": "Chapter 14: Cursed Legacy",
        "chapter_number": "20",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2019,
        "release_date": "December 3, 2019",
        "dlc_counterparts": '["The Oni"]',
        "lore": "A fierce and independent motorcycle racer from Japan, Yui led an all-female street racing gang before crossing the finish line into The Fog.",
    },
    "the deathslinger": {
        "release_number": 19,
        "code_prefix": "K19",
        "role": "Killer",
        "chapter_name": "Chapter 15: Chains of Hate",
        "chapter_number": "15",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2020,
        "release_date": "March 10, 2020",
        "dlc_counterparts": '["Zarina Kassir"]',
        "lore": "A brilliant Irish engineer in the American frontier who invented the speargun, driven to vengeance after having his patents stolen.",
    },
    "zarina kassir": {
        "release_number": 21,
        "code_prefix": "S21",
        "role": "Survivor",
        "chapter_name": "Chapter 15: Chains of Hate",
        "chapter_number": "21",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2020,
        "release_date": "March 10, 2020",
        "dlc_counterparts": '["The Deathslinger"]',
        "lore": "A fearless documentary filmmaker uncovering stories of injustice, Zarina investigated Hellshire Penitentiary before being claimed by The Fog.",
    },
    "the executioner": {
        "release_number": 20,
        "code_prefix": "K20",
        "role": "Killer",
        "chapter_name": "Chapter 16: Silent Hill",
        "chapter_number": "16",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2020,
        "release_date": "June 16, 2020",
        "dlc_counterparts": '["Cheryl Mason"]',
        "lore": "A manifestation of guilt and punishment from Silent Hill, dragging the Great Knife to exact relentless torment and tormenting cages.",
    },
    "cheryl mason": {
        "release_number": 22,
        "code_prefix": "S22",
        "role": "Survivor",
        "chapter_name": "Chapter 16: Silent Hill",
        "chapter_number": "16",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2020,
        "release_date": "June 16, 2020",
        "dlc_counterparts": '["The Executioner"]',
        "lore": "Having survived the nightmarish cult of Silent Hill, Cheryl sought a peaceful life helping troubled teens before The Fog claimed her.",
    },
    "the blight": {
        "release_number": 21,
        "code_prefix": "K21",
        "role": "Killer",
        "chapter_name": "Chapter 17: Descend Beyond",
        "chapter_number": "17",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2020,
        "release_date": "September 8, 2020",
        "dlc_counterparts": '["Felix Richter"]',
        "lore": "A brilliant Scottish chemist obsessed with the mind-altering serum extracted from Pustula flowers, Talbot mutated into a hyper-fast monster.",
    },
    "felix richter": {
        "release_number": 23,
        "code_prefix": "S23",
        "role": "Survivor",
        "chapter_name": "Chapter 17: Descend Beyond",
        "chapter_number": "17",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2020,
        "release_date": "September 8, 2020",
        "dlc_counterparts": '["The Blight"]',
        "lore": "An innovative German architect searching for his missing father on the desolate island of Dyer, Felix stumbled into an ancient portal.",
    },
    "the twins": {
        "release_number": 22,
        "code_prefix": "K22",
        "role": "Killer",
        "chapter_name": "Chapter 18: A Binding of Kin",
        "chapter_number": "18",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2020,
        "release_date": "December 1, 2020",
        "dlc_counterparts": '["Élodie Rakoto"]',
        "lore": "Born conjoined in 17th-century France, Charlotte and Victor were hunted as demons. Reunited by The Entity, they hunt as a lethal pair.",
    },
    "élodie rakoto": {
        "release_number": 24,
        "code_prefix": "S24",
        "role": "Survivor",
        "chapter_name": "Chapter 18: A Binding of Kin",
        "chapter_number": "18",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2020,
        "release_date": "December 1, 2020",
        "dlc_counterparts": '["The Twins"]',
        "lore": "An occult investigator searching the world for ancient artifacts connected to her missing parents, Élodie followed the clues into The Fog.",
    },
    "the trickster": {
        "release_number": 23,
        "code_prefix": "K23",
        "role": "Killer",
        "chapter_name": "Chapter 19: All-Kill",
        "chapter_number": "19",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2021,
        "release_date": "March 30, 2021",
        "dlc_counterparts": '["Yun-Jin Lee"]',
        "lore": "A sensational K-Pop superstar who secretly recorded the agonizing screams of his murder victims and mixed them into his hit songs.",
    },
    "yun-jin lee": {
        "release_number": 25,
        "code_prefix": "S25",
        "role": "Survivor",
        "chapter_name": "Chapter 19: All-Kill",
        "chapter_number": "19",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2021,
        "release_date": "March 30, 2021",
        "dlc_counterparts": '["The Trickster"]',
        "lore": "A ruthless music producer who built NO SPIN from the ground up, Yun-Jin always put her own survival and career ambitions first.",
    },
    "the nemesis": {
        "release_number": 24,
        "code_prefix": "K24",
        "role": "Killer",
        "chapter_name": "Chapter 20: Resident Evil",
        "chapter_number": "20",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2021,
        "release_date": "June 15, 2021",
        "dlc_counterparts": '["Leon S. Kennedy", "Jill Valentine"]',
        "lore": "Umbrella Corporation's ultimate biological weapon, programmed with a singular mission: eradicate all members of S.T.A.R.S.",
    },
    "leon s. kennedy": {
        "release_number": 26,
        "code_prefix": "S26",
        "role": "Survivor",
        "chapter_name": "Chapter 20: Resident Evil",
        "chapter_number": "20",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2021,
        "release_date": "June 15, 2021",
        "dlc_counterparts": '["The Nemesis", "Jill Valentine"]',
        "lore": "On his first day as a rookie cop in Raccoon City, Leon faced a biological apocalypse, displaying tactical brilliance and resolve.",
    },
    "jill valentine": {
        "release_number": 27,
        "code_prefix": "S27",
        "role": "Survivor",
        "chapter_name": "Chapter 20: Resident Evil",
        "chapter_number": "20",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2021,
        "release_date": "June 15, 2021",
        "dlc_counterparts": '["The Nemesis", "Leon S. Kennedy"]',
        "lore": "Founding member of S.T.A.R.S. and surviving operative of the Spencer Mansion incident, Jill escaped Raccoon City while hunted by Nemesis.",
    },
    "the cenobite": {
        "release_number": 25,
        "code_prefix": "K25",
        "role": "Killer",
        "chapter_name": "Chapter 21: Hellraiser™",
        "chapter_number": "21",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2021,
        "release_date": "September 7, 2021",
        "dlc_counterparts": "[]",
        "lore": "An explorer in the further regions of experience: demon to some, angel to others. Summons hooks and chains to harvest mortal souls.",
    },
    "mikaela reid": {
        "release_number": 28,
        "code_prefix": "S28",
        "role": "Survivor",
        "chapter_name": "Chapter 21.5: Hour of the Witch",
        "chapter_number": "21.5",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2021,
        "release_date": "October 19, 2021",
        "dlc_counterparts": "[]",
        "lore": "A modern witch and horror storyteller, Mikaela blessed totems at the Moonstone festival before disappearing into the mist.",
    },
    "the artist": {
        "release_number": 26,
        "code_prefix": "K26",
        "role": "Killer",
        "chapter_name": "Chapter 22: Portrait of a Murder",
        "chapter_number": "22",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2021,
        "release_date": "November 30, 2021",
        "dlc_counterparts": '["Jonah Vasquez"]',
        "lore": "A gifted Chilean artist whose tongue and hands were severed by corrupt officials. Crows flocked to avenge her, manifesting ink dire crows.",
    },
    "jonah vasquez": {
        "release_number": 29,
        "code_prefix": "S29",
        "role": "Survivor",
        "chapter_name": "Chapter 22: Portrait of a Murder",
        "chapter_number": "22",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2021,
        "release_date": "November 30, 2021",
        "dlc_counterparts": '["The Artist"]',
        "lore": "A CIA cryptanalyst who decoded an arcane recurring signal that led him to an abandoned cemetery in the Chilean desert.",
    },
    "the onryō": {
        "release_number": 27,
        "code_prefix": "K27",
        "role": "Killer",
        "chapter_name": "Chapter 23: Sadako Rising",
        "chapter_number": "23",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2022,
        "release_date": "March 8, 2022",
        "dlc_counterparts": '["Yoichi Asakawa"]',
        "lore": "Left to die in a water well, Sadako's psychic wrath manifested as a cursed videotape that condemns anyone who watches it.",
    },
    "yoichi asakawa": {
        "release_number": 30,
        "code_prefix": "S30",
        "role": "Survivor",
        "chapter_name": "Chapter 23: Sadako Rising",
        "chapter_number": "23",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2022,
        "release_date": "March 8, 2022",
        "dlc_counterparts": '["The Onryō"]',
        "lore": "The boy who survived Sadako's curse grew up to become a marine biologist, forever haunted by psychic visions of the ocean deep.",
    },
    "the dredge": {
        "release_number": 28,
        "code_prefix": "K28",
        "role": "Killer",
        "chapter_name": "Chapter 24: Roots of Dread",
        "chapter_number": "24",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2022,
        "release_date": "June 7, 2022",
        "dlc_counterparts": '["Haddie Kaur"]',
        "lore": "A monstrous amalgamation of dark thoughts and severed limbs born from the suppressed malice of a utopian cult on the Garden of Joy.",
    },
    "haddie kaur": {
        "release_number": 31,
        "code_prefix": "S31",
        "role": "Survivor",
        "chapter_name": "Chapter 24: Roots of Dread",
        "chapter_number": "31",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2022,
        "release_date": "June 7, 2022",
        "dlc_counterparts": '["The Dredge"]',
        "lore": "A psychic podcaster capable of seeing 'The Ravage' — bleeding dimensions of darkness — who investigated haunted locations worldwide.",
    },
    "the mastermind": {
        "release_number": 29,
        "code_prefix": "K29",
        "role": "Killer",
        "chapter_name": "Chapter 25: Resident Evil: PROJECT W",
        "chapter_number": "25",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2022,
        "release_date": "August 30, 2022",
        "dlc_counterparts": '["Ada Wong", "Rebecca Chambers"]',
        "lore": "A visionary eugenicist with superhuman power derived from the Uroboros virus, believing humanity requires forced evolution.",
    },
    "ada wong": {
        "release_number": 32,
        "code_prefix": "S32",
        "role": "Survivor",
        "chapter_name": "Chapter 25: Resident Evil: PROJECT W",
        "chapter_number": "25",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2022,
        "release_date": "August 30, 2022",
        "dlc_counterparts": '["The Mastermind", "Rebecca Chambers"]',
        "lore": "An enigmatic corporate spy of unparalleled skill who uses stealth, grappling hooks, and intellect to complete impossible missions.",
    },
    "rebecca chambers": {
        "release_number": 33,
        "code_prefix": "S33",
        "role": "Survivor",
        "chapter_name": "Chapter 25: Resident Evil: PROJECT W",
        "chapter_number": "25",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2022,
        "release_date": "August 30, 2022",
        "dlc_counterparts": '["The Mastermind", "Ada Wong"]',
        "lore": "The prodigy medic of S.T.A.R.S. Bravo Team whose medical expertise and optimism keep her allies fighting through darkness.",
    },
    "the knight": {
        "release_number": 30,
        "code_prefix": "K30",
        "role": "Killer",
        "chapter_name": "Chapter 26: Forged in Fog",
        "chapter_number": "26",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2022,
        "release_date": "November 22, 2022",
        "dlc_counterparts": '["Vittorio Toscano"]',
        "lore": "A brutal Hungarian sellsword who led his loyal Guardia Compagnia — The Carnifex, The Assassin, and The Jailer — in bloody conquest.",
    },
    "vittorio toscano": {
        "release_number": 34,
        "code_prefix": "S34",
        "role": "Survivor",
        "chapter_name": "Chapter 26: Forged in Fog",
        "chapter_number": "34",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2022,
        "release_date": "November 22, 2022",
        "dlc_counterparts": '["The Knight"]',
        "lore": "An Italian nobleman and scholar who unlocked ancient runes of peace, roaming across realms for centuries without aging.",
    },
    "the skull merchant": {
        "release_number": 31,
        "code_prefix": "K31",
        "role": "Killer",
        "chapter_name": "Chapter 27: Tools of Torment",
        "chapter_number": "27",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2023,
        "release_date": "March 7, 2023",
        "dlc_counterparts": '["Thalita Lyra", "Renato Lyra"]',
        "lore": "A wealthy tech CEO who used surveillance drones and stealth technology to eliminate corporate rivals and track human quarry.",
    },
    "thalita lyra": {
        "release_number": 35,
        "code_prefix": "S35",
        "role": "Survivor",
        "chapter_name": "Chapter 27: Tools of Torment",
        "chapter_number": "27",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2023,
        "release_date": "March 7, 2023",
        "dlc_counterparts": '["The Skull Merchant", "Renato Lyra"]',
        "lore": "A high-spirited Brazilian kite-fighter and mentor, working alongside her brother Renato to protect their local beach community.",
    },
    "renato lyra": {
        "release_number": 36,
        "code_prefix": "S36",
        "role": "Survivor",
        "chapter_name": "Chapter 27: Tools of Torment",
        "chapter_number": "27",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2023,
        "release_date": "March 7, 2023",
        "dlc_counterparts": '["The Skull Merchant", "Thalita Lyra"]',
        "lore": "A patient, analytical kite competitor and student whose calculated thinking balances his sister Thalita's fiery spontaneity.",
    },
    "the singularity": {
        "release_number": 32,
        "code_prefix": "K32",
        "role": "Killer",
        "chapter_name": "Chapter 28: End Transmission",
        "chapter_number": "28",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2023,
        "release_date": "June 13, 2023",
        "dlc_counterparts": '["Gabriel Soma"]',
        "lore": "An autonomous android on an alien planet that came into contact with ancient alien technology, declaring humanity obsolete.",
    },
    "gabriel soma": {
        "release_number": 37,
        "code_prefix": "S37",
        "role": "Survivor",
        "chapter_name": "Chapter 28: End Transmission",
        "chapter_number": "28",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2023,
        "release_date": "June 13, 2023",
        "dlc_counterparts": '["The Singularity"]',
        "lore": "A synthetic clone technician created to maintain deep space outposts on Dvarka, who fought desperately for his own genuine humanity.",
    },
    "nicolas cage": {
        "release_number": 38,
        "code_prefix": "S38",
        "role": "Survivor",
        "chapter_name": "Paragraph: Nicolas Cage",
        "chapter_number": "Paragraph",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2023,
        "release_date": "July 25, 2023",
        "dlc_counterparts": "[]",
        "lore": "Legendary actor Nicolas Cage was filming the performance of a lifetime when a red mist on set transported him straight into The Fog.",
    },
    "the xenomorph": {
        "release_number": 33,
        "code_prefix": "K33",
        "role": "Killer",
        "chapter_name": "Chapter 29: Alien",
        "chapter_number": "29",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2023,
        "release_date": "August 29, 2023",
        "dlc_counterparts": '["Ellen Ripley"]',
        "lore": "The perfect organism. Unmatched structural perfection matched only by its hostility. It stalks through subterranean tunnels to slaughter.",
    },
    "ellen ripley": {
        "release_number": 39,
        "code_prefix": "S39",
        "role": "Survivor",
        "chapter_name": "Chapter 29: Alien",
        "chapter_number": "29",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2023,
        "release_date": "August 29, 2023",
        "dlc_counterparts": '["The Xenomorph"]',
        "lore": "Warrant Officer on the commercial starship USCSS Nostromo, Ripley is the ultimate survivor who never surrenders against impossible odds.",
    },
    "the good guy": {
        "release_number": 34,
        "code_prefix": "K34",
        "role": "Killer",
        "chapter_name": "Chapter 30: Chucky",
        "chapter_number": "30",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2023,
        "release_date": "November 28, 2023",
        "dlc_counterparts": "[]",
        "lore": "The notorious Lakeshore Strangler transferred his soul into a Good Guy doll using voodoo, relishing bloody mayhem with gleeful malice.",
    },
    "alan wake": {
        "release_number": 40,
        "code_prefix": "S40",
        "role": "Survivor",
        "chapter_name": "Paragraph: Alan Wake",
        "chapter_number": "Paragraph",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "January 30, 2024",
        "dlc_counterparts": "[]",
        "lore": "A troubled best-selling novelist trapped in the Dark Place, writing manuscripts with his trusty flashlight to reshape reality and escape.",
    },
    "the unknown": {
        "release_number": 35,
        "code_prefix": "K35",
        "role": "Killer",
        "chapter_name": "Chapter 31: All Things Wicked",
        "chapter_number": "31",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2024,
        "release_date": "March 12, 2024",
        "dlc_counterparts": '["Sable Ward"]',
        "lore": "An urban legend brought into horrifying physical reality by rumors and fear, mimicking voices and twisting limbs in impossible shapes.",
    },
    "sable ward": {
        "release_number": 41,
        "code_prefix": "S41",
        "role": "Survivor",
        "chapter_name": "Chapter 31: All Things Wicked",
        "chapter_number": "31",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2024,
        "release_date": "March 12, 2024",
        "dlc_counterparts": '["The Unknown"]',
        "lore": "A goth host of a late-night horror radio show who willingly walked into the Greenville cinema basement to find her best friend Mikaela.",
    },
    "the lich": {
        "release_number": 36,
        "code_prefix": "K36",
        "role": "Killer",
        "chapter_name": "Chapter 32: Dungeons & Dragons",
        "chapter_number": "32",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "June 3, 2024",
        "dlc_counterparts": '["Aestri Yazar", "Baemar Uraz"]',
        "lore": "The arch-lich of Greyhawk, Master of the Spider Throne and Lord of Secrets. Wields the Book of Vile Darkness and four arcane spells.",
    },
    "aestri yazar": {
        "release_number": 42,
        "code_prefix": "S42",
        "role": "Survivor",
        "chapter_name": "Chapter 32: Dungeons & Dragons",
        "chapter_number": "32",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "June 3, 2024",
        "dlc_counterparts": '["The Lich"]',
        "lore": "An elven bard of joyful spirit and arcane inspiration, weaving magical songs and illusions to aid her adventuring party.",
    },
    "lara croft": {
        "release_number": 43,
        "code_prefix": "S43",
        "role": "Survivor",
        "chapter_name": "Paragraph: Tomb Raider",
        "chapter_number": "Paragraph",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "July 16, 2024",
        "dlc_counterparts": "[]",
        "lore": "Legendary archaeologist and tomb raider whose acrobatic agility, resourcefulness, and survival instincts keep her one step ahead.",
    },
    "the dark lord": {
        "release_number": 37,
        "code_prefix": "K37",
        "role": "Killer",
        "chapter_name": "Chapter 33: Castlevania",
        "chapter_number": "33",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "August 27, 2024",
        "dlc_counterparts": '["Trevor Belmont"]',
        "lore": "The immortal lord of vampires and dark sorcery. Shapeshifts into bat, wolf, and vampire forms to conquer all mortal realms.",
    },
    "trevor belmont": {
        "release_number": 44,
        "code_prefix": "S44",
        "role": "Survivor",
        "chapter_name": "Chapter 33: Castlevania",
        "chapter_number": "33",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "August 27, 2024",
        "dlc_counterparts": '["The Dark Lord"]',
        "lore": "Last scion of the legendary Belmont monster-hunting clan, wielding holy magic, courage, and relics against nocturnal beasts.",
    },
    "the houndmaster": {
        "release_number": 38,
        "code_prefix": "K38",
        "role": "Killer",
        "chapter_name": "Chapter 34: Doomed Course",
        "chapter_number": "34",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2024,
        "release_date": "November 2024",
        "dlc_counterparts": '["Taurie Cain"]',
        "lore": "A 19th-century naval captain stranded on a cursed island who commands her loyal war hound Snug to tear down mutineers.",
    },
    "taurie cain": {
        "release_number": 45,
        "code_prefix": "S45",
        "role": "Survivor",
        "chapter_name": "Chapter 34: Doomed Course",
        "chapter_number": "34",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2024,
        "release_date": "November 2024",
        "dlc_counterparts": '["The Houndmaster"]',
        "lore": "A member of the black-market Black Vale cult whose invocation rituals led her directly into the court of The Entity.",
    },
    "the ghoul": {
        "release_number": 39,
        "code_prefix": "K39",
        "role": "Killer",
        "chapter_name": "Dead by Daylight Archives: The Ghoul",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "A half-ghoul cursed to walk between humanity and monstrous hunger, fighting to protect those he loves with visceral predatory fury.",
    },
    "the animatronic": {
        "release_number": 40,
        "code_prefix": "K40",
        "role": "Killer",
        "chapter_name": "Dead by Daylight Archives: Five Nights",
        "chapter_number": "Archives",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "William Afton, trapped inside a decaying animatronic rabbit suit, bound by rusty crossbeams and eternal agony, eternally driven to hunt.",
    },
    "the krasue": {
        "release_number": 41,
        "code_prefix": "K41",
        "role": "Killer",
        "chapter_name": "Dead by Daylight Archives: Southeast Legends",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "A nocturnal female ghost of folklore whose head detaches from the body at night to hunt for flesh, trailing glowing internal viscera.",
    },
    "the slasher": {
        "release_number": 42,
        "code_prefix": "K42",
        "role": "Killer",
        "chapter_name": "Dead by Daylight Archives: Crystal Lake",
        "chapter_number": "Archives",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "The masked drowned boy of Crystal Lake, an immortal juggernaut of vengeance who punishes all who trespass upon his sacred woods.",
    },
    "the first": {
        "release_number": 43,
        "code_prefix": "K43",
        "role": "Killer",
        "chapter_name": "Dead by Daylight Archives: Ancient Fog",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "The earliest hunter taken by the Entity when humanity first made fire, ancient and molded into pure elemental cruelty.",
    },
    "the judgment": {
        "release_number": 44,
        "code_prefix": "K44",
        "role": "Killer",
        "chapter_name": "Dead by Daylight Archives: Holy Inquisition",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "A fanatic judge from the Spanish Inquisition who tortured thousands in the name of purity until the Entity answered his prayers.",
    },
    "orela rose": {
        "release_number": 46,
        "code_prefix": "S46",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2024,
        "release_date": "2024",
        "dlc_counterparts": "[]",
        "lore": "A botanist exploring cursed flora whose research into the Black Vale led her straight into the Fog.",
    },
    "rick grimes": {
        "release_number": 47,
        "code_prefix": "S47",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives: The Walking Dead",
        "chapter_number": "Archives",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "2024",
        "dlc_counterparts": '["Michonne Grimes"]',
        "lore": "A sheriff's deputy turned battle-hardened leader who did whatever it took to keep his family alive in an apocalyptic wasteland.",
    },
    "michonne grimes": {
        "release_number": 48,
        "code_prefix": "S48",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives: The Walking Dead",
        "chapter_number": "Archives",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "2024",
        "dlc_counterparts": '["Rick Grimes"]',
        "lore": "A fierce katana-wielding survivor whose sharp instincts and quiet resilience made her a beacon of hope against walking death.",
    },
    "vee boonyasak": {
        "release_number": 49,
        "code_prefix": "S49",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2024,
        "release_date": "2024",
        "dlc_counterparts": "[]",
        "lore": "A street racer from Bangkok who used precision reflexes and mechanical ingenuity to outrun underground syndicates.",
    },
    "eleven": {
        "release_number": 50,
        "code_prefix": "S50",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives: Stranger Things Vol 2",
        "chapter_number": "Archives",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "2024",
        "dlc_counterparts": '["Dustin Henderson"]',
        "lore": "A young girl with psychokinetic powers escaped from Hawkins National Laboratory, braving monsters from the Upside Down.",
    },
    "dustin henderson": {
        "release_number": 51,
        "code_prefix": "S51",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives: Stranger Things Vol 2",
        "chapter_number": "Archives",
        "dlc_type": "licensed_chapter",
        "is_licensed": True,
        "release_year": 2024,
        "release_date": "2024",
        "dlc_counterparts": '["Eleven"]',
        "lore": "A whip-smart science enthusiast and radio builder whose loyalty to his friends never wavered in the darkest hours.",
    },
    "kwon tae-young": {
        "release_number": 52,
        "code_prefix": "S52",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "An underground investigative journalist in Seoul who risked everything to expose corruption among high-level executives.",
    },
    "shane wiigwaas": {
        "release_number": 53,
        "code_prefix": "S53",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "An indigenous wilderness tracker from Ontario whose bond with nature helped him guide lost wanderers through blizzard country.",
    },
    "aurora stardotter": {
        "release_number": 54,
        "code_prefix": "S54",
        "role": "Survivor",
        "chapter_name": "Dead by Daylight Archives",
        "chapter_number": "Archives",
        "dlc_type": "original_chapter",
        "is_licensed": False,
        "release_year": 2025,
        "release_date": "2025",
        "dlc_counterparts": "[]",
        "lore": "A Nordic stargazer and astronomer who unlocked ancestral celestial maps pointing beyond known dimensions.",
    },
}

CANONICAL_KILLER_POWERS: Dict[str, Dict[str, Any]] = {
    "the trapper": {
        "name": "Bear Trap",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4c/IconPowers_bearTrap.png",
        "targets": ["Bear Trap", "The Trapper", "Evan MacMillan"],
        "description": "The Trapper starts the Trial carrying Bear Traps and can find additional Bear Traps scattered throughout the Realm. The Trapper can set a Bear Trap on the ground. When a Survivor steps into an active Bear Trap, they become trapped, injured into the Injured state if Healthy, and suffer from the Trapped Status Effect until they escape or are rescued.",
    },
    "the wraith": {
        "name": "Wailing Bell",
        "movement_speed": "4.6 m/s (115%) / 6.0 m/s (150% Cloaked)",
        "terror_radius": "32 m (0 m Cloaked)",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2c/IconPowers_wailingBell.png",
        "targets": ["Wailing Bell", "The Wraith", "Philip Ojomo"],
        "description": "Ring the Wailing Bell to enter and exit the Spirit World. While Cloaked, the Wraith moves significantly faster, gains the Undetectable Status Effect, and is invisible to Survivors beyond 20 metres. Uncloaking grants a temporary burst of Movement Speed.",
    },
    "the hillbilly": {
        "name": "Chainsaw",
        "movement_speed": "4.6 m/s (115%) / 10.12 m/s (253% Sprint)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/9/9e/IconPowers_chainsaw.png",
        "targets": ["Chainsaw", "The Hillbilly", "Max Thompson Jr."],
        "description": "Rev the Chainsaw to trigger a deadly high-speed Chainsaw Sprint. Hitting a Survivor with the Chainsaw instantly puts them into the Dying State. The Chainsaw features an Overheat mechanic that builds heat while revving and sprinting.",
    },
    "the nurse": {
        "name": "Spencer's Last Breath",
        "movement_speed": "3.85 m/s (96.25%) / 13.33 m/s Blink",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c5/IconPowers_spencersLastBreath.png",
        "targets": ["Spencer's Last Breath", "The Nurse", "Sally Smithson"],
        "description": "Channel Spencer's Last Breath to perform a Blink, tearing through the physical world and traversing obstacles and terrain instantly. The Nurse can chain an additional Blink before suffering a brief fatigue.",
    },
    "the shape": {
        "name": "Evil Within",
        "movement_speed": "4.2 m/s (105% T1) / 4.6 m/s (115% T2-T3)",
        "terror_radius": "0 m (T1) / 16 m (T2) / 32 m (T3)",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPowers_evilWithin.png",
        "targets": ["Evil Within", "The Shape", "Michael Myers"],
        "description": "Stalk Survivors to harvest Evil and progress through three tiers of Evil Within. Tier I grants Undetectable but slower movement. Tier II gives standard speed and reduced Terror Radius. Tier III gives extended Lunge and causes all Basic Attacks to inflict the Dying State.",
    },
    "the hag": {
        "name": "Blackened Catalyst",
        "movement_speed": "4.4 m/s (110%)",
        "terror_radius": "24 m",
        "terror_radius_meters": 24,
        "height": "Short",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/ca/IconPowers_blackenedCatalyst.png",
        "targets": ["Blackened Catalyst", "The Hag", "Lisa Sherwood"],
        "description": "Draw Phantasm Traps on the ground using mud. When a Survivor steps near a trap, a terrifying Phantasm is triggered, disorienting the Survivor. The Hag can teleport instantly to any triggered Phantasm Trap within 48 metres.",
    },
    "the doctor": {
        "name": "Carter's Spark",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/e/e4/IconPowers_cartersSpark.png",
        "targets": ["Carter's Spark", "The Doctor", "Herman Carter"],
        "description": "Release Shock Therapy attacks and a devastating Static Blast that shocks Survivors, causing them to scream, reveal their locations, and advance through Madness tiers (I, II, III). High Madness causes hallucinations, skill check disruptions, and prevents interaction.",
    },
    "the huntress": {
        "name": "Hunting Hatchets",
        "movement_speed": "4.4 m/s (110%)",
        "terror_radius": "20 m (45 m Lullaby)",
        "terror_radius_meters": 20,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/07/IconPowers_huntingHatchets.png",
        "targets": ["Hunting Hatchets", "The Huntress", "Anna"],
        "description": "Carry up to 5 Hunting Hatchets and wind up high-velocity ranged throws that injure or down Survivors across long distances. Replenish Hatchets at Lockers throughout the Trial.",
    },
    "the cannibal": {
        "name": "Bubba's Chainsaw",
        "movement_speed": "4.6 m/s (115%) / 5.29 m/s (132.25% Sweep)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/09/IconPowers_bubbasChainsaw.png",
        "targets": ["Bubba's Chainsaw", "The Cannibal", "Bubba Sawyer"],
        "description": "Consume Power Tokens to initiate a Chainsaw Sweep, swinging the chainsaw back and forth in a lethal arc that instantly downs any Survivors hit and chews through thrown pallets.",
    },
    "the nightmare": {
        "name": "Dream Demon",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m (32 m Lullaby in Dream)",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/ad/IconPowers_dreamDemon.png",
        "targets": ["Dream Demon", "The Nightmare", "Freddy Krueger"],
        "description": "Survivors passively fall asleep into the Dream World. Asleep Survivors are oblivious to Freddy's Terror Radius, hearing a Lullaby instead. Freddy can place Dream Snares/Pallets to hinder Survivors and project his form across the map to teleport to Generators.",
    },
    "the pig": {
        "name": "Jigsaw's Baptism",
        "movement_speed": "4.6 m/s (115%) / 3.6 m/s (Crouch) / 6.9 m/s (Ambush)",
        "terror_radius": "32 m (0 m Crouched)",
        "terror_radius_meters": 32,
        "height": "Short",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/13/IconPowers_jigsawsBaptism.png",
        "targets": ["Jigsaw's Baptism", "The Pig", "Amanda Young"],
        "description": "Crouch to become Undetectable and unleash an Ambush Dash attack. When downing a Survivor, place a Reverse Bear Trap on their head. RBTs activate when a Generator completes and kill the Survivor if not removed at a Jigsaw Box before time expires.",
    },
    "the clown": {
        "name": "The Afterpiece Tonic",
        "movement_speed": "4.6 m/s (115%) / 5.06 m/s (Antidote)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/89/IconPowers_theAfterpieceTonic.png",
        "targets": ["The Afterpiece Tonic", "The Clown", "Kenneth Chase"],
        "description": "Brew and throw bottles of Afterpiece Tonic (intoxicating purple gas that impairs vision and slows Survivors) and Afterpiece Antidote (invigorating yellow gas that cures intoxication and grants a speed boost).",
    },
    "the spirit": {
        "name": "Yamaoka's Haunting",
        "movement_speed": "4.4 m/s (110%) / 7.04 m/s (Phase)",
        "terror_radius": "24 m",
        "terror_radius_meters": 24,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4e/IconPowers_yamaokasHaunting.png",
        "targets": ["Yamaoka's Haunting", "The Spirit", "Rin Yamaoka"],
        "description": "Leave behind a stationary Husk and enter the Ethereal Plane to Phase-Walk at extreme speed. While Phase-Walking, Survivors are invisible to the Spirit, who must track them via scratch marks, sounds, and environmental disturbance.",
    },
    "the legion": {
        "name": "Feral Frenzy",
        "movement_speed": "4.6 m/s (115%) / 5.2 m/s (Frenzy)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/b/b3/IconPowers_feralFrenzy.png",
        "targets": ["Feral Frenzy", "The Legion", "Frank, Julie, Susie, Joey"],
        "description": "Activate Feral Frenzy to sprint rapidly and vault pallets and windows at high speed. Hitting a Survivor applies Deep Wound and reveals the locations of all other Survivors within Terror Radius via Killer Instinct.",
    },
    "the plague": {
        "name": "Vile Purge",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/5/52/IconPowers_vilePurge.png",
        "targets": ["Vile Purge", "The Plague", "Adiris"],
        "description": "Vomit streams of infection that contaminate Survivors and interactive objects. Infected Survivors eventually become Broken. Purging at Pools of Devotion cleanses Survivors but corrupts the pool into Corrupt Purge, turning the stream into lethal damage.",
    },
    "the ghost face": {
        "name": "Night Shroud",
        "movement_speed": "4.6 m/s (115%) / 3.6 m/s (Crouch)",
        "terror_radius": "32 m (0 m Shroud)",
        "terror_radius_meters": 32,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3d/IconPowers_nightShroud.png",
        "targets": ["Night Shroud", "The Ghost Face", "Danny Johnson"],
        "description": "Activate Night Shroud to gain the Undetectable Status Effect. Crouch and lean from cover to stalk Survivors, filling their stalk gauge to Mark them, inflicting the Exposed Status Effect.",
    },
    "the demogorgon": {
        "name": "Of the Abyss",
        "movement_speed": "4.6 m/s (115%) / 9.2 m/s (Shred)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a9/IconPowers_ofTheAbyss.png",
        "targets": ["Of the Abyss", "The Demogorgon", "Demogorgon"],
        "description": "Place Portals across the map and traverse the Upside Down to travel between them. Channel Of the Abyss to detect nearby Survivors on portals and unleash a long-range Shred lunge attack.",
    },
    "the oni": {
        "name": "Yamaoka's Wrath",
        "movement_speed": "4.6 m/s (115%) / 7.82 m/s (Demon Dash)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/df/IconPowers_yamaokasWrath.png",
        "targets": ["Yamaoka's Wrath", "The Oni", "Kazan Yamaoka"],
        "description": "Injured Survivors drop Blood Orbs that the Oni absorbs to charge his power. When full, activate Blood Fury to execute high-speed Demon Sprints and deadly Demon Strikes that instantly down Survivors.",
    },
    "the deathslinger": {
        "name": "The Redeemer",
        "movement_speed": "4.4 m/s (110%)",
        "terror_radius": "24 m",
        "terror_radius_meters": 24,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/77/IconPowers_theRedeemer.png",
        "targets": ["The Redeemer", "The Deathslinger", "Caleb Quinn"],
        "description": "Aim and fire a spear gun with a tethered chain to harpoon Survivors from range, reeling them in toward you for a basic attack or forcing them to break the chain and suffer Deep Wound.",
    },
    "the executioner": {
        "name": "Rites of Judgement",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c5/IconPowers_ritesOfJudgement.png",
        "targets": ["Rites of Judgement", "The Executioner", "Pyramid Head"],
        "description": "Carve trails of Torment into the ground. Survivors who step into the trails become Tormented. Unleash Punishment of the Damned to send shockwaves through obstacles, and send downed Tormented Survivors directly into Cages of Atonement or execute them with Final Judgement.",
    },
    "the blight": {
        "name": "Blighted Corruption",
        "movement_speed": "4.6 m/s (115%) / 9.2 m/s (Rush)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2f/IconPowers_blightedCorruption.png",
        "targets": ["Blighted Corruption", "The Blight", "Talbot Grimes"],
        "description": "Consume Rush Tokens to initiate high-speed Rushes. Slam into environmental obstacles to perform a Slam, resetting tokens and chaining into Lethal Rushes to strike Survivors across the map.",
    },
    "the twins": {
        "name": "Blood Bond",
        "movement_speed": "4.6 m/s (Charlotte) / 6.0 m/s (Victor)",
        "terror_radius": "32 m (Charlotte) / 0 m (Victor)",
        "terror_radius_meters": 32,
        "height": "Tall (Charlotte) / Short (Victor)",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7b/IconPowers_bloodBond.png",
        "targets": ["Blood Bond", "The Twins", "Charlotte & Victor Deshayes"],
        "description": "Release Victor from Charlotte's chest to control him independently. Victor moves with blinding speed, detects Survivors via Killer Instinct, and pounces onto Survivors to latch on, injure, or down them.",
    },
    "the trickster": {
        "name": "Showstopper",
        "movement_speed": "4.4 m/s (110%)",
        "terror_radius": "24 m (40 m Lullaby)",
        "terror_radius_meters": 24,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2f/IconPowers_showstopper.png",
        "targets": ["Showstopper", "The Trickster", "Ji-Woon Hak"],
        "description": "Throw a flurry of throwing blades at rapid speed. Each blade hit fills a Survivor's Laceration Meter, dealing damage once full. Rapid hits build up Main Event, unlocking an automatic stream of infinite blades.",
    },
    "the nemesis": {
        "name": "T-Virus",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/4/4b/IconPowers_t-Virus.png",
        "targets": ["T-Virus", "The Nemesis", "Nemesis T-Type"],
        "description": "Whip Survivors with your Tentacle Strike to infect them with the T-Virus and advance through Mutation rates (Tier I, II, III). Higher tiers increase range and allow destroying pallets and breakable walls. AI-controlled Zombies roam the map.",
    },
    "the cenobite": {
        "name": "Summons of Pain",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2e/IconPowers_summonsOfPain.png",
        "targets": ["Summons of Pain", "The Cenobite", "Pinhead (Elliot Spencer)"],
        "description": "Spawn a gateway and guide a possessed Chain projectile to snare Survivors. The Lament Configuration puzzle box spawns in the Trial; if Survivors neglect it, a universal Chain Hunt relentlessly attacks all Survivors.",
    },
    "the artist": {
        "name": "Birds of Torment",
        "movement_speed": "4.4 m/s (110%)",
        "terror_radius": "24 m",
        "terror_radius_meters": 24,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/30/IconPowers_birdsOfTorment.png",
        "targets": ["Birds of Torment", "The Artist", "Carmina Mora"],
        "description": "Summon Dire Crows and launch them across the entire map in straight trajectories. Crows reveal Survivors with a swarm or injure Survivors if launched within close range or through obstacles.",
    },
    "the onryō": {
        "name": "Deluge of Fear",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "24 m (0 m Demanifested + 24 m Lullaby)",
        "terror_radius_meters": 24,
        "height": "Short",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/0c/IconPowers_delugeOfFear.png",
        "targets": ["Deluge of Fear", "The Onryō", "The Onryo", "Sadako Yamamura"],
        "description": "Manifest to enter and exit invisibility. Demanifested Sadako is Undetectable and can Project herself directly to active TVs near Survivors, spreading Condemned stacks. Fully Condemned Survivors can be instantly killed by hand.",
    },
    "the dredge": {
        "name": "Reign of Darkness",
        "movement_speed": "4.6 m/s (115%) / 12-38 m/s (Teleport)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/d3/IconPowers_reignOfDarkness.png",
        "targets": ["Reign of Darkness", "The Dredge"],
        "description": "Teleport between Lockers across the map and leave behind a Remnant to return to. When the Nightfall meter fills from injuries and teleports, total darkness envelops the Trial, blinding Survivors and granting Dredge extreme mobility.",
    },
    "the mastermind": {
        "name": "Virulent Bound",
        "movement_speed": "4.6 m/s (115%) / 14.0 m/s (Bound)",
        "terror_radius": "40 m",
        "terror_radius_meters": 40,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPowers_virulentBound.png",
        "targets": ["Virulent Bound", "The Mastermind", "Albert Wesker"],
        "description": "Charge two high-speed Bound attacks to vault obstacles and slam into Survivors, infecting them with Uroboros and tossing or slamming them into walls for heavy damage.",
    },
    "the knight": {
        "name": "Guardia Compagnia",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/d/df/IconPowers_guardiaCompagnia.png",
        "targets": ["Guardia Compagnia", "The Knight", "Tarhos Kovács"],
        "description": "Draw a patrol path and summon one of three loyal Guards (The Carnifex, The Assassin, The Jailer) to patrol the area, hunt Survivors, or damage generators and pallets automatically.",
    },
    "the skull merchant": {
        "name": "Eyes in the Sky",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c5/IconPowers_eyesInTheSky.png",
        "targets": ["Eyes in the Sky", "The Skull Merchant", "Adriana Imai"],
        "description": "Deploy Eyes in the Sky Drones that scan zones with detection lines. Survivors scanned gain Lock-On stacks; full Lock-On inflicts Claw Traps, Hindered, and Broken while tracking their positions on the Radar.",
    },
    "the singularity": {
        "name": "Quantum Instantiation",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/0/08/IconPowers_quantumInstantiation.png",
        "targets": ["Quantum Instantiation", "The Singularity", "HUX-A7-13"],
        "description": "Fire Biopods onto walls and ceilings to surveil the map. Target Survivors through Biopods to apply Temporal Slipstreams, allowing the Singularity to teleport directly behind them into Overclock mode.",
    },
    "the xenomorph": {
        "name": "Hidden Pursuit",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m (24 m Crawler Mode)",
        "terror_radius_meters": 32,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c9/IconPowers_hiddenPursuit.png",
        "targets": ["Hidden Pursuit", "The Xenomorph", "Xenomorph"],
        "description": "Access a subterranean Tunnel System under Control Stations to travel anywhere with extreme speed. Exiting tunnels triggers Crawler Mode, reducing Terror Radius and enabling a lethal Tail Attack.",
    },
    "the good guy": {
        "name": "Playtime's Over",
        "movement_speed": "4.4 m/s (110%) / 8.28 m/s (Slice & Dice)",
        "terror_radius": "32 m (0 m Hidey-Ho)",
        "terror_radius_meters": 32,
        "height": "Short",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPowers_playtimesOver.png",
        "targets": ["Playtime's Over", "The Good Guy", "Chucky (Charles Lee Ray)"],
        "description": "Enter Hidey-Ho Mode to become Undetectable and spawn phantom footsteps. While in Hidey-Ho Mode, perform a Scamper under pallets or unleash a high-speed Slice & Dice charge attack.",
    },
    "the unknown": {
        "name": "UVX",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/7/7b/IconPowers_uvx.png",
        "targets": ["UVX", "The Unknown"],
        "description": "Launch bouncing UVX projectiles that create a blast radius upon detonation, inflicting Weakened on Survivors or injuring Weakened Survivors. The Unknown leaves behind Hallucinations to teleport to instantly.",
    },
    "the lich": {
        "name": "Vile Darkness",
        "movement_speed": "4.6 m/s (115%) / 7.0 m/s (Fly)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/23/IconPowers_vileDarkness.png",
        "targets": ["Vile Darkness", "The Lich", "Vecna"],
        "description": "Wield four distinct dark spells: Mage Hand (lifts or blocks pallets), Flight of the Damned (summons flying spectral skeletons), Dispelling Sphere (invisible sphere disabling magic items), and Fly (grants airborne flight speed).",
    },
    "the dark lord": {
        "name": "Vampiric Shift",
        "movement_speed": "4.6 m/s (115%) / 6.0 m/s (Wolf)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/a/a2/IconPowers_vampiricShift.png",
        "targets": ["Vampiric Shift", "The Dark Lord", "Dracula (Vlad Tepes)"],
        "description": "Shift between three monstrous forms: Vampire Form (casts Hellfire pillars over obstacles), Bat Form (invisible flight and teleport to vault locations), and Wolf Form (scents blood trails and unleashes Pounce attacks).",
    },
    "the houndmaster": {
        "name": "Command: Search & Chase",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/8/86/IconPowers_commandSearchAndChase.png",
        "targets": ["Command: Search & Chase", "The Houndmaster", "Portia Maye"],
        "description": "Issue commands to your faithful hunting hound, Snag. Command: Search sends the hound to scout ahead and reveal Survivors. Command: Chase directs the hound to charge, pounce, and drag Survivors back toward you.",
    },
    "the ghoul": {
        "name": "Rinkaku Kagune",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Average",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/30/IconPowers_birdsOfTorment.png",
        "targets": ["Rinkaku Kagune", "The Ghoul", "Ken Kaneki"],
        "description": "Unleash predatory Rinkaku Kagune tentacles from your back to pierce through obstacles, vault elevations rapidly, and impale fleeing survivors from distance.",
    },
    "the animatronic": {
        "name": "Springlock Malfunction",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/1/14/IconPowers_playtimesOver.png",
        "targets": ["Springlock Malfunction", "The Animatronic", "Springtrap", "William Afton"],
        "description": "Sabotage ventilation and audio systems across the realm. Activate Phantom Audio hallucinations to lure survivors into deadly springlock ambushes.",
    },
    "the krasue": {
        "name": "Nocturnal Severance",
        "movement_speed": "4.4 m/s (110%)",
        "terror_radius": "24 m",
        "terror_radius_meters": 24,
        "height": "Short",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/ca/IconPowers_blackenedCatalyst.png",
        "targets": ["Nocturnal Severance", "The Krasue", "Krasue"],
        "description": "Detach your head and glowing internal organs from your body to fly silently over obstacles and inflict lingering septic curses on survivors.",
    },
    "the slasher": {
        "name": "Relentless Stalker",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/3/3d/IconPowers_nightShroud.png",
        "targets": ["Relentless Stalker", "The Slasher", "Jason Voorhees"],
        "description": "Channel pure unstoppable momentum to smash through barricades instantly, shift silently across fog-covered paths, and execute brutal machete strikes.",
    },
    "the first": {
        "name": "Primordial Blight",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/2/2f/IconPowers_blightedCorruption.png",
        "targets": ["Primordial Blight", "The First"],
        "description": "Channel the raw primordial energy of the Fog before the Realms were forged, warping reality, corrupting generator foundations, and manifesting entity claws.",
    },
    "the judgment": {
        "name": "Pyre of Heresy",
        "movement_speed": "4.6 m/s (115%)",
        "terror_radius": "32 m",
        "terror_radius_meters": 32,
        "height": "Tall",
        "icon_url": "https://static.wikia.nocookie.net/deadbydaylight_gamepedia_en/images/c/c5/IconPowers_ritesOfJudgement.png",
        "targets": ["Pyre of Heresy", "The Judgment"],
        "description": "Branded heretic glyphs burst into holy fire beneath running survivors, exposing false paths and sentencing survivors to the cleansing pyre.",
    },
}

CHARACTER_ALIASES: Dict[str, str] = {
    "ash": "Ashley J. Williams",
    "ash williams": "Ashley J. Williams",
    "ashley williams": "Ashley J. Williams",
    "ashley j. williams": "Ashley J. Williams",
    "nancy": "Nancy Wheeler",
    "nancy wheeler": "Nancy Wheeler",
    "steve": "Steve Harrington",
    "steve harrington": "Steve Harrington",
    "bill": 'William "Bill" Overbeck',
    "bill overbeck": 'William "Bill" Overbeck',
    "william bill overbeck": 'William "Bill" Overbeck',
    'william "bill" overbeck': 'William "Bill" Overbeck',
    "quentin": "Quentin Smith",
    "quentin smith": "Quentin Smith",
    "tapp": "Detective Tapp",
    "detective tapp": "Detective Tapp",
    "david tapp": "Detective Tapp",
    "adam": "Adam Francis",
    "adam francis": "Adam Francis",
    "jeff": "Jeff Johansen",
    "jeff johansen": "Jeff Johansen",
    "jane": "Jane Romero",
    "jane romero": "Jane Romero",
    "yui": "Yui Kimura",
    "yui kimura": "Yui Kimura",
    "zarina": "Zarina Kassir",
    "zarina kassir": "Zarina Kassir",
    "cheryl": "Cheryl Mason",
    "heather": "Cheryl Mason",
    "cheryl mason": "Cheryl Mason",
    "felix": "Felix Richter",
    "felix richter": "Felix Richter",
    "elodie": "Élodie Rakoto",
    "élodie": "Élodie Rakoto",
    "elodie rakoto": "Élodie Rakoto",
    "élodie rakoto": "Élodie Rakoto",
    "yun-jin": "Yun-Jin Lee",
    "yun-jin lee": "Yun-Jin Lee",
    "yunjin": "Yun-Jin Lee",
    "yunjin lee": "Yun-Jin Lee",
    "lee yun-jin": "Yun-Jin Lee",
    "mikaela": "Mikaela Reid",
    "mikaela reid": "Mikaela Reid",
    "jonah": "Jonah Vasquez",
    "jonah vasquez": "Jonah Vasquez",
    "yoichi": "Yoichi Asakawa",
    "yoichi asakawa": "Yoichi Asakawa",
    "haddie": "Haddie Kaur",
    "haddie kaur": "Haddie Kaur",
    "ada": "Ada Wong",
    "ada wong": "Ada Wong",
    "rebecca": "Rebecca Chambers",
    "rebecca chambers": "Rebecca Chambers",
    "vittorio": "Vittorio Toscano",
    "vittorio toscano": "Vittorio Toscano",
    "thalita": "Thalita Lyra",
    "thalita lyra": "Thalita Lyra",
    "renato": "Renato Lyra",
    "renato lyra": "Renato Lyra",
    "gabriel": "Gabriel Soma",
    "gabriel soma": "Gabriel Soma",
    "nicolas": "Nicolas Cage",
    "nicolas cage": "Nicolas Cage",
    "ellen": "Ellen Ripley",
    "ellen ripley": "Ellen Ripley",
    "ripley": "Ellen Ripley",
    "sable": "Sable Ward",
    "sable ward": "Sable Ward",
    "estranho": "The Unknown",
    "alan": "Alan Wake",
    "alan wake": "Alan Wake",
    "lara": "Lara Croft",
    "lara croft": "Lara Croft",
    "trevor": "Trevor Belmont",
    "trevor belmont": "Trevor Belmont",
    "orela": "Orela Rose",
    "orela rose": "Orela Rose",
    "taurie": "Taurie Cain",
    "taurie cain": "Taurie Cain",
    "leon": "Leon S. Kennedy",
    "leon kennedy": "Leon S. Kennedy",
    "leon s. kennedy": "Leon S. Kennedy",
    "jill": "Jill Valentine",
    "jill valentine": "Jill Valentine",
    "aestri": "Aestri Yazar",
    "baermar": "Aestri Yazar",
    "aestri yazar": "Aestri Yazar",
    "baermar uraz": "Aestri Yazar",
    "aestri yazar & baermar uraz": "Aestri Yazar",
    "the troupe": "Aestri Yazar",
    "bard": "Aestri Yazar",
    "the onryo": "The Onryō",
    "onryo": "The Onryō",
    "onryō": "The Onryō",
}

EXCLUDED_SLUGS: Set[str] = {
    "entity",
    "generator",
    "hatch",
    "chest",
    "item",
    "perk",
    "perks",
    "killers",
    "survivors",
    "tome",
    "observer",
    "vigo",
    "void",
    "stagger",
    "hook",
    "obsession",
    "blindness",
    "exhausted",
    "mangled",
    "broken",
    "exposed",
    "hindered",
    "oblivious",
    "aura",
    "scratch_marks",
    "pools_of_blood",
    "terror_radius",
    "basement",
    "exit_gate_switch",
    "skill_check",
    "loud_noise_notification",
    "conspicuous_action",
    "health_state",
    "injured_state",
    "protection_hit",
    "special_attack",
    "special_attacks",
    "crow",
    "window",
    "med-kit",
    "med-kits",
    "toolbox",
    "flashlight",
    "flashlights",
    "key",
    "keys",
    "add-on",
    "add-ons",
    "playing_survivor:_tips_and_tricks",
    "characters",
    "the_campfire",
    "status_effects",
    "realm",
    "realms",
    "map",
    "maps",
}