# backend/app/scrapers/constants.py
from typing import Dict, Tuple

GENERIC_PERK_CANONICAL_MAP: Dict[str, Tuple[str, str]] = {
    "will to live": ("Decisive Strike", "Will to Live"),
    "down to the last": ("Sole Survivor", "Down to the Last"),
    "bound by obsession": ("Object of Obsession", "Bound by Obsession"),
    "keep them waiting": ("Save the Best for Last", "Keep Them Waiting"),
    "see how they run": ("Play with Your Food", "See How They Run"),
    "cull the weak": ("Dying Light", "Cull the Weak"),
    "no holds barred": ("Deadlock", "No Holds Barred"),
    "hex fortune s fool": ("Hex: Plaything", "Hex: Fortune's Fool"),
    "hex fortunes fool": ("Hex: Plaything", "Hex: Fortune's Fool"),
    "scourge hook weeping wounds": ("Scourge Hook: Gift of Pain", "Scourge Hook: Weeping Wounds"),
    "jolt": ("Surge", "Jolt"),
    "fearmonger": ("Mindbreaker", "Fearmonger"),
    "claustrophobia": ("Cruel Limits", "Claustrophobia"),
    "guardian": ("Babysitter", "Guardian"),
    "kinship": ("Camaraderie", "Kinship"),
    "self aware": ("Fixated", "Self-Aware"),
    "selfaware": ("Fixated", "Self-Aware"),
    "situational awareness": ("Better Together", "Situational Awareness"),
    "inner healing": ("Inner Strength", "Inner Healing"),
    "renewal": ("Second Wind", "Renewal"),
}

KNOWN_KILLER_POWER_ALIASES: Dict[str, str] = {
    "bear trap": "The Trapper",
    "bear traps": "The Trapper",
    "wailing bell": "The Wraith",
    "the chainsaw": "The Hillbilly",
    "chainsaw": "The Hillbilly",
    "spencer s last breath": "The Nurse",
    "spencers last breath": "The Nurse",
    "evil within": "The Shape",
    "blackened catalyst": "The Hag",
    "carter s spark": "The Doctor",
    "carters spark": "The Doctor",
    "hunting hatchets": "The Huntress",
    "hunting hatchet": "The Huntress",
    "bubba s chainsaw": "The Cannibal",
    "bubbas chainsaw": "The Cannibal",
    "dream demon": "The Nightmare",
    "jigsaw s baptism": "The Pig",
    "jigsaws baptism": "The Pig",
    "the afterpiece tonic": "The Clown",
    "afterpiece tonic": "The Clown",
    "yamaoka s haunting": "The Spirit",
    "yamaokas haunting": "The Spirit",
    "feral frenzy": "The Legion",
    "vile purge": "The Plague",
    "night shroud": "The Ghost Face",
    "of the abyss": "The Demogorgon",
    "yamaoka s wrath": "The Oni",
    "yamaokas wrath": "The Oni",
    "the redeemer": "The Deathslinger",
    "redeemer": "The Deathslinger",
    "rites of judgement": "The Executioner",
    "blighted corruption": "The Blight",
    "blood bond": "The Twins",
    "showstopper": "The Trickster",
    "t virus": "The Nemesis",
    "summons of pain": "The Cenobite",
    "birds of torment": "The Artist",
    "deluge of fear": "The Onryō",
    "reign of darkness": "The Dredge",
    "virulent bound": "The Mastermind",
    "guardia compagnia": "The Knight",
    "eyes in the sky": "The Skull Merchant",
    "quantum instantiation": "The Singularity",
    "hidden pursuit": "The Xenomorph",
    "playtime s over": "The Good Guy",
    "playtimes over": "The Good Guy",
    "uvx": "The Unknown",
    "vile darkness": "The Lich",
    "viledarkness": "The Lich",
    "vampiric shift": "The Dark Lord",
    "scent of blood": "The Houndmaster",
    "one eyed terror": "The Ghoul",
    "fazbear s fright": "The Animatronic",
    "fazbears fright": "The Animatronic",
    "unbodied flesh": "The Krasue",
    "test subject 001": "The First",
    "test subject 1": "The First",
    "omnipresent evil": "The Slasher",
    "will of the gods": "The Judgment",
}
