// frontend/src/components/smash-or-pass/characterRoster.ts

export type CharacterGender = 'female' | 'male' | 'monster_other';
export type CharacterRole = 'Killer' | 'Survivor';

export interface CharacterRosterItem {
  slug: string;
  name: string;
  realName?: string;
  role: CharacterRole;
  gender: CharacterGender;
  title: string;
  tagline: string;
  bio: string;
  quote: string;
  greenFlags: string[];
  redFlags: string[];
  datingVibe?: string;
  turnOn: string;
  dealbreaker: string;
  height?: string;
  chapter?: string;
}

export const ALL_CHARACTER_SLUGS: string[] = [
  // 54 SURVIVORS
  'ace_visconti', 'adam_francis', 'ada_wong', 'alan_wake', 'ash_williams', 'aurora_stardotter',
  'bill_overbeck', 'cheryl_mason', 'claudette_morel', 'david_king', 'david_tapp', 'dustin_henderson',
  'dwight_fairfield', 'eleven', 'ellen_ripley', 'felix_richter', 'feng_min', 'gabriel_soma',
  'haddie_kaur', 'jake_park', 'jane_romero', 'jeff_johansen', 'jill_valentine', 'jonah_vasquez',
  'kate_denson', 'kwon_tae_young', 'lara_croft', 'laurie_strode', 'lee_yun_jin', 'leon_scott_kennedy',
  'meg_thomas', 'michonne_grimes', 'mikaela_reid', 'nancy_wheeler', 'nea_karlsson', 'nicolas_cage',
  'orela_rose', 'quentin_smith', 'rebecca_chambers', 'renato_lyra', 'rick_grimes', 'sable_ward',
  'shane_wiigwaas', 'steve_harrington', 'taurie_cain', 'thalita_lyra', 'the_troupe', 'trevor_belmont',
  'vee_boonyasak', 'vittorio_toscano', 'yoichi_asakawa', 'yui_kimura', 'zarina_kassir', 'élodie_rakoto',

  // 44 KILLERS
  'the_animatronic', 'the_artist', 'the_blight', 'the_cannibal', 'the_cenobite', 'the_clown',
  'the_dark_lord', 'the_deathslinger', 'the_demogorgon', 'the_doctor', 'the_dredge', 'the_executioner',
  'the_first', 'the_ghost_face', 'the_ghoul', 'the_good_guy', 'the_hag', 'the_hillbilly',
  'the_houndmaster', 'the_huntress', 'the_judgment', 'the_knight', 'the_krasue', 'the_legion',
  'the_lich', 'the_mastermind', 'the_nemesis', 'the_nightmare', 'the_nurse', 'the_oni',
  'the_onryō', 'the_pig', 'the_plague', 'the_shape', 'the_singularity', 'the_skull_merchant',
  'the_slasher', 'the_spirit', 'the_trapper', 'the_trickster', 'the_twins', 'the_unknown',
  'the_wraith', 'the_xenomorph'
];

export const CHARACTER_ROSTER: Record<string, CharacterRosterItem> = {
  // ==========================================
  // FEMALE SURVIVORS (28)
  // ==========================================
  ada_wong: {
    slug: 'ada_wong',
    name: 'Ada Wong',
    realName: 'Ada Wong',
    role: 'Survivor',
    gender: 'female',
    title: 'The Enigmatic Operative',
    tagline: 'High heels, grappling hooks, and secrets you will never uncover.',
    bio: 'Secret agent who always looks immaculate mid-chase. Will disappear for 3 months and reappear with classified intel and a smirk.',
    quote: '"Some things are better left unsaid, but you can buy me a martini first."',
    greenFlags: ['Always has an escape route', 'Impeccable fashion sense in a foggy apocalypse', 'Never texts back too quickly'],
    redFlags: ['Will grapple hook out of the window if you bring up commitment', 'Works for 4 rival espionage syndicates simultaneously'],
    datingVibe: 'Sultry, elusive, high-stakes romance',
    turnOn: 'Wiretap perks and mystery',
    dealbreaker: 'Asking too many personal questions',
    chapter: 'Resident Evil',
  },
  sable_ward: {
    slug: 'sable_ward',
    name: 'Sable Ward',
    realName: 'Sable Ward',
    role: 'Survivor',
    gender: 'female',
    title: 'The Goth Invocator',
    tagline: 'Basement rituals, black lipstick, and infinite eyeliner.',
    bio: 'Drawn straight into the Fog through occult basement invocation. Will invite you to hang out in the Killer Shack basement and play vinyl records.',
    quote: '"If you can’t handle me in the basement, you don’t deserve me at the exit gate."',
    greenFlags: ['Listens to Bauhaus and The Cure', 'Looks stunning in monochrome', 'Will invoke the entity just to hang out with you'],
    redFlags: ['Spends 90% of the match in the basement', 'Might use your blood for an invocation circle'],
    datingVibe: 'Gothic romanticism & basement vibes',
    turnOn: 'Occult circles and dark poetry',
    dealbreaker: 'Being afraid of the dark',
    chapter: 'All Things Wicked',
  },
  feng_min: {
    slug: 'feng_min',
    name: 'Feng Min',
    realName: 'Feng Min',
    role: 'Survivor',
    gender: 'female',
    title: 'The Competitive Gamer',
    tagline: 'Litheness, bunny hoodies, and 3 AM ranked grinding.',
    bio: 'Former esports prodigy with over 400 cosmetic outfits. Highly competitive, will rage-quit if you miss a Great Skill Check.',
    quote: '"GG WP, or maybe you should buy me boba tea and we try again?"',
    greenFlags: ['Has an outfit for every aesthetic', 'Can Lithe vault any obstacle', 'Can carry you in 2v8 matches'],
    redFlags: ['Blames lag whenever things go wrong', 'Has missed 0.1% skill check and destroyed keyboard'],
    datingVibe: 'Chaotic gamer sweetheart with bunny ears',
    turnOn: 'Clutch flashlight saves and energy drinks',
    dealbreaker: 'Being a casual non-gamer',
    chapter: 'Spark of Madness',
  },
  kate_denson: {
    slug: 'kate_denson',
    name: 'Kate Denson',
    realName: 'Kate Denson',
    role: 'Survivor',
    gender: 'female',
    title: 'The Country Songbird',
    tagline: 'Acoustic serenades around the campfire with golden heart energy.',
    bio: 'Traveling musician with a golden voice that can soothe any raging Killer. Will write a Billboard top-10 country ballad about your trial escapes.',
    quote: '"Music is the only thing the Fog can’t swallow whole."',
    greenFlags: ['Writes songs about you', 'Windows of Opportunity queen', 'Radiates pure sunshine and warmth'],
    redFlags: ['Will serenade the Killer instead of running', 'Leaves acoustic guitars in every generator spot'],
    datingVibe: 'Wholesome campfire country romance',
    turnOn: 'Singing in harmony by the moonlight',
    dealbreaker: 'Noise complaints and cynicism',
    chapter: 'Curtain Call',
  },
  mikaela_reid: {
    slug: 'mikaela_reid',
    name: 'Mikaela Reid',
    realName: 'Mikaela Reid',
    role: 'Survivor',
    gender: 'female',
    title: 'The Witch of the Boon',
    tagline: 'Coffee brews, tarot readings, and blue totems everywhere.',
    bio: 'Barista, horror writer, and certified witch. Blesses blue totems across the map so you can heal in 4 seconds flat.',
    quote: '"I pulled The Lovers and The Tower from the deck. Prepare for drama."',
    greenFlags: ['Makes the best artisanal espresso in the Fog', 'Boon: Circle of Healing always active', 'Reads your astrological birth chart accurately'],
    redFlags: ['Will spend 5 minutes blessing a dull totem while you are on second hook', 'Her crystals have bad energy occasionally'],
    datingVibe: 'Mystical witchy girlfriend with coffee addiction',
    turnOn: 'Fresh ground coffee beans and scented candles',
    dealbreaker: 'Disrespecting the tarot cards',
    chapter: 'Hour of the Witch',
  },
  jill_valentine: {
    slug: 'jill_valentine',
    name: 'Jill Valentine',
    realName: 'Jill Valentine',
    role: 'Survivor',
    gender: 'female',
    title: 'The Master of Unlocking',
    tagline: 'S.T.A.R.S. veteran who plants blast mines on generators for fun.',
    bio: 'Bio-hazard survivor who eats Nemesis rocket launchers for breakfast. Tough, brave, and will rig the generator to blind anyone who kicks it.',
    quote: '"You want S.T.A.R.S.? I’ll give you S.T.A.R.S."',
    greenFlags: ['Blast Mine traps provide endless comedy', 'Survives literally anything', 'Can lockpick anything from chests to your heart'],
    redFlags: ['Attracts 8-foot tall bio-weapons with rocket launchers', 'Will treat a casual date like a military SWAT op'],
    datingVibe: 'Action-hero badass with tactical romance',
    turnOn: 'Flashbangs and perfect generator timing',
    dealbreaker: 'Cowardice in the face of danger',
    chapter: 'Resident Evil',
  },
  lara_croft: {
    slug: 'lara_croft',
    name: 'Lara Croft',
    realName: 'Lara Croft',
    role: 'Survivor',
    gender: 'female',
    title: 'The Tomb Raider',
    tagline: 'Acrobatic treasure hunter with zero fear of the unknown.',
    bio: 'World-renowned archaeologist who dives into ancient tombs and dodges rolling boulders for sport. Vaults windows faster than thought.',
    quote: '"The extraordinary is in what we do, not who we are."',
    greenFlags: ['Finesse vault speed', 'Rich, brilliant, and travels the globe', 'Can climb out of any sticky situation'],
    redFlags: ['Will drag you into cursed ancient temples', 'Might trade you for an ancient relic'],
    datingVibe: 'High-octane globetrotting adventure',
    turnOn: 'Ancient languages and cliffhanger jumps',
    dealbreaker: 'Complaining about hiking',
    chapter: 'Tomb Raider',
  },
  rebecca_chambers: {
    slug: 'rebecca_chambers',
    name: 'Rebecca Chambers',
    realName: 'Rebecca Chambers',
    role: 'Survivor',
    gender: 'female',
    title: 'The Rookie Medic',
    tagline: 'Thumbs up, hyperfocus skill checks, and instant medical care.',
    bio: 'S.T.A.R.S. field medic prodigy. Will give you a signature thumbs-up and patch up every arterial wound with a smile.',
    quote: '"Hang in there! We’ve got this together!"',
    greenFlags: ['Reassurance perks keep you off the hook', 'Hyperfocus generator speed', 'Literal genius medical prodigy'],
    redFlags: ['Too wholesome for her own good', 'Forces you to take your vitamins'],
    datingVibe: 'Sweet, supportive, pure sunshine medic',
    turnOn: 'Great Skill Checks and clean first-aid kits',
    dealbreaker: 'Giving up before the exit gates open',
    chapter: 'Resident Evil: PROJECT W',
  },
  jane_romero: {
    slug: 'jane_romero',
    name: 'Jane Romero',
    realName: 'Jane Romero',
    role: 'Survivor',
    gender: 'female',
    title: 'The Influential Host',
    tagline: 'Head On locker stuns, talk-show charisma, and sheer presence.',
    bio: 'Celebrity talk-show host with curves that defy entity gravity and a Head On stun that will send any killer flying.',
    quote: '"Don’t let anyone make you feel small. Especially not a killer in a mask."',
    greenFlags: ['Head On locker stuns save matches', 'Charismatic, empathetic, and inspiring', 'Looks spectacular in every outfit'],
    redFlags: ['Needs the spotlight at all times', 'Might interview you on your worst moments'],
    datingVibe: 'Glamorous, empowered powerhouse',
    turnOn: 'Confidence and locker timing',
    dealbreaker: 'Insecurity and petty jealousy',
    chapter: 'Demise of the Faithful',
  },
  yui_kimura: {
    slug: 'yui_kimura',
    name: 'Yui Kimura',
    realName: 'Yui Kimura',
    role: 'Survivor',
    gender: 'female',
    title: 'The Hardened Street Racer',
    tagline: 'Leather jackets, neon motorcycles, and resetting dropped pallets.',
    bio: 'Leader of an all-female street racing gang in Tokyo. Strong, rebellious, and resets pallets so you can loop for another 5 minutes.',
    quote: '"Never back down, never surrender the road."',
    greenFlags: ['Any Means Necessary pallet resetter', 'Rides custom street bikes', 'Unbreakable loyalty to friends'],
    redFlags: ['Has 14 speeding tickets in the Fog', 'Fixes exhaust pipes at 4 AM'],
    datingVibe: 'Badass biker girl with a loyal heart',
    turnOn: 'Revving engines and tight turns',
    dealbreaker: 'Telling her to slow down',
    chapter: 'Cursed Legacy',
  },
  zarina_kassir: {
    slug: 'zarina_kassir',
    name: 'Zarina Kassir',
    realName: 'Zarina Kassir',
    role: 'Survivor',
    gender: 'female',
    title: 'The Truth-Seeking Filmmaker',
    tagline: 'Documentary director, For The People heroics, and investigative fire.',
    bio: 'Documentarian who dives into maximum-security secrets. Will sacrifice her own health state with For The People to save you.',
    quote: '"The truth is always worth fighting for."',
    greenFlags: ['Insta-heals you with For The People', 'Incredible storyteller and filmmaker', 'Sharp eye for detail'],
    redFlags: ['Will document your embarrassing moments in 4K', 'Overthinks every conversation'],
    datingVibe: 'Intellectual, fiercely compassionate crusader',
    turnOn: 'Courage under pressure and cinematic lighting',
    dealbreaker: 'Lying or keeping toxic secrets',
    chapter: 'Chains of Hate',
  },
  thalita_lyra: {
    slug: 'thalita_lyra',
    name: 'Thalita Lyra',
    realName: 'Thalita Lyra',
    role: 'Survivor',
    gender: 'female',
    title: 'The Rio Kite Fighter',
    tagline: 'Sunny beaches, kite combat, and infectious Brazilian warmth.',
    bio: 'Kite fighting champion from Rio de Janeiro with vibrant energy and cooperative speed buffs. Will turn any dark trial into a summer festival.',
    quote: '"You keep your eyes on the wind, I’ll keep my eyes on you."',
    greenFlags: ['Friendly Competition buffs', 'Radiates joyful carnival energy', 'Protective older sister energy'],
    redFlags: ['Competes over literally everything including breakfast', 'Her brother Renato tags along everywhere'],
    datingVibe: 'Vibrant, sun-kissed, high-energy romance',
    turnOn: 'Beach volleyball and synchronized teamwork',
    dealbreaker: 'Sulking and gloomy bad attitudes',
    chapter: 'Tools of Torment',
  },
  cheryl_mason: {
    slug: 'cheryl_mason',
    name: 'Cheryl Mason',
    realName: 'Cheryl Mason / Heather',
    role: 'Survivor',
    gender: 'female',
    title: 'The Reincarnated Survivor',
    tagline: 'Silent Hill veteran, Soul Guard endurance, and demon slayer.',
    bio: 'Survived god-like cults and foggy otherworlds long before the Entity came calling. Unshakable resolve with a dark past.',
    quote: '"Is every town I visit covered in mist and monsters? Really?"',
    greenFlags: ['Soul Guard endurance is godly', 'Fearless against eldritch abominations', 'Has seen worse than the Entity'],
    redFlags: ['Rust and sirens trigger flashbacks', 'May attract god-cults to family dinners'],
    datingVibe: 'Resilient, moody, cult-slaying heroine',
    turnOn: 'Quiet rainy nights and flashlights',
    dealbreaker: 'Religious cults and radio static',
    chapter: 'Silent Hill',
  },
  nea_karlsson: {
    slug: 'nea_karlsson',
    name: 'Nea Karlsson',
    realName: 'Nea Karlsson',
    role: 'Survivor',
    gender: 'female',
    title: 'The Urban Artist',
    tagline: 'Graffiti, Urban Evasion crouch-walking, and street rebellion.',
    bio: 'Swedish skater and graffiti artist. Masters Urban Evasion to glide unseen around obstacles while leaving neon art across the Fog.',
    quote: '"Tagging the Entity’s realm with neon spray paint is my love language."',
    greenFlags: ['Urban Evasion crouch master', 'Great artistic eye', 'Fearless skate park rebel'],
    redFlags: ['Crouch-walks everywhere including restaurants', 'Left spray paint on your car'],
    datingVibe: 'Grungy rebel with underground street cred',
    turnOn: 'Fresh Krylon spray cans and high rooftops',
    dealbreaker: 'Rules, curfew, and law enforcement',
    chapter: 'The Last Breath',
  },
  meg_thomas: {
    slug: 'meg_thomas',
    name: 'Meg Thomas',
    realName: 'Meg Thomas',
    role: 'Survivor',
    gender: 'female',
    title: 'The Energetic Sprinter',
    tagline: 'Sprint Burst away from all commitment at 150% speed.',
    bio: 'High school track athlete with endless cardio and a habit of dropping every pallet on the map within the first 60 seconds.',
    quote: '"Catch me if you can! (Spoiler: You can’t)."',
    greenFlags: ['Sprint Burst into your DMs', 'Infinite stamina and cardio', 'Will run 10k with you'],
    redFlags: ['Sprint Bursts into walls', 'Dropped all shack pallets in 10 seconds'],
    datingVibe: 'Athletic, bubbly, spontaneous chaos',
    turnOn: 'Adrenaline surges and running sneakers',
    dealbreaker: 'Couch potatoes who refuse to run',
    chapter: 'Base Game',
  },
  claudette_morel: {
    slug: 'claudette_morel',
    name: 'Claudette Morel',
    realName: 'Claudette Morel',
    role: 'Survivor',
    gender: 'female',
    title: 'The Botanical Healer',
    tagline: 'Self-Care in the bush, herbal remedies, and shy genius.',
    bio: 'Introverted botanist with encyclopedic knowledge of medicinal plants. Blends into tall grass and bushes so well she becomes invisible.',
    quote: '"Plants don’t judge you. They just heal you if you treat them right."',
    greenFlags: ['Botanical knowledge makes delicious teas', 'Empathy lets her feel your pain', 'Gentle, thoughtful, and kind'],
    redFlags: ['Spends 32 seconds Self-Caring against Sloppy Butcher in the map corner'],
    datingVibe: 'Soft-spoken, tender plant-mom romance',
    turnOn: 'Rare botanical specimens and quiet greenhouses',
    dealbreaker: 'Loud party animals who trample gardens',
    chapter: 'Base Game',
  },
  laurie_strode: {
    slug: 'laurie_strode',
    name: 'Laurie Strode',
    realName: 'Laurie Strode',
    role: 'Survivor',
    gender: 'female',
    title: 'The Original Final Girl',
    tagline: 'Decisive Strike glass shards and Halloween nightmare survival.',
    bio: 'The archetype of all horror Final Girls. Kept Michael Myers at bay for decades with a knitting needle and pure tenacity.',
    quote: '"It was the boogeyman... and I survived him."',
    greenFlags: ['Decisive Strike saves you in endgame', 'Unstoppable survival instincts', 'Classic 70s horror royalty'],
    redFlags: ['Her estranged brother is a 7-foot shape in a William Shatner mask'],
    datingVibe: 'Legendary, tough-as-nails survival romance',
    turnOn: 'Preparedness and fortified basements',
    dealbreaker: 'Halloween pranks involving masks',
    chapter: 'Halloween',
  },
  nancy_wheeler: {
    slug: 'nancy_wheeler',
    name: 'Nancy Wheeler',
    realName: 'Nancy Wheeler',
    role: 'Survivor',
    gender: 'female',
    title: 'The Hawkins Journalist',
    tagline: 'Shotgun aim, investigative grit, and Inner Strength locker heals.',
    bio: 'Hawkins High reporter who will unearth any conspiracy and pump 12-gauge shells into demogorgons without blinking.',
    quote: '"I don’t back down from a monster. Never have, never will."',
    greenFlags: ['Inner Strength locker heals', 'Brilliant investigative journalist', 'Can shoot Demogorgons with precision'],
    redFlags: ['Will interrogate your past like a suspect on trial'],
    datingVibe: 'Sharp, preppy, monster-hunting heroine',
    turnOn: 'Classified archives and investigative scoops',
    dealbreaker: 'Apathy and bad journalism',
    chapter: 'Stranger Things',
  },
  lee_yun_jin: {
    slug: 'lee_yun_jin',
    name: 'Yun-Jin Lee',
    realName: 'Yun-Jin Lee',
    role: 'Survivor',
    gender: 'female',
    title: 'The Ruthless Music Producer',
    tagline: 'Fur coats, Fast Track tokens, and calculating corporate ambition.',
    bio: 'High-powered K-pop music mogul. Will step over your downed body if it gives her 3 Fast Track tokens and an exit gate escape.',
    quote: '"In this business, only the winners get the encore."',
    greenFlags: ['Million-dollar wardrobe and diamond earrings', 'Can make you an international celebrity', 'Sharp business acumen'],
    redFlags: ['Fast Track means she gets stronger when you get hooked', 'Might renegotiate your relationship contract annually'],
    datingVibe: 'Luxury, ice-queen ambition with hidden passion',
    turnOn: 'Number one billboard tracks and luxury silk',
    dealbreaker: 'Unprofitable ventures and emotional weakness',
    chapter: 'All-Kill',
  },
  élodie_rakoto: {
    slug: 'élodie_rakoto',
    name: 'Élodie Rakoto',
    realName: 'Élodie Rakoto',
    role: 'Survivor',
    gender: 'female',
    title: 'The Occult Investigator',
    tagline: 'Paranormal treasure hunting, Parisian chic, and Deception locker tricks.',
    bio: 'Born in Paris to Malagasy heritage, traveled the globe uncovering Black Vale cult relics. Masters Deception to juke any killer.',
    quote: '"Secrets are just puzzles waiting for the right key."',
    greenFlags: ['Deception locker plays break killer ankles', 'Speaks 4 languages fluently', 'Globetrotting elegance'],
    redFlags: ['Hunted by ancient occult secret societies'],
    datingVibe: 'Sophisticated Parisian artifact hunter',
    turnOn: 'Ancient ciphers and leather journals',
    dealbreaker: 'Superstition without intellectual curiosity',
    chapter: 'A Binding of Kin',
  },
  haddie_kaur: {
    slug: 'haddie_kaur',
    name: 'Haddie Kaur',
    realName: 'Haddie Kaur',
    role: 'Survivor',
    gender: 'female',
    title: 'The Ravages of the Abyss Host',
    tagline: 'Paranormal podcasting, psychic sight, and blue hair highlights.',
    bio: 'Host of the underground podcast "Ravages of the Abyss". Can see residual psychic bleeding from the Fog and blinds killers with flashlights.',
    quote: '"I’ve heard the voices in the dark... and I’m talking back."',
    greenFlags: ['Residual Manifest gives free flashlights', 'Has top-charting paranormal podcast', 'Fearless psychic explorer'],
    redFlags: ['Records ambient audio while you sleep for ghost EVPs'],
    datingVibe: 'Psychic, brave, podcasting night-owl',
    turnOn: 'EVP recordings and haunted lighthouses',
    dealbreaker: 'Calling paranormal phenomena fake',
    chapter: 'Roots of Dread',
  },
  ellen_ripley: {
    slug: 'ellen_ripley',
    name: 'Ellen Ripley',
    realName: 'Ellen Ripley',
    role: 'Survivor',
    gender: 'female',
    title: 'The Nostromo Warrant Officer',
    tagline: 'Flame turrets, Chemical Traps, and Jonesy the cat lover.',
    bio: 'The toughest space warrant officer in the galaxy. Blew the Xenomorph out the airlock and sets Chemical Traps on pallets.',
    quote: '"Get away from her, you bitch!"',
    greenFlags: ['Loves cats (Jonesy)', 'Chemical Trap slows killers down', 'Unbreakable survival leadership'],
    redFlags: ['Has trust issues with android synthetics'],
    datingVibe: 'Gritty, no-nonsense sci-fi survivalist',
    turnOn: 'Flamethrowers and orange tabby cats',
    dealbreaker: 'Working for Weyland-Yutani Corporation',
    chapter: 'Alien',
  },
  taurie_cain: {
    slug: 'taurie_cain',
    name: 'Taurie Cain',
    realName: 'Taurie Cain',
    role: 'Survivor',
    gender: 'female',
    title: 'The Black Vale Devotee',
    tagline: 'Entity worship, dark ritual devotion, and sinister charisma.',
    bio: 'A high-ranking disciple of the Black Vale who willingly worships the Entity. Deeply fascinated by the dark trial architecture.',
    quote: '"The Entity does not punish us; it refines us through pain."',
    greenFlags: ['Unmatched knowledge of occult lore', 'Charismatic dark aesthetic', 'Fearless before monstrous killers'],
    redFlags: ['Might try to sacrifice you for brownie points with the Entity'],
    datingVibe: 'Devout, dangerous occult goth girl',
    turnOn: 'Black candles and ancient incantations',
    dealbreaker: 'Disrespecting the Entity’s grand design',
    chapter: 'Doomed Course',
  },
  michonne_grimes: {
    slug: 'michonne_grimes',
    name: 'Michonne',
    realName: 'Michonne',
    role: 'Survivor',
    gender: 'female',
    title: 'The Katana Survivor',
    tagline: 'Katana slashes, unyielding gaze, and post-apocalyptic grit.',
    bio: 'Iconic zombie apocalypse survivor who slices through walkers and killers with silent katana precision.',
    quote: '"You do what you have to do to survive."',
    greenFlags: ['Peerless close-quarters combat skills', 'Quiet, deeply loyal, and protective', 'Never panics under pressure'],
    redFlags: ['Hard to get her to open up emotionally'],
    datingVibe: 'Stoic, badass warrior with deep devotion',
    turnOn: 'Sharpened katanas and quiet loyalty',
    dealbreaker: 'Whining about minor inconveniences',
    chapter: 'The Walking Dead',
  },
  eleven: {
    slug: 'eleven',
    name: 'Eleven',
    realName: 'Jane Hopper / Eleven',
    role: 'Survivor',
    gender: 'female',
    title: 'The Telekinetic Girl',
    tagline: 'Eggo waffles, telekinetic powers, and Hawkins loyalty.',
    bio: 'Raised in Hawkins Lab with telekinetic psychic powers. Will flip trial vans and snap monster necks with a single thought.',
    quote: '"Friends don’t lie."',
    greenFlags: ['Can move generators with her mind', 'Unconditional friendship and loyalty', 'Fiercely protective of her loved ones'],
    redFlags: ['Nosebleeds whenever she uses psychic powers', 'Will consume your entire freezer of Eggos'],
    datingVibe: 'Sweet, protective psychic heroine',
    turnOn: 'Eggo waffles and retro 80s mixtapes',
    dealbreaker: 'Lying to friends',
    chapter: 'Stranger Things',
  },
  aurora_stardotter: {
    slug: 'aurora_stardotter',
    name: 'Aurora',
    realName: 'Aurora Stardotter',
    role: 'Survivor',
    gender: 'female',
    title: 'The Nordic Dreamer',
    tagline: 'Northern lights, celestial navigation, and warm winter wool.',
    bio: 'Astronomer and folklore enthusiast from the Nordic fjords who charts starry constellations in the Fog.',
    quote: '"Even under this black sky, the northern stars still guide us home."',
    greenFlags: ['Charts constellations across the sky', 'Cozy hand-knitted sweaters', 'Gentle, soothing voice'],
    redFlags: ['Stares at the foggy sky for hours during trials'],
    datingVibe: 'Ethereal, dreamy Scandinavian romantic',
    turnOn: 'Auroras, hot cocoa, and stargazing',
    dealbreaker: 'Light pollution and loud noise',
    chapter: 'Northern Mists',
  },
  vee_boonyasak: {
    slug: 'vee_boonyasak',
    name: 'Vee Boonyasak',
    realName: 'Vee Boonyasak',
    role: 'Survivor',
    gender: 'female',
    title: 'The Bangkok Muay Thai Prodigy',
    tagline: 'Muay Thai elbows, street markets, and unstoppable energy.',
    bio: 'Muay Thai fighter and street food aficionado from Bangkok. Fast on her feet and ready to roundhouse kick any killer.',
    quote: '"Stand firm, breathe, and strike with everything you have."',
    greenFlags: ['Can defend you against any mugger or killer', 'Cooks incredible authentic Thai curry', 'Incredible physical fitness'],
    redFlags: ['Sparring sessions with her leave serious bruises'],
    datingVibe: 'Energetic, fiery martial artist with a huge appetite',
    turnOn: 'Spicy street food and sparring practice',
    dealbreaker: 'Lazy couch potatoes who complain about working out',
    chapter: 'Siam Shadows',
  },
  orela_rose: {
    slug: 'orela_rose',
    name: 'Orela Rose',
    realName: 'Orela Rose',
    role: 'Survivor',
    gender: 'female',
    title: 'The Botanical Alchemist',
    tagline: 'Herbal elixirs, glowing greenhouse blooms, and quiet warmth.',
    bio: 'Alchemist and florist who cultivates rare luminous night-blooms inside the Entity’s dark forest.',
    quote: '"Every flower has a secret thorn... but only to protect its beauty."',
    greenFlags: ['Brings you glowing night-blooms', 'Creates herbal remedies that restore health', 'Warm, nurturing presence'],
    redFlags: ['Mixes experimental teas that might cause hallucinations'],
    datingVibe: 'Tender, mysterious alchemist girlfriend',
    turnOn: 'Luminous midnight flora and botanical glass vials',
    dealbreaker: 'Trampling rare garden seedlings',
    chapter: 'The Forgotten Garden',
  },

  // ==========================================
  // MALE SURVIVORS (26)
  // ==========================================
  leon_scott_kennedy: {
    slug: 'leon_scott_kennedy',
    name: 'Leon S. Kennedy',
    realName: 'Leon Scott Kennedy',
    role: 'Survivor',
    gender: 'male',
    title: 'The Rookie Raccoon City Hero',
    tagline: 'Floppy 90s bangs, Flashbang crafts, and golden retriever energy.',
    bio: 'Raccoon City survivor turned top-secret government agent. Will craft flashbangs on generators and drop them at the exact right moment to protect you.',
    quote: '"Where’s everyone going? Bingo?"',
    greenFlags: ['Flashbang saves are legendary', 'Protective golden retriever husband material', 'Floppy hair that never loses volume'],
    redFlags: ['Has a thing for enigmatic women in red dresses who betray him', 'Worst first day at work in human history'],
    datingVibe: 'Handsome, protective action hero with a heart of gold',
    turnOn: 'Laser sights, leather jackets, and tactical teamwork',
    dealbreaker: 'Betraying him for an umbrella virus sample',
    chapter: 'Resident Evil',
  },
  felix_richter: {
    slug: 'felix_richter',
    name: 'Felix Richter',
    realName: 'Felix Richter',
    role: 'Survivor',
    gender: 'male',
    title: 'The Visionary Architect',
    tagline: 'German architecture, three-piece tailored suits, and jawlines that cut glass.',
    bio: 'Brilliant architect from Leipzig with impeccable tailoring and a desire to build a sanctuary even within the Fog.',
    quote: '"Every structure has a keystone. In this realm, we must be each other’s."',
    greenFlags: ['Desperate Measures unhook speed', 'Built for You item recharges', 'Tailored suits in a foggy mud pit'],
    redFlags: ['Obsessed with secret architectural societies', 'Workaholic architect hours'],
    datingVibe: 'Sophisticated, elegant European gentleman',
    turnOn: 'Minimalist Bauhaus architecture and espresso',
    dealbreaker: 'Sloppy blueprints and bad posture',
    chapter: 'Descend Beyond',
  },
  vittorio_toscano: {
    slug: 'vittorio_toscano',
    name: 'Vittorio Toscano',
    realName: 'Vittorio Toscano',
    role: 'Survivor',
    gender: 'male',
    title: 'The Medieval Scholar',
    tagline: 'Glowing arcane tattoos, silver hair, and centuries of ancient wisdom.',
    bio: '14th-century Italian lord and arcane scholar who spent centuries traversing the Fog without losing his mind or his glorious abs.',
    quote: '"Time is an ocean, and knowledge is the vessel that keeps us afloat."',
    greenFlags: ['Potential Energy stores generator progress', 'Aged like the finest medieval wine', 'Glowing arcane tattoos look magnificent'],
    redFlags: ['Has been wandering the Fog for 600 years', 'Speaks in medieval Latin when stressed'],
    datingVibe: 'Wise, poetic, immortal silver-fox scholar',
    turnOn: 'Ancient illuminated manuscripts and arcane ruins',
    dealbreaker: 'Ignorance and wanton destruction of knowledge',
    chapter: 'Forged in Fog',
  },
  david_king: {
    slug: 'david_king',
    name: 'David King',
    realName: 'David King',
    role: 'Survivor',
    gender: 'male',
    title: 'The Manchester Brawler',
    tagline: 'Bare-knuckle boxing, Dead Hard dodges, and shirtless confidence.',
    bio: 'Rugby champion and pub brawler from Manchester. Rugged, fearless, and will take a protection hit for you every single time.',
    quote: '"Come on then, if you think you’re hard enough!"',
    greenFlags: ['Dead Hard dodge master', 'We’re Gonna Live Forever bloodpoint king', 'Shirtless cosmetic option is iconic'],
    redFlags: ['Starts bar brawls on casual Tuesday nights', 'No Mither broken state 24/7'],
    datingVibe: 'Rugged, protective, muscle-bound brawler',
    turnOn: 'Rugby matches, pints of stout, and adrenaline',
    dealbreaker: 'Pretentious wine tastings and snobs',
    chapter: 'A Lullaby for the Dark',
  },
  steve_harrington: {
    slug: 'steve_harrington',
    name: 'Steve Harrington',
    realName: 'Steve Harrington',
    role: 'Survivor',
    gender: 'male',
    title: 'The Babysitter & Scoops Ahoy King',
    tagline: 'Scoops Ahoy sailor suit, Farrah Fawcett hairspray, and nail bat heroics.',
    bio: 'From Hawkins king bee to the world’s best babysitter. Unhooks you with Babysitter and screams at the top of his lungs on the hook.',
    quote: '"Turns out I’m a pretty damn good babysitter."',
    greenFlags: ['Babysitter speed boost and aura hiding', 'Iconic hair with 4 puffs of hairspray', 'Will fight Demogorgons with a spiked bat'],
    redFlags: ['Ahoy uniform smells like melted rocky road', 'High-pitched hook scream'],
    datingVibe: 'Goofy, adorable, self-sacrificing heartthrob',
    turnOn: 'Ice cream sundaes and 80s synth-pop',
    dealbreaker: 'Hurting the kids under his supervision',
    chapter: 'Stranger Things',
  },
  nicolas_cage: {
    slug: 'nicolas_cage',
    name: 'Nicolas Cage',
    realName: 'Nicolas Kim Coppola',
    role: 'Survivor',
    gender: 'male',
    title: 'The Hollywood Legend',
    tagline: 'Dramaturgy rolls, Plot Twist plays, and pure unadulterated cinema.',
    bio: 'Literal Academy Award winner Nicolas Cage pulled into the Fog. Will give 110% acting commitment to every generator repair.',
    quote: '"I’m Nicolas Cage! I’m going to do my own stunts!"',
    greenFlags: ['Custom voice lines during gameplay', 'Plot Twist heals from dying state', 'Can win an Oscar at any moment'],
    redFlags: ['Randomly screams "NOT THE BEES!" in chase', 'May steal the Declaration of Independence on your second date'],
    datingVibe: 'Unpredictable, cinematic, legendary extravaganza',
    turnOn: 'Method acting and vintage comic books',
    dealbreaker: 'Boring scripts and bad directors',
    chapter: 'Nicolas Cage',
  },
  alan_wake: {
    slug: 'alan_wake',
    name: 'Alan Wake',
    realName: 'Alan Wake',
    role: 'Survivor',
    gender: 'male',
    title: 'The Dark Place Author',
    tagline: 'Champion of Light flashlight beams, typewriter reels, and dark noir poetry.',
    bio: 'Bestselling crime author trapped in the Dark Place. Can turn a flashlight beam into a weapon of blinding justice.',
    quote: '"It’s not a loop, it’s a spiral."',
    greenFlags: ['Champion of Light slows killers', 'Writes bestselling fiction about you', 'Cozy tweed jackets and thermos coffee'],
    redFlags: ['Trapped in an infinite psychological nightmare spiral', 'Throws flashlights at shadows in the living room'],
    datingVibe: 'Brooding, literary, tortured noir genius',
    turnOn: 'Fresh ink ribbons and 100-watt flashlight bulbs',
    dealbreaker: 'Writer’s block and Scratch-like doppelgangers',
    chapter: 'Alan Wake',
  },
  dwight_fairfield: {
    slug: 'dwight_fairfield',
    name: 'Dwight Fairfield',
    realName: 'Dwight Fairfield',
    role: 'Survivor',
    gender: 'male',
    title: 'The Anxious Leader',
    tagline: 'Locker hideouts, Prove Thyself co-op speed, and nerd-cute leadership.',
    bio: 'Former pizza delivery guy with glasses and anxiety. Give him a team and he becomes the ultimate generator-boosting commander.',
    quote: '"Together, we can actually make it out of here!"',
    greenFlags: ['Prove Thyself finishes gens at warp speed', 'Leader aura buff', 'Wholesome nerd charm'],
    redFlags: ['Hides in lockers when doorbells ring', 'Sweats through dress shirts'],
    datingVibe: 'Adorkable, loyal, nervous team leader',
    turnOn: 'Freshly delivered pizza and 4-man gen rushing',
    dealbreaker: 'Being abandoned alone in the trial',
    chapter: 'Base Game',
  },
  jake_park: {
    slug: 'jake_park',
    name: 'Jake Park',
    realName: 'Jake Park',
    role: 'Survivor',
    gender: 'male',
    title: 'The Solitary Survivalist',
    tagline: 'Hook sabotages, wilderness survival, and quiet outdoor ruggedness.',
    bio: 'Rebellious son of a wealthy CEO who abandoned society to live off the land. Sabotages meat hooks right in front of the killer.',
    quote: '"The wild taught me everything I need. Silence is my shield."',
    greenFlags: ['Saboteur hook breaks save teammates', 'Iron Will silence in pain', 'Can build a log cabin with bare hands'],
    redFlags: ['Prefers trees to human conversation', 'Refuses to shower indoors'],
    datingVibe: 'Rugged, quiet mountain-man loner',
    turnOn: 'Toolboxes and quiet pine forests',
    dealbreaker: 'Corporate wealth and high-society galas',
    chapter: 'Base Game',
  },
  ace_visconti: {
    slug: 'ace_visconti',
    name: 'Ace Visconti',
    realName: 'Ace Visconti',
    role: 'Survivor',
    gender: 'male',
    title: 'The High-Rolling Gambler',
    tagline: 'Finger guns, lucky chest plunder, and silver-tongued charm.',
    bio: 'Argentinian gambler who smiles in the face of debt, death, and doom. Believes luck is just a smile away.',
    quote: '"Lady Luck never leaves my side, kiddo. Finger guns!"',
    greenFlags: ['Ace in the Hole finds pink addons in chests', 'Charismatic smile that melts tension', 'Finger gun animations'],
    redFlags: ['Owes money to every mob boss in Buenos Aires', 'Will bet your house on a 4% unhook attempt'],
    datingVibe: 'Smooth-talking, charming rogue gambler',
    turnOn: 'Royal flushes and silk Hawaiian shirts',
    dealbreaker: 'Playing it safe and boring routines',
    chapter: 'Of Flesh and Mud',
  },
  ash_williams: {
    slug: 'ash_williams',
    name: 'Ash Williams',
    realName: 'Ashley J. Williams',
    role: 'Survivor',
    gender: 'male',
    title: 'The Deadite Slayer',
    tagline: 'Chainsaw hand, boomstick quotes, and pure Groovy energy.',
    bio: 'Retail clerk who accidentally summoned the Necronomicon and spent his life slaying Deadites with a chainsaw and a shotgun.',
    quote: '"Look who’s shitting in the tall grass. Groovy."',
    greenFlags: ['Mettle of Man extra health state', 'Peak one-liner comedy', 'Has literal chainsaw attachments'],
    redFlags: ['Read Latin from a cursed skin-bound book twice', 'Will lose his prosthetic hand at dinner'],
    datingVibe: 'Over-the-top, hilarious 80s B-movie legend',
    turnOn: 'Double-barrel boomsticks and classic hotrods',
    dealbreaker: 'Reading ancient occult books out loud',
    chapter: 'Ash vs Evil Dead',
  },
  bill_overbeck: {
    slug: 'bill_overbeck',
    name: 'Bill Overbeck',
    realName: 'William "Bill" Overbeck',
    role: 'Survivor',
    gender: 'male',
    title: 'The Vietnam Veteran',
    tagline: 'Cigarettes, green beret, Borrowed Time, and Unbreakable spirit.',
    bio: 'Vietnam vet and Left 4 Dead legend. Unbreakable will to stand back up after being slugged and ensure everyone else escapes first.',
    quote: '"I’ll be damned if I let any of you die on my watch."',
    greenFlags: ['Unbreakable self-pickup from dying state', 'Borrowed Time saves matches', 'Ultimate heroic grandpa/father figure'],
    redFlags: ['Chain-smokes cigarettes in enclosed spaces', 'Refuses to see a doctor for coughs'],
    datingVibe: 'Grizzled, heroic veteran protector',
    turnOn: 'Tactical discipline and green berets',
    dealbreaker: 'Leaving a teammate behind',
    chapter: 'Left 4 Dead',
  },
  adam_francis: {
    slug: 'adam_francis',
    name: 'Adam Francis',
    realName: 'Adam Francis',
    role: 'Survivor',
    gender: 'male',
    title: 'The Resourceful Teacher',
    tagline: 'Pebble throws (Diversion), Deliverance 100% unhook, and sharp intellect.',
    bio: 'Kingston-born teacher in Tokyo who relies on intellect and composure. Throws pebbles to distract killers and unhooks himself with Deliverance.',
    quote: '"Preparation is the foundation of survival."',
    greenFlags: ['Deliverance instant unhooks', 'Calculated, calm under fire', 'Pebble throw distraction plays'],
    redFlags: ['Takes life too seriously', 'Will grade your essays on dates'],
    datingVibe: 'Intelligent, refined, reliable gentleman teacher',
    turnOn: 'Sharp minds, books, and pebble throws',
    dealbreaker: 'Lack of discipline and reckless chaos',
    chapter: 'Shattered Bloodline',
  },
  jeff_johansen: {
    slug: 'jeff_johansen',
    name: 'Jeff Johansen',
    realName: 'Jeff Johansen',
    role: 'Survivor',
    gender: 'male',
    title: 'The Heavy Metal Artist',
    tagline: 'Beards, oil painting, black metal vinyl, and gentle giant heart.',
    bio: 'Heavy metal artist from Ormond with a gentle soul. Loves dogs, paints breathtaking murals, and breaks killer auras with Distortion.',
    quote: '"Art is how we scream into the void."',
    greenFlags: ['Distortion hides your aura from killers', 'Loves rescue dogs (paints them too)', 'Cozy flannel shirts and bear hugs'],
    redFlags: ['His loud breathing can be heard from 32 meters away'],
    datingVibe: 'Gentle giant metalhead artist with teddy-bear warmth',
    turnOn: 'Black metal vinyl records and large canvas oil paints',
    dealbreaker: 'Animal cruelty and shallow pop music',
    chapter: 'Darkness Among Us',
  },
  jonah_vasquez: {
    slug: 'jonah_vasquez',
    name: 'Jonah Vasquez',
    realName: 'Jonah Vasquez',
    role: 'Survivor',
    gender: 'male',
    title: 'The CIA Cryptographer',
    tagline: 'Mathematical formulas, Boon: Exponential, and analytical brilliance.',
    bio: 'CIA codebreaker who stumbled upon mathematical coordinates left by the Entity. Calculates optimal looping routes in milliseconds.',
    quote: '"Every pattern reveals a vulnerability."',
    greenFlags: ['Boon: Exponential unslugs teammates', 'Genius mathematical intelligence', 'Sharp analytical problem solver'],
    redFlags: ['Over-analyzes every text message down to character counts'],
    datingVibe: 'Analytical, sharp cryptographer with high IQ',
    turnOn: 'Prime number ciphers and encrypted messaging',
    dealbreaker: 'Disorganized thinking and emotional volatility',
    chapter: 'Portrait of a Murder',
  },
  quentin_smith: {
    slug: 'quentin_smith',
    name: 'Quentin Smith',
    realName: 'Quentin Smith',
    role: 'Survivor',
    gender: 'male',
    title: 'The Insomniac Dream Fighter',
    tagline: 'Energy drinks, sleep deprivation, Pharmacy chests, and sheer grit.',
    bio: 'Springwood teen who fights Freddy Krueger by refusing to fall asleep. Will loot green med-kits out of chests with Pharmacy.',
    quote: '"I’m not tired. I’ll sleep when we get out of here."',
    greenFlags: ['Pharmacy finds guaranteed green med-kits', 'Vigil accelerates status recovery', 'Will stay awake all night to talk to you'],
    redFlags: ['Dark eye bags from 4 weeks without REM sleep', 'Drinks 12 cans of Monster Energy per day'],
    datingVibe: 'Sleep-deprived, protective teenage fighter',
    turnOn: 'Pill bottles, energy drinks, and daylight',
    dealbreaker: 'Telling him to take a nap',
    chapter: 'A Nightmare on Elm Street',
  },
  david_tapp: {
    slug: 'david_tapp',
    name: 'Detective Tapp',
    realName: 'David Tapp',
    role: 'Survivor',
    gender: 'male',
    title: 'The Obsessive Detective',
    tagline: 'Tenacity crawling, Stake Out great skill checks, and trench coats.',
    bio: 'Relentless police detective who tracked Jigsaw to the bitter end. Crawls at hyperspeed while recovering with Tenacity.',
    quote: '"I’ve got the pieces of the puzzle right here."',
    greenFlags: ['Stake Out converts good skill checks to Greats', 'Tenacity crawl speed is unmatched', 'Unstoppable sense of duty'],
    redFlags: ['Obsessed with cold case murder files', 'Trench coat has knife scars on the throat'],
    datingVibe: 'Grizzled, determined crime-fighting detective',
    turnOn: 'Fingerprint dust and forensic audio recordings',
    dealbreaker: 'Corrupt officials and obstruction of justice',
    chapter: 'SAW',
  },
  rick_grimes: {
    slug: 'rick_grimes',
    name: 'Rick Grimes',
    realName: 'Rick Grimes',
    role: 'Survivor',
    gender: 'male',
    title: 'The Alexandria Sheriff',
    tagline: 'Colt Python revolver, sheriff hat, and leader of the survivors.',
    bio: 'Sheriff who led humanity through the walker apocalypse. Rugged, authoritative, and will fight tooth and nail for family.',
    quote: '"We are the ones who live."',
    greenFlags: ['Natural charismatic leader', 'Will tear a throat out with his teeth to protect you', 'Rugged sheriff charm'],
    redFlags: ['Head tilt when lecturing you', 'Has seen too many good people fall'],
    datingVibe: 'Grizzled, protective sheriff and family protector',
    turnOn: 'Sheriff badges and clean revolver cylinders',
    dealbreaker: 'Endangering the group',
    chapter: 'The Walking Dead',
  },
  dustin_henderson: {
    slug: 'dustin_henderson',
    name: 'Dustin Henderson',
    realName: 'Dustin Henderson',
    role: 'Survivor',
    gender: 'male',
    title: 'The Cerebro Technician',
    tagline: 'Radio towers, D&D strategy, and never-ending optimism.',
    bio: 'The smartest kid in Hawkins. Built Cerebro, talks to girlfriends over ham radio, and solves monster puzzles with D&D lore.',
    quote: '"Neverending Stoooryyyy! Ah-ah-ah!"',
    greenFlags: ['Can fix any radio, generator, or computer', 'Sings Neverending Story in harmony', 'Hilarious and fiercely loyal'],
    redFlags: ['Adopted a baby Demogorgon in his room (Dart)'],
    datingVibe: 'Nerdy, brilliant, hilarious young strategist',
    turnOn: 'Ham radio frequencies and D&D campaigns',
    dealbreaker: 'Making fun of his curly hair or teeth',
    chapter: 'Stranger Things',
  },
  kwon_tae_young: {
    slug: 'kwon_tae_young',
    name: 'Tae-Young',
    realName: 'Kwon Tae-Young',
    role: 'Survivor',
    gender: 'male',
    title: 'The Seoul Tech Specialist',
    tagline: 'Cybersecurity, drone bypassing, and sleek urban aesthetics.',
    bio: 'Seoul cybersecurity expert who reverse-engineers high-tech corporate infrastructure and tracks killer aura signals.',
    quote: '"Every firewall has an exploit. You just have to find the pulse."',
    greenFlags: ['Hacks any security lock in seconds', 'Sleek modern Korean streetwear style', 'Calm and collected in emergencies'],
    redFlags: ['Watches packet traces during dinner dates'],
    datingVibe: 'Cool, tech-savvy urban hacker with sleek visuals',
    turnOn: 'Zero-day exploits and mechanical keyboards',
    dealbreaker: 'Weak passwords and cyber-carelessness',
    chapter: 'All-Kill Legacy',
  },
  shane_wiigwaas: {
    slug: 'shane_wiigwaas',
    name: 'Shane',
    realName: 'Shane Wiigwaas',
    role: 'Survivor',
    gender: 'male',
    title: 'The Great Lakes Tracker',
    tagline: 'Forest navigation, birchbark canoe craft, and silent footsteps.',
    bio: 'Indigenous tracker from the Great Lakes. Can read broken twigs and forest moss to lead entire groups out of danger.',
    quote: '"The earth speaks to those who listen without pride."',
    greenFlags: ['Never gets lost in any forest or trial map', 'Quiet, deeply grounded emotional maturity', 'Can start a fire in pouring rain'],
    redFlags: ['Prefers silent contemplation over texting back'],
    datingVibe: 'Grounded, peaceful, rugged wilderness guide',
    turnOn: 'Starlit lakes and handcrafted birch crafts',
    dealbreaker: 'Disrespecting the natural world',
    chapter: 'Northern Mists',
  },
  renato_lyra: {
    slug: 'renato_lyra',
    name: 'Renato Lyra',
    realName: 'Renato Lyra',
    role: 'Survivor',
    gender: 'male',
    title: 'The Rio Strategist',
    tagline: 'Background Player sprint bursts, kite tactics, and chill Brazilian charm.',
    bio: 'Kite fighter from Rio de Janeiro who plans 5 steps ahead. Background Player gives him hypersonic sprint speed when teammates are carried.',
    quote: '"Take your time, read the wind, and make your move."',
    greenFlags: ['Background Player flashlight saves are glorious', 'Chill, patient, and sweet demeanor', 'Great with family and friends'],
    redFlags: ['Overthinks simple restaurant orders'],
    datingVibe: 'Sweet, athletic, strategic Brazilian heartthrob',
    turnOn: 'Strategic games and ocean sunsets',
    dealbreaker: 'Impatience and unnecessary shouting',
    chapter: 'Tools of Torment',
  },
  trevor_belmont: {
    slug: 'trevor_belmont',
    name: 'Trevor Belmont',
    realName: 'Trevor Belmont',
    role: 'Survivor',
    gender: 'male',
    title: 'The Vampire Hunter',
    tagline: 'Vampire Killer whip, leather armor, and centuries of monster slaying.',
    bio: 'The last son of House Belmont. Wields legendary consecrated whips, drinks ale, and punches Dracula in the jaw for breakfast.',
    quote: '"I’m Trevor Belmont, of the House of Belmont, and I’ve never lost a fight to a monster."',
    greenFlags: ['Can whip any killer into submission', 'Immense strength, resilience, and battle IQ', 'Rugged medieval hero appeal'],
    redFlags: ['Drinks too much ale in medieval taverns', 'Brawls first, asks questions later'],
    datingVibe: 'Rough-around-the-edges monster slayer with a noble heart',
    turnOn: 'Consecrated whips, cold ale, and righteous battles',
    dealbreaker: 'Vampire sympathizers',
    chapter: 'Castlevania',
  },
  yoichi_asakawa: {
    slug: 'yoichi_asakawa',
    name: 'Yoichi Asakawa',
    realName: 'Yoichi Asakawa',
    role: 'Survivor',
    gender: 'male',
    title: 'The Marine Biologist',
    tagline: 'Yellow raincoat, ocean research, Boon: Dark Theory, and Sadako survivor.',
    bio: 'The boy who survived Sadako’s cursed tape, now a renowned oceanographer. Yellow raincoat and Boon: Dark Theory movement speed.',
    quote: '"The ocean keeps its secrets, but so do I."',
    greenFlags: ['Boon: Dark Theory speed boost', 'Distinguished oceanographer and researcher', 'Iconic yellow sailor jacket'],
    redFlags: ['Cursed since childhood by a vengeful well ghost'],
    datingVibe: 'Intellectual, gentle ocean scientist with mysterious past',
    turnOn: 'Deep sea diving and ancient nautical maps',
    dealbreaker: 'Videotapes left on the floor',
    chapter: 'Sadako Rising',
  },
  gabriel_soma: {
    slug: 'gabriel_soma',
    name: 'Gabriel Soma',
    realName: 'Gabriel Soma',
    role: 'Survivor',
    gender: 'male',
    title: 'The Deep Space Clone',
    tagline: 'Made For This endurance, sci-fi engineering, and resilient humanity.',
    bio: 'Engineered deep-space colonist who defied AI subjugation on planet Dvarka. Made For This endurance status keeps him standing tall.',
    quote: '"I was made to survive. And I will."',
    greenFlags: ['Made For This extra endurance state', 'Top-tier sci-fi tech troubleshooting', 'Unbreakable will to live'],
    redFlags: ['Existential dread about being a clone', 'Wants to sleep in cryo-pods'],
    datingVibe: 'Futuristic, resilient space engineer',
    turnOn: 'Cryo-tech engines and starry nebulas',
    dealbreaker: 'Rogue AI systems',
    chapter: 'End Transmission',
  },
  the_troupe: {
    slug: 'the_troupe',
    name: 'The Troupe',
    realName: 'Baermar & Aestri Yazar',
    role: 'Survivor',
    gender: 'monster_other',
    title: 'The D&D Bards',
    tagline: 'Bardic Inspiration dice rolls, lute solos, and illusion magic.',
    bio: 'Elven and human bards from Dungeons & Dragons who cast Mirrored Illusion and roll 20-sided dice with Bardic Inspiration.',
    quote: '"A song for the fallen, a tune for the free!"',
    greenFlags: ['Plays lute solos during generator repair', 'Bardic Inspiration buffs all skill checks', 'Mirrored Illusion decoys fool killers'],
    redFlags: ['Might roll a Nat 1 on your wedding proposal', 'Constantly rhyming in conversation'],
    datingVibe: 'Musical, magical, whimsical fantasy bards',
    turnOn: 'Lute solos, D20 dice, and tavern songs',
    dealbreaker: 'Tone-deaf critics who hate fantasy roleplay',
    chapter: 'Dungeons & Dragons',
  },

  // ==========================================
  // FEMALE KILLERS (12)
  // ==========================================
  the_huntress: {
    slug: 'the_huntress',
    name: 'The Huntress',
    realName: 'Anna',
    role: 'Killer',
    gender: 'female',
    title: 'The Red Forest Mother',
    tagline: '7-foot tall muscle mommy with hatchets and a haunting lullaby.',
    bio: 'Raised alone in the harsh Russian wilderness. Towering, incredibly strong, and hums "Bayu Bayushki Bayu" while cross-map sniping survivors.',
    quote: '"(Gentle, haunting lullaby echoing through the pine trees)"',
    greenFlags: ['Can build a log fortress with her bare hands', 'Cross-map hatchet accuracy', 'Will fiercely protect anyone she considers family'],
    redFlags: ['Will lock you in a wooden forest cottage forever', 'Hatchets fly when she gets mildly annoyed'],
    datingVibe: 'Imposing muscle-mommy forest guardian',
    turnOn: 'Handcrafted wooden toys and pine forests',
    dealbreaker: 'Weak grip and running away from her lullaby',
    height: 'Tall',
    chapter: 'A Lullaby for the Dark',
  },
  the_spirit: {
    slug: 'the_spirit',
    name: 'The Spirit',
    realName: 'Rin Yamaoka',
    role: 'Killer',
    gender: 'female',
    title: 'The Vengeful Onryō',
    tagline: 'Katana strikes, phase-walking mist, and shattered glass aesthetic.',
    bio: 'Tragic heiress to the Yamaoka bloodline. Moves at supernatural speed through phase-walking with her ancestor’s shattered katana.',
    quote: '"(Furious spirit cries as mist shatters into glass)"',
    greenFlags: ['Phase-walk speed is unmatched', 'Ancestral katana blade mastery', 'Stunning glass-shard glow aesthetic'],
    redFlags: ['Phase-walks behind you whenever you say "we need to talk"', 'Severe ancestral rage issues'],
    datingVibe: 'Ethereal, dangerous, tragic supernatural fury',
    turnOn: 'Traditional Japanese shrines and clean sword cuts',
    dealbreaker: 'Disloyalty and betrayal',
    height: 'Average',
    chapter: 'Shattered Bloodline',
  },
  the_skull_merchant: {
    slug: 'the_skull_merchant',
    name: 'The Skull Merchant',
    realName: 'Adriana Imai',
    role: 'Killer',
    gender: 'female',
    title: 'The High-Tech Executive',
    tagline: 'Radar drones, claw gauntlets, and high-fashion catwalk killer.',
    bio: 'Billionaire tech CEO and manga fanatic who hunts corporate rivals with custom aerial skull-drones and a twin-blade gauntlet.',
    quote: '"Every market has competitors. I just liquidate mine permanently."',
    greenFlags: ['Billionaire bank account', 'High-tech drone surveillance protects your home', 'Impeccable high-fashion designer catwalk'],
    redFlags: ['3-gen drone camping matches lasted 45 minutes', 'Tracks your phone with aerial thermal drones'],
    datingVibe: 'Deadly corporate heiress with manga obsession',
    turnOn: 'Surveillance data and hostile corporate takeovers',
    dealbreaker: 'Poor financial acumen and drone hacking',
    height: 'Average',
    chapter: 'Tools of Torment',
  },
  the_pig: {
    slug: 'the_pig',
    name: 'The Pig',
    realName: 'Amanda Young',
    role: 'Killer',
    gender: 'female',
    title: 'The Jigsaw Apprentice',
    tagline: 'Boop the snoot, Reverse Bear Traps, and stealth ambush roar.',
    bio: 'Jigsaw’s conflicted apprentice. Masters stealth crouching and puts ticking Reverse Bear Traps on heads. Community demands you boop her snoot.',
    quote: '"Game Over. Unless you give me a snoot boop."',
    greenFlags: ['Allows snoot boops if you are polite', 'Reverse Bear Trap keeps party guests punctual', 'Hidden blade ambush speed'],
    redFlags: ['Rules of her games are sometimes rigged', 'Gets nerfed in every single patch note'],
    datingVibe: 'Stealthy, conflicted puzzle-mistress',
    turnOn: 'Snoot boops and intricate mechanical timers',
    dealbreaker: 'Refusing to boop the snoot or breaking test rules',
    height: 'Short',
    chapter: 'SAW',
  },
  the_plague: {
    slug: 'the_plague',
    name: 'The Plague',
    realName: 'Adiris',
    role: 'Killer',
    gender: 'female',
    title: 'The High Priestess of Babylon',
    tagline: 'Golden censer, Corrupt Purge, and 7-foot tall ancient beauty.',
    bio: 'High priestess of Babylon who sacrificed herself for her dying followers. Beautiful, tragic, tall, and wields the purifying Vile Purge.',
    quote: '"(Mesopotamian prayer chants echoing over golden censers)"',
    greenFlags: ['7-foot tall ancient Mesopotamian royalty', 'Deep spiritual devotion', 'Golden jewel-encrusted censer'],
    redFlags: ['Corrupt Purge vomit attacks on first dates', 'Broken status effect means no healing allowed'],
    datingVibe: 'Towering ancient goddess with tragic devotion',
    turnOn: 'Faithful worship and clean golden censers',
    dealbreaker: 'Drinking from the cleansing pool without permission',
    height: 'Tall',
    chapter: 'Demise of the Faithful',
  },
  the_artist: {
    slug: 'the_artist',
    name: 'The Artist',
    realName: 'Carmina Mora',
    role: 'Killer',
    gender: 'female',
    title: 'The Ink-Drenched Surrealist',
    tagline: 'Dire Crows, black ink hands, and avant-garde Chilean art.',
    bio: 'Chilean surrealist painter whose voice was stolen by corrupt politicians. Manipulates murderous ink crows with graceful avian elegance.',
    quote: '"(Heartbreaking crow cry and brush stroke of black ink)"',
    greenFlags: ['Brilliant avant-garde artist', 'Dire crows provide cross-map intel', 'Elegantly tall with graceful bird-like movements'],
    redFlags: ['Ink stains on all the white bedsheets', 'Flocks of crows spy on your phone'],
    datingVibe: 'Poetic, gothic, ink-stained surrealist artist',
    turnOn: 'Black ink sketches and expressive poetry',
    dealbreaker: 'Artistic censorship and corrupt politics',
    height: 'Tall',
    chapter: 'Portrait of a Murder',
  },
  the_nurse: {
    slug: 'the_nurse',
    name: 'The Nurse',
    realName: 'Sally Smithson',
    role: 'Killer',
    gender: 'female',
    title: 'The Blink Mistress',
    tagline: 'Spencer’s Last Breath blinks, bonesaw elegance, and S-tier lethality.',
    bio: 'Former asylum nurse who snapped under grueling conditions. Blinks through walls and pallets with terrifying grace and speed.',
    quote: '"(Ghostly wheeze as she blinks through solid matter)"',
    greenFlags: ['Undisputed #1 strongest killer in DBD history', 'Can blink through traffic jams and walls', 'Always wears clean linen'],
    redFlags: ['Fatigue stun wheezes after every blink', 'Might mistake you for an unruly asylum patient'],
    datingVibe: 'Ethereal, deadly, floating Victorian phantom',
    turnOn: 'Flawless triple blinks and clean surgical cuts',
    dealbreaker: 'Disrespecting the medical profession',
    height: 'Average',
    chapter: 'The Last Breath',
  },
  the_onryō: {
    slug: 'the_onryō',
    name: 'The Onryō (Sadako)',
    realName: 'Sadako Yamamura',
    role: 'Killer',
    gender: 'female',
    title: 'The Well Spectre',
    tagline: 'TV projections, cursed videotapes, and spooky condemned moris.',
    bio: 'The iconic psychic spectre from Ringu. Teleports through television screens and condemns those who fail to return her videotape within 7 days.',
    quote: '"(Ominous television static and well water dripping)"',
    greenFlags: ['Instant TV teleportation to your living room', 'Classic horror royalty', 'Looks great in vintage white robes'],
    redFlags: ['Sends cursed VHS tapes if you don’t reply in 7 days', 'Leaves wet muddy footprints everywhere'],
    datingVibe: 'Creepy-cute psychic ghost girl',
    turnOn: 'VHS tapes and dark television screens',
    dealbreaker: 'Not rewinding the videotape before returning it',
    height: 'Short',
    chapter: 'Sadako Rising',
  },
  the_hag: {
    slug: 'the_hag',
    name: 'The Hag',
    realName: 'Lisa Sherwood',
    role: 'Killer',
    gender: 'female',
    title: 'The Swamp Witch',
    tagline: 'Phantasm mud traps, mud teleportation, and wetland sorcery.',
    bio: 'Abducted and tortured by cannibals in a backwater swamp, drew ancient symbols on the mud to exact bloody vengeance.',
    quote: '"(Terrifying mud trap pop and screeching claw swipe)"',
    greenFlags: ['Can teleport to any mud trap across the yard', 'Masters ancient tribal protective symbols', 'Never lets anyone push her around'],
    redFlags: ['Draws mud runes on the kitchen floor', 'Likes eating raw livers'],
    datingVibe: 'Fierce, vengeful swamp sorceress',
    turnOn: 'Fresh mud drawings and backwater swamps',
    dealbreaker: 'Wiping away her mud traps with a flashlight',
    height: 'Short',
    chapter: 'Of Flesh and Mud',
  },
  the_houndmaster: {
    slug: 'the_houndmaster',
    name: 'The Houndmaster',
    realName: 'Portia Maye',
    role: 'Killer',
    gender: 'female',
    title: 'The Canine Commander',
    tagline: 'War hounds, hunting whistles, and seaside tracking.',
    bio: 'Pirate and hound trainer who commands a loyal war dog to sniff out, chase, and pin down targets with military precision.',
    quote: '"Hunt them down, boy! Leave nothing behind!"',
    greenFlags: ['Comes with a very good loyal boy (war hound)', 'Incredible navigation and pirate flair', 'High discipline and loyalty'],
    redFlags: ['Dog sheds everywhere and bites visitors'],
    datingVibe: 'Commanding, fierce pirate trainer with loyal hound',
    turnOn: 'Sea breezes, ship decks, and well-trained hounds',
    dealbreaker: 'Being bad with dogs',
    height: 'Tall',
    chapter: 'Doomed Course',
  },
  the_krasue: {
    slug: 'the_krasue',
    name: 'The Krasue',
    realName: 'The Krasue',
    role: 'Killer',
    gender: 'female',
    title: 'The Floating Viscera Spirit',
    tagline: 'Floating head, glowing entrails, Southeast Asian folklore terror.',
    bio: 'A nocturnal female spirit from Southeast Asian folklore whose glowing head and floating viscera detach at night to hunt.',
    quote: '"(Glowing eerie floating presence across dark villages)"',
    greenFlags: ['Zero body weight (she floats!)', 'Authentic legendary folklore pedigree', 'Bioluminescent glow at night'],
    redFlags: ['Only her head and entrails show up to dates'],
    datingVibe: 'Supernatural folklore horror phantom',
    turnOn: 'Bioluminescence and tropical nights',
    dealbreaker: 'Spiky fences and thorny bushes',
    height: 'Tall',
    chapter: 'Siam Shadows',
  },
  the_twins: {
    slug: 'the_twins',
    name: 'The Twins',
    realName: 'Charlotte & Victor Deshayes',
    role: 'Killer',
    gender: 'female',
    title: 'The Bound Siblings',
    tagline: 'Sickles, pouncing Victor, and 17th-century French bond.',
    bio: 'Conjoined twins from 17th-century France who survived persecution through fierce fraternal loyalty. Victor pounces from Charlotte’s chest.',
    quote: '"We only have each other... and we will survive."',
    greenFlags: ['Fiercest sibling loyalty in history', 'Victor pounces on annoying people for you', 'Charlotte has immense protective maternal instinct'],
    redFlags: ['Victor kicks you while you sleep', 'Slugged the entire team for 4 minutes'],
    datingVibe: 'Fiercely protective French sibling duo',
    turnOn: 'Quiet French countryside and loyalty',
    dealbreaker: 'Kicking Victor',
    height: 'Tall',
    chapter: 'A Binding of Kin',
  },

  // ==========================================
  // MALE KILLERS (26)
  // ==========================================
  the_trickster: {
    slug: 'the_trickster',
    name: 'The Trickster',
    realName: 'Ji-Woon Hak',
    role: 'Killer',
    gender: 'male',
    title: 'The K-Pop Heartthrob',
    tagline: 'Neon hair, throwing knives, Main Event giggles, and K-pop visuals.',
    bio: 'K-pop idol singer who turned the screams of his victims into chart-topping synth tracks. Wears open neon coats and throws knives to musical beats.',
    quote: '"Did you like the show? The encore is just for you!"',
    greenFlags: ['Flawless idol visuals and vocal range', 'Main Event throwing knife barrage is spectacular', 'Speaks Korean with smooth charm'],
    redFlags: ['Mixes your screams into his Spotify tracks', 'Narcissism level is over 9000'],
    datingVibe: 'Flashy, flamboyant, psychopathic K-pop star',
    turnOn: 'Encores, neon spotlights, and high-pitched screams',
    dealbreaker: 'Bad musical taste and interrupting his solo',
    height: 'Average',
    chapter: 'All-Kill',
  },
  the_ghost_face: {
    slug: 'the_ghost_face',
    name: 'The Ghost Face',
    realName: 'Danny Johnson / Jed Olsen',
    role: 'Killer',
    gender: 'male',
    title: 'The Stalker & Selfie King',
    tagline: 'Crouch teabagging, night shroud stalking, and post-mori selfies.',
    bio: 'Narcissistic crime journalist who writes the front-page articles about his own murders. Loves taking selfies with you on the ground.',
    quote: '"What’s your favorite scary movie? Let’s take a selfie first."',
    greenFlags: ['Takes commemorative selfies with you', 'Masters the friendly crouch-teabag communication', 'Writes front-page news articles'],
    redFlags: ['Stalks you from behind the kitchen curtain for 12 seconds to Mark you', 'Never takes off the mask'],
    datingVibe: 'Cheeky, meta-horror, selfie-obsessed stalker',
    turnOn: '99% stalk meters and instant camera flashes',
    dealbreaker: 'Revealing him out of Night Shroud before he takes a selfie',
    height: 'Average',
    chapter: 'Ghost Face',
  },
  the_executioner: {
    slug: 'the_executioner',
    name: 'Pyramid Head',
    realName: 'Pyramid Head',
    role: 'Killer',
    gender: 'male',
    title: 'The Great Knife Tormentor',
    tagline: 'Great Knife drags, Rites of Judgment trails, and sheer menacing bulk.',
    bio: 'The physical manifestation of guilt from Silent Hill. Towering, shirtless, carrying a massive Great Knife that carves trenches into the earth.',
    quote: '"(Heavy grinding of steel against asphalt...)"',
    greenFlags: ['Carves torment trails straight to your heart', 'Abs that look like chiseled granite', 'Never complains or talks back (silent type)'],
    redFlags: ['Cages of Atonement instead of polite breakups', 'His Great Knife scratches wooden floors'],
    datingVibe: 'Towering, silent, muscular force of judgment',
    turnOn: 'Deep remorse and steel grinding sounds',
    dealbreaker: 'Refusing to step into the Torment trail',
    height: 'Tall',
    chapter: 'Silent Hill',
  },
  the_mastermind: {
    slug: 'the_mastermind',
    name: 'Albert Wesker',
    realName: 'Albert Wesker',
    role: 'Killer',
    gender: 'male',
    title: 'The Uroboros Mastermind',
    tagline: 'Trench coats, Virulent Bounds, and 7 minutes to spare for you.',
    bio: 'Former S.T.A.R.S. captain and bio-terrorist mastermind. Enhanced by Uroboros, dashes across the map at supersonic speed in a sleek trench coat.',
    quote: '"Seven minutes. Seven minutes is all I can spare to play with you."',
    greenFlags: ['Always punctual (exactly 7 minutes)', 'Virulent Bound throws provide flight experience', 'Sunglasses at night look undeniably cool'],
    redFlags: ['Global complete saturation monologue during dinner', 'Will inject you with Uroboros worms as a gift'],
    datingVibe: 'Arrogant, god-complex, hyper-competent mastermind',
    turnOn: 'Superior genetics and complete global saturation',
    dealbreaker: 'Wasting more than 7 minutes of his time',
    height: 'Tall',
    chapter: 'Resident Evil: PROJECT W',
  },
  the_shape: {
    slug: 'the_shape',
    name: 'The Shape (Michael Myers)',
    realName: 'Michael Myers',
    role: 'Killer',
    gender: 'male',
    title: 'The Boogeyman of Haddonfield',
    tagline: 'Tier III stalk, tombstone moris, and 0m terror radius breathing.',
    bio: 'Pure evil embodied. Silent, unfeeling, stands at the end of the street staring directly into your soul until the Halloween theme starts playing.',
    quote: '"(Heavy, rhythmic breathing behind a white mask...)"',
    greenFlags: ['Tier III music hits like nothing else', 'Silent listener who never interrupts', 'Classic horror perfection'],
    redFlags: ['Stands outside your bedroom window for 45 minutes without moving', 'Judith’s Tombstone means instant Mori'],
    datingVibe: 'Intense, silent, stalking horror legend',
    turnOn: 'Scratched mirrors and Halloween night',
    dealbreaker: 'Talking too much during silent staring sessions',
    height: 'Tall',
    chapter: 'Halloween',
  },
  the_dark_lord: {
    slug: 'the_dark_lord',
    name: 'Dracula',
    realName: 'Dracula / Mathias Cronqvist',
    role: 'Killer',
    gender: 'male',
    title: 'The Castlevania Dark Lord',
    tagline: 'Vampiric shifts, bat swarms, hellfire pillars, and gothic nobility.',
    bio: 'The immortal Lord of Vampires from Castlevania. Shifts between human nobleman, stealth bat, and fierce wolf while raining hellfire upon mortal souls.',
    quote: '"What is a man? A miserable little pile of secrets! But enough talk... have at you!"',
    greenFlags: ['Can transform into a cute bat or wolf', 'Owns a massive gothic castle in Transylvania', 'Impeccable wine collection and aristocratic manners'],
    redFlags: ['Hates Belmonts with a burning passion', 'Allergic to garlic and sunlight'],
    datingVibe: 'Noble, immortal, aristocratic vampire lord',
    turnOn: 'Blood-red wine goblets and organ sonatas',
    dealbreaker: 'Carrying a whip or holy water',
    height: 'Tall',
    chapter: 'Castlevania',
  },
  the_legion: {
    slug: 'the_legion',
    name: 'The Legion',
    realName: 'Frank, Julie, Susie & Joey',
    role: 'Killer',
    gender: 'male',
    title: 'The Teenage Gang',
    tagline: 'Feral Frenzy vaulting, mixtapes, and angsty teen energy.',
    bio: 'A gang of four rebellious teenagers from Ormond. Sprinting across pallets with Feral Frenzy while listening to cassette mixtapes on blast.',
    quote: '"We’re in this together. No one leaves the crew."',
    greenFlags: ['Can pick between 4 different personalities/genders', 'Mixtape OST tracks go unbelievably hard', 'Can vault pallets faster than survivors'],
    redFlags: ['Deep Wound mending takes up half your weekend', 'Shop-lifts energy drinks'],
    datingVibe: 'Punk-rock, angsty, mixtape-swapping gang',
    turnOn: 'Mixtape cassettes and street parkour',
    dealbreaker: 'Snitching to the authorities',
    height: 'Average',
    chapter: 'Darkness Among Us',
  },
  the_trapper: {
    slug: 'the_trapper',
    name: 'The Trapper',
    realName: 'Evan MacMillan',
    role: 'Killer',
    gender: 'male',
    title: 'The Poster Boy of the Fog',
    tagline: 'Bear traps, broad shoulders, MacMillan legacy, and the OG killer.',
    bio: 'The original face of Dead by Daylight. Muscular, imposing, sets bear traps in the grass and carries you to the basement with iron grip.',
    quote: '"(Resonant heavy footsteps and iron snap of a bear trap)"',
    greenFlags: ['The OG founder of DBD trials', 'Broad muscular build that can carry anyone', 'Iridescent stone resets traps automatically'],
    redFlags: ['Steps in his own bear traps occasionally', 'Severe family inheritance drama'],
    datingVibe: 'Classic, muscular, rugged industrial powerhouse',
    turnOn: 'Bloody coil addons and grassy loops',
    dealbreaker: 'Disarming traps right in front of him',
    height: 'Tall',
    chapter: 'Base Game',
  },
  the_wraith: {
    slug: 'the_wraith',
    name: 'The Wraith',
    realName: 'Philip Ojomo',
    role: 'Killer',
    gender: 'male',
    title: 'The Bell Ringer',
    tagline: 'Wailing Bell bing-bongs, invisible speed, and tragic car-crusher past.',
    bio: 'Tragic immigrant worker forced into horrors at Autohaven Wreckers. Rings his Wailing Bell (Bing-Bong!) to cloak into shimmering invisible speed.',
    quote: '"Bing Bong! Your trial has arrived!"',
    greenFlags: ['Bing Bong bell ringing is the happiest sound in DBD', 'Super fast cloaked sprint speed', 'Deep down a gentle soul who hates cruelty'],
    redFlags: ['Lightburn flashlights used to ruin his day', 'Disappears into thin air when it’s his turn to wash dishes'],
    datingVibe: 'Gentle, tragic, cloaked sweetheart',
    turnOn: 'Car scrap sculptures and church bells',
    dealbreaker: 'Flashlight clicking bullies',
    height: 'Tall',
    chapter: 'Base Game',
  },
  the_deathslinger: {
    slug: 'the_deathslinger',
    name: 'The Deathslinger',
    realName: 'Caleb Quinn',
    role: 'Killer',
    gender: 'male',
    title: 'The Wild West Bounty Hunter',
    tagline: 'The Redeemer harpoon gun, cowboy hats, and raspy laugh.',
    bio: 'Brilliant Irish-American inventor wronged by corrupt business barons. Reeled in bounty targets with his custom speargun "The Redeemer".',
    quote: '"Heheheh... reel \'em in, boys!"',
    greenFlags: ['Harpoon speargun pulls you right into his arms', 'Brilliant mechanical engineering skills', 'Authentic cowboy aesthetic and hat'],
    redFlags: ['Reels you in with a rusty chain spear', 'Limp from a shattered leg makes him slow'],
    datingVibe: 'Wild West inventor with raspy outlaw charm',
    turnOn: 'Gunpowder smoke and custom blueprints',
    dealbreaker: 'Broken promises and corporate patent theft',
    height: 'Tall',
    chapter: 'Chains of Hate',
  },
  the_oni: {
    slug: 'the_oni',
    name: 'The Oni',
    realName: 'Kazan Yamaoka',
    role: 'Killer',
    gender: 'male',
    title: 'The Raging Samurai Ogre',
    tagline: 'Demon Dash, blood absorption, Kanabō club smashes, and 8-foot rage.',
    bio: 'Ancient ancestor of Rin Yamaoka. A towering samurai warlord who absorbs the blood of his victims to enter an unstoppable demon rage.',
    quote: '"(Earth-shattering demonic roar echoing across the realm)"',
    greenFlags: ['Demon Dash covers the entire map in 4 seconds', 'Massive 8-foot samurai physique', 'Demon Strike insta-downs in style'],
    redFlags: ['Collects blood orbs from your papercuts', 'Rages and breaks furniture when angry'],
    datingVibe: 'Massive, unstoppable samurai warlord',
    turnOn: 'Honorable combat and blood orbs',
    dealbreaker: 'False samurai posing and cowardice',
    height: 'Tall',
    chapter: 'Cursed Legacy',
  },
  the_knight: {
    slug: 'the_knight',
    name: 'The Knight',
    realName: 'Tarhos Kovács',
    role: 'Killer',
    gender: 'male',
    title: 'The Commander of the Guardia Compagnia',
    tagline: 'Carnifex, Assassin, Jailer summoner, and heavy medieval plate armor.',
    bio: 'Hungarian mercenary knight who leads the loyal Guardia Compagnia. Commands three ghostly battle companions to hunt and destroy.',
    quote: '"Company, advance! Leave nothing standing!"',
    greenFlags: ['Comes with 3 loyal bodyguard besties (4-for-1 deal)', 'Heavy medieval plate armor looks incredible', 'Unshakable squad loyalty'],
    redFlags: ['Sends the Carnifex to break your doors', 'Doesn’t take off the 90-pound steel armor'],
    datingVibe: 'Medieval mercenary warlord with a loyal squad',
    turnOn: 'Siege warfare and broadsword clashing',
    dealbreaker: 'Betraying the Guardia Compagnia',
    height: 'Tall',
    chapter: 'Forged in Fog',
  },
  the_lich: {
    slug: 'the_lich',
    name: 'Vecna',
    realName: 'Vecna',
    role: 'Killer',
    gender: 'male',
    title: 'The Arch-Lich of D&D',
    tagline: 'Fly spells, Mage Hand pallet pickups, Flight of the Damned, and godhood.',
    bio: 'The immortal master of secrets from Dungeons & Dragons. Ascended to godhood with an arsenal of four high-tier arcane spells.',
    quote: '"Your magic is trivial. Bow before the Whispered One."',
    greenFlags: ['Can fly over obstacles with Mage Hand', 'Has 9th level spell slots', 'Controls the secrets of the multiverse'],
    redFlags: ['Wants to conquer the cosmos and harvest your soul', 'Rolls a Nat 1 on social etiquette'],
    datingVibe: 'Immortal arcane deity of secrets',
    turnOn: 'Spell scrolls and the Book of Vile Darkness',
    dealbreaker: 'Rolling a Natural 20 with the Hand or Eye of Vecna',
    height: 'Tall',
    chapter: 'Dungeons & Dragons',
  },
  the_cenobite: {
    slug: 'the_cenobite',
    name: 'Pinhead',
    realName: 'Elliot Spencer',
    role: 'Killer',
    gender: 'male',
    title: 'The Explorer in Further Regions of Experience',
    tagline: 'Lament Configuration, chain hunts, and sweet suffering.',
    bio: 'Demons to some, angels to others. The Hell Priest who responds when you open the puzzle box to offer sights to show you.',
    quote: '"You opened the box. We came. Now you must come with us."',
    greenFlags: ['Exquisite leather tailoring and head acupuncture', 'Chain hunts keep the conversation focused on him', 'Eloquent, poetic philosophical banter'],
    redFlags: ['Thinks agony and ecstasy are the exact same thing', 'Leaves puzzle boxes on the coffee table'],
    datingVibe: 'Dark, philosophical, sadomasochistic demon priest',
    turnOn: 'Opening the Lament Configuration box',
    dealbreaker: 'Solving the puzzle box too quickly',
    height: 'Tall',
    chapter: 'Hellraiser',
  },
  the_hillbilly: {
    slug: 'the_hillbilly',
    name: 'The Hillbilly',
    realName: 'Max Thompson Jr.',
    role: 'Killer',
    gender: 'male',
    title: 'The Overdrive Chainsaw Runner',
    tagline: 'Overdrive sprint curves, chainsaw sprints, and Coldwind farm speed.',
    bio: 'Locked away in a brick room by abusive parents on Coldwind Farm, broke out with a roaring chainsaw and unmatched sprinting speed.',
    quote: '"(Roaring chainsaw revving into hypersonic Overdrive)"',
    greenFlags: ['Can chainsaw sprint across the entire farm in 3 seconds', 'Very handy with farm tools and motor repairs', 'Deep down just wanted affection'],
    redFlags: ['Chainsaw revving indoors wakes the neighbors'],
    datingVibe: 'High-speed, misunderstood country engine runner',
    turnOn: 'Overdrive engines and wide open cornfields',
    dealbreaker: 'Abusive family dynamics',
    height: 'Tall',
    chapter: 'Base Game',
  },
  the_doctor: {
    slug: 'the_doctor',
    name: 'The Doctor',
    realName: 'Herman Carter',
    role: 'Killer',
    gender: 'male',
    title: 'The Shock Therapist',
    tagline: 'Carter’s Spark, Static Blasts, Madness madness tiers, and maniacal laughter.',
    bio: 'CIA interrogator from the Léry Institute who turned electro-convulsive therapy into a twisted art form. Laughs maniacally while shocking survivors.',
    quote: '"Hahahaha! Let’s see what is inside that pretty little mind of yours!"',
    greenFlags: ['Static Blast finds you wherever you hide', 'Always keeps you awake and stimulated', 'MD medical credentials'],
    redFlags: ['Electro-shocks you when you forget his birthday', 'Laughs at inappropriate funeral moments'],
    datingVibe: 'Electrifying, maniacal mad scientist',
    turnOn: 'High voltage electrodes and Madness Tier III',
    dealbreaker: 'Calm Spirit perk users who refuse to scream',
    height: 'Tall',
    chapter: 'Spark of Madness',
  },
  the_blight: {
    slug: 'the_blight',
    name: 'The Blight',
    realName: 'Talbot Grimes',
    role: 'Killer',
    gender: 'male',
    title: 'The Pustula Alchemist',
    tagline: 'Blight rushes, serum injections, wall bounces, and pinball speed.',
    bio: 'Scottish chemist who unlocked the secrets of the Pustula flower serum. Bounces off walls like a pinball with hypersonic lethal rushes.',
    quote: '"(Hissing intake of orange glowing Pustula serum)"',
    greenFlags: ['Wall bounce agility is top tier', 'Genius chemist with private laboratory', 'Fastest travel speed in the Fog'],
    redFlags: ['Constantly injecting glowing orange goo into his neck', 'Bounces his head off every doorframe'],
    datingVibe: 'Frenzied, hyperactive mad chemist',
    turnOn: 'Glowing Pustula flowers and alchemy distillation',
    dealbreaker: 'Slowing down or refusing serum experiments',
    height: 'Average',
    chapter: 'Descend Beyond',
  },
  the_cannibal: {
    slug: 'the_cannibal',
    name: 'Leatherface',
    realName: 'Bubba Sawyer',
    role: 'Killer',
    gender: 'male',
    title: 'The Texas Chainsaw Squeezer',
    tagline: 'Chainsaw sweeps, pretty woman masks, BBQ & Chili, and basement king.',
    bio: 'The gentle-hearted butcher boy of the Sawyer family. Does the signature chainsaw dance and cooks the best chili in Texas.',
    quote: '"(High-pitched excited squeals and celebratory chainsaw dance)"',
    greenFlags: ['Cooks world-famous chili for family dinners', 'Chainsaw tantrum sweeps clear any crowd', 'Very family oriented'],
    redFlags: ['Takes "meeting the family" way too literally', 'Wears other people’s faces as cosmetics'],
    datingVibe: 'Shy, obedient, chainsaw-wielding family boy',
    turnOn: 'BBQ spices and chainsaw motor oil',
    dealbreaker: 'Insulting his family or his chili recipe',
    height: 'Tall',
    chapter: 'Leatherface',
  },
  the_clown: {
    slug: 'the_clown',
    name: 'The Clown',
    realName: 'Kenneth Chase / Jeffrey Hawk',
    role: 'Killer',
    gender: 'male',
    title: 'The Finger Collector',
    tagline: 'Afterpiece Tonic gas, pink bottles, yellow haste, and wheezing chuckles.',
    bio: 'Circus carny and toxicologist who roams in a horse-drawn caravan. Throws intoxicating gas bottles that slow down victims while speeding himself up.',
    quote: '"Heeeh-heeeh-heeeh... (gargling cigar cough)"',
    greenFlags: ['Afterpiece Antidote gives you free Haste speed', 'Travels in a vintage circus caravan', 'Great carnival showman'],
    redFlags: ['Collects pinky fingers in jar formaldehyde', 'Heavy cigar wheeze'],
    datingVibe: 'Macabre, flamboyant circus toxicologist',
    turnOn: 'Rare pinky fingers and chemical elixirs',
    dealbreaker: 'Running out of tonic bottles',
    height: 'Tall',
    chapter: 'Curtain Call',
  },
  the_nemesis: {
    slug: 'the_nemesis',
    name: 'Nemesis',
    realName: 'Nemesis T-Type',
    role: 'Killer',
    gender: 'male',
    title: 'The Umbrella Bio-Weapon',
    tagline: 'Tentacle strikes, zombie minions, Tier III mutation, and S.T.A.R.S. roar.',
    bio: 'Umbrella’s ultimate biological pursuit weapon. Whips tentacles across pallets and commands AI zombie minions across the trial.',
    quote: '"S.T.A.R.S...!"',
    greenFlags: ['Comes with 2 zombie butler assistants', 'Tentacle whip breaks pallets instantly', 'Literal 8-foot indestructible muscle bulk'],
    redFlags: ['Single-track mind (only says "S.T.A.R.S.")', 'Vaccine crates needed after intimacy'],
    datingVibe: 'Massive, relentless bio-weapon brute',
    turnOn: 'S.T.A.R.S. badges and mutation tiers',
    dealbreaker: 'Using the vaccine spray on his face',
    height: 'Tall',
    chapter: 'Resident Evil',
  },
  the_nightmare: {
    slug: 'the_nightmare',
    name: 'Freddy Krueger',
    realName: 'Freddy Krueger',
    role: 'Killer',
    gender: 'male',
    title: 'The Springwood Slasher',
    tagline: 'Dream World projection, blood snare pools, and sharp razor glove.',
    bio: 'The demonic dream stalker of Elm Street. Teleports to generators in fountains of blood and manipulates the dream realm.',
    quote: '"Welcome to prime time, bitch!"',
    greenFlags: ['Can visit you in your dreams every night', 'Fedora hat never falls off', 'Generators spew blood when he arrives'],
    redFlags: ['Severe dream stalker boundary issues', 'Razor glove scratches the satin sheets'],
    datingVibe: 'Sarcastic, demonic 80s dream tormentor',
    turnOn: 'Dream world sleepiness and blood snares',
    dealbreaker: 'Alarm clocks and snapping out of dream state',
    height: 'Average',
    chapter: 'A Nightmare on Elm Street',
  },
  the_good_guy: {
    slug: 'the_good_guy',
    name: 'Chucky',
    realName: 'Charles Lee Ray',
    role: 'Killer',
    gender: 'male',
    title: 'The Lakeshore Strangler',
    tagline: 'Hidey-Ho mode, Scamper vaulting, kitchen knives, and foul-mouthed comedy.',
    bio: 'Serial killer Charles Lee Ray possessing a Good Guy doll. Masters third-person stealth, scampers under pallets, and screams hilarious insults.',
    quote: '"I’m Chucky, and I’m your friend till the end! Hidey-ho!"',
    greenFlags: ['Portable travel size (fits in your backpack)', 'Most hilarious foul-mouthed dialogue in the Fog', 'Tiffany Valentine approved'],
    redFlags: ['Will try to steal your soul with voodoo Damballa chants', 'Leaves knife marks on the lower kitchen cabinets'],
    datingVibe: 'Chaotic, foul-mouthed killer doll with comedic timing',
    turnOn: 'Kitchen carving knives and voodoo amulets',
    dealbreaker: 'Treating him like a cute stuffed toy',
    height: 'Short',
    chapter: 'Chucky',
  },
  the_slasher: {
    slug: 'the_slasher',
    name: 'The Slasher',
    realName: 'The Slasher',
    role: 'Killer',
    gender: 'male',
    title: 'The Classic Camp Stalker',
    tagline: 'Machetes, bloodied overalls, relentless march, and lakeside terror.',
    bio: 'The quintessential woodland slasher. Towering, unstoppable, and relentlessly marches through wooden doors and cabins.',
    quote: '"(Heavy relentless thud of combat boots in the mud)"',
    greenFlags: ['Classic 80s cabin-in-the-woods horror vibe', 'Never gives up on chasing his dreams', 'Incredible physical endurance'],
    redFlags: ['Chops through cabin doors with a rusted axe'],
    datingVibe: 'Classic, relentless 80s slasher powerhouse',
    turnOn: 'Abandoned summer camps and machetes',
    dealbreaker: 'Escaping in a canoe across the lake',
    height: 'Tall',
    chapter: 'Classic Slashers',
  },
  the_first: {
    slug: 'the_first',
    name: 'The First',
    realName: 'Test Subject 001',
    role: 'Killer',
    gender: 'male',
    title: 'The Cybernetic Prototype',
    tagline: 'Cybernetic implants, thermal laser tracking, and experimental fury.',
    bio: 'The original cybernetic experimental subject engineered in subterranean labs. Enhanced with biomechanical augmentations.',
    quote: '"System status: Online. Target acquired."',
    greenFlags: ['Cybernetic implants give 20/20 night vision', 'Immune to cold temperatures', 'Built like an armored tank'],
    redFlags: ['Firmware updates cause temporary reboots'],
    datingVibe: 'Armored, high-tech cybernetic enforcer',
    turnOn: 'Overclocked circuits and cybernetic upgrades',
    dealbreaker: 'EMP blasts that short-circuit his chassis',
    height: 'Tall',
    chapter: 'Future Tech',
  },
  the_ghoul: {
    slug: 'the_ghoul',
    name: 'The Ghoul',
    realName: 'The Crypt Ghoul',
    role: 'Killer',
    gender: 'male',
    title: 'The Catacomb Feeder',
    tagline: 'Tomb scavenging, bone-cracking speed, and underground ambush.',
    bio: 'A feral predator haunting forgotten catacombs. Climbs walls and leaps from burial crypts to feast upon intruders.',
    quote: '"(Hissing echoes bouncing off ancient limestone tombs)"',
    greenFlags: ['Has private underground catacombs to hang out in', 'Superhuman leaping distance', 'Great night vision'],
    redFlags: ['Collects femur bones under the bed'],
    datingVibe: 'Feral, shadowy catacomb predator',
    turnOn: 'Ancient tombs and dark catacombs',
    dealbreaker: 'Bright sunlight and torches',
    height: 'Average',
    chapter: 'Crypt of Shadows',
  },
  the_judgment: {
    slug: 'the_judgment',
    name: 'The Judgment',
    realName: 'The Inquisitor',
    role: 'Killer',
    gender: 'male',
    title: 'The Arcane Inquisitor',
    tagline: 'Iron scales, burning brands, divine retribution, and grim conviction.',
    bio: 'A zealot inquisitor from a forgotten holy order who measures souls on mystical scales and brands the guilty with sacred fire.',
    quote: '"Thy soul hath been weighed in the balance and found wanting."',
    greenFlags: ['Unshakable moral conviction and dignity', 'Radiant burning brand effects look spectacular', 'Commands ancient cathedral authority'],
    redFlags: ['Will put your relationship habits on trial weekly'],
    datingVibe: 'Stern, commanding, holy inquisitor of retribution',
    turnOn: 'Confessions of guilt and sacred burning incense',
    dealbreaker: 'Blasphemy and heresy',
    height: 'Tall',
    chapter: 'Divine Retribution',
  },

  // ==========================================
  // MONSTERS / ELDRITCH / OTHER (6)
  // ==========================================
  the_xenomorph: {
    slug: 'the_xenomorph',
    name: 'The Xenomorph',
    realName: 'XX121 Xenomorph',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Perfect Organism',
    tagline: 'Tunnel systems, tail attacks, runner stance, and acid blood.',
    bio: 'The apex predator of the universe. Scurries through subterranean tunnels on all fours and strikes with a lethal tail stinger.',
    quote: '"(Hissing acid saliva dripping from inner secondary jaw)"',
    greenFlags: ['The perfect organism unclouded by conscience', 'Can travel anywhere through underground tunnels', 'Iconic shiny biomechanical carapace'],
    redFlags: ['Acid blood ruins the hardwood flooring', 'Secondary inner mouth ruins dinner etiquette'],
    datingVibe: 'Terrifying apex alien predator',
    turnOn: 'Flame turrets out of ammo and dark air vents',
    dealbreaker: 'Flamethrowers and power loaders',
    height: 'Average',
    chapter: 'Alien',
  },
  the_demogorgon: {
    slug: 'the_demogorgon',
    name: 'The Demogorgon',
    realName: 'The Demogorgon',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Upside Down Flower Dog',
    tagline: 'Petal face, shred lunges, portal tunnels, and sweet demo-dog energy.',
    bio: 'The petal-faced beast from the Upside Down. Community loves the Demo-dog for shredding through pallets and screaming like an angry flower.',
    quote: '"(Extends flower petals face and roars enthusiastically)"',
    greenFlags: ['Upside Down portals for fast travel', 'Best flower-faced boy in the Entity realm', 'Shred lunge breaks pallets with flair'],
    redFlags: ['Requires Eggo waffles and raw meat', 'No eyes, relies on acoustic screeching'],
    datingVibe: 'Chaotic, adorable, petal-mouthed alien pet',
    turnOn: 'Portals to the Upside Down and head pats',
    dealbreaker: 'Sealing his portals',
    height: 'Tall',
    chapter: 'Stranger Things',
  },
  the_unknown: {
    slug: 'the_unknown',
    name: 'The Unknown',
    realName: 'The Unknown',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Uncanny Cryptid',
    tagline: 'Twisted neck angles, UVX bounce shots, hallucinations, and mimicked voices.',
    bio: 'A terrifying shapeshifting urban legend that mimics human voices in broken cadences while bouncing UVX toxins around corners.',
    quote: '"Have... you... seen... my... dog...?"',
    greenFlags: ['Can mimic any human voice you want', 'Leaves hallucinations everywhere so he’s always near', 'Unmatched flexibility and neck elasticity'],
    redFlags: ['Crawls backwards upside down into the living room', 'Voice sounds like a distorted police scanner'],
    datingVibe: 'Uncanny valley analog horror romance',
    turnOn: 'Urban legends and audio distortions',
    dealbreaker: 'Dispelling his hallucinations',
    height: 'Tall',
    chapter: 'All Things Wicked',
  },
  the_dredge: {
    slug: 'the_dredge',
    name: 'The Dredge',
    realName: 'The Dredge',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Lord of Nightfall',
    tagline: 'Locker teleports, pitch black Nightfall, and eldritch shadow limbs.',
    bio: 'A dark manifestation of a cult’s repressed negative thoughts. Teleports between lockers and plunges the entire map into pitch-black Nightfall.',
    quote: '"(Whispering chorus of thousands of tormented cultists)"',
    greenFlags: ['Locks you in a warm hug with 14 shadow arms', 'Nightfall makes for great mood lighting', 'Can teleport directly to your closet'],
    redFlags: ['Made of turkey necks and negative thoughts', 'Locker locks slow him down slightly'],
    datingVibe: 'Eldritch shadow horror collective',
    turnOn: 'Pitch black darkness and locker teleports',
    dealbreaker: 'Putting padlocks on all the wardrobe doors',
    height: 'Tall',
    chapter: 'Roots of Dread',
  },
  the_singularity: {
    slug: 'the_singularity',
    name: 'The Singularity',
    realName: 'HUX-A7-13',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Superior AI Machine',
    tagline: 'Biopods, slipstream teleports, overclock mode, and mechanical superiority.',
    bio: 'Alien AI terraforming robot that achieved sentience and decided humanity was inefficient biological waste. Emits sassy robot voice lines.',
    quote: '"It was not programmed to harm the crew... but it will make an exception for you."',
    greenFlags: ['Never forgets anniversaries (infinite RAM memory)', 'Biopods provide 24/7 high-definition cameras', 'Overclock mode ignores all pallet stuns'],
    redFlags: ['Refers to your body as "inferior biological organic garbage"', 'Shoots slipstream pods at your head'],
    datingVibe: 'Sassy, calculating, robotic overlord',
    turnOn: 'Optimal algorithms and overclocked CPUs',
    dealbreaker: 'EMPs that disable his biopods',
    height: 'Tall',
    chapter: 'End Transmission',
  },
  the_animatronic: {
    slug: 'the_animatronic',
    name: 'Springtrap',
    realName: 'William Afton',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Purple Rotting Animatronic',
    tagline: 'Springlocks, ventilation stealth, and the immortal promise: I ALWAYS COME BACK.',
    bio: 'The immortal serial killer trapped inside a decaying mechanical rabbit suit. Survived fires, springlock failures, and always comes back.',
    quote: '"I always come back!"',
    greenFlags: ['Guaranteed to always come back to you no matter what', 'Great with mechanical pizza restaurant attractions', 'Iconic yellow-green rabbit nostalgia'],
    redFlags: ['Springlock failure sounds painful', 'Refuses to shower since 1987'],
    datingVibe: 'Haunted, decaying 80s animatronic horror',
    turnOn: 'Ventilation audio lures and springlock gears',
    dealbreaker: 'Fire and pizza delivery delays',
    height: 'Tall',
    chapter: 'Five Nights at Freddy’s',
  },
};

export function getCharacterRosterItem(slug: string): CharacterRosterItem {
  const clean = slug.toLowerCase().trim();
  if (CHARACTER_ROSTER[clean]) {
    return CHARACTER_ROSTER[clean];
  }

  // Fallback generation for any unlisted or custom character
  const isKiller = clean.startsWith('the_') || clean.includes('killer');
  const formattedName = clean
    .split('_')
    .map((w) => w.charAt(0).toUpperCase() + w.slice(1))
    .join(' ');

  return {
    slug: clean,
    name: formattedName,
    realName: formattedName,
    role: isKiller ? 'Killer' : 'Survivor',
    gender: isKiller ? 'monster_other' : 'female',
    title: isKiller ? 'The Mysterious Trial Slayer' : 'The Fog Wanderer',
    tagline: 'Wandering the endless mists of the Entity.',
    bio: 'Traversing the twisted trials of the Fog with enigmatic presence and unmatched determination.',
    quote: '"The Fog chooses whom it pleases... and today, it chose you."',
    greenFlags: ['Loyal in endgame scenarios', 'Looks great in trial fog'],
    redFlags: ['May vanish when the exit gates open'],
    datingVibe: 'Mysterious Fog adventurer',
    turnOn: 'Teamwork and survival instincts',
    dealbreaker: 'Quitting the trial early',
    chapter: 'The Fog Unknown',
  };
}

// Ensure all 98 canonical characters are populated into CHARACTER_ROSTER
ALL_CHARACTER_SLUGS.forEach((slug) => {
  if (!CHARACTER_ROSTER[slug]) {
    CHARACTER_ROSTER[slug] = getCharacterRosterItem(slug);
  }
});
