// frontend/src/components/smash-or-pass/editionsRegistry.ts
import { CharacterRosterItem, CHARACTER_ROSTER, ALL_CHARACTER_SLUGS } from './characterRoster';

export interface SmashEdition {
  id: string;
  name: string;
  subtitle: string;
  description: string;
  iconName: 'Heart' | 'Sparkles' | 'Flame' | 'FolderPlus';
  badgeColor: string;
  characters: CharacterRosterItem[];
}

// Hooked on You Island Dating Edition Roster
export const HOOKED_ON_YOU_ROSTER: CharacterRosterItem[] = [
  {
    slug: 'the_trapper_hoy',
    name: 'The Trapper (Island)',
    role: 'Killer',
    gender: 'male',
    title: 'The Brooding Beach Jock',
    tagline: 'Muscles, bear traps, and secretly loves carving romantic driftwood.',
    bio: 'He may look intimidating with his machete and spiked traps, but take him on a walk along the tropical beach and he might just show you his soft, artistic side.',
    greenFlags: ['Enjoys romantic sunsets', 'Will carry you when tired', 'Protective to a fault'],
    redFlags: ['Steps on his own traps when flustered', 'Aggressive arm wrestling'],
    turnOn: 'Sun-kissed skin and deep philosophical conversations under the stars',
    dealbreaker: 'People who touch his private trap stash',
    quote: '"If you step into my snare, I won’t let you go easily."',
  },
  {
    slug: 'the_huntress_hoy',
    name: 'The Huntress (Bikini)',
    role: 'Killer',
    gender: 'female',
    title: 'The Amazonian Beach Queen',
    tagline: 'Loves coconut bowling, throwing hatchets, and singing island lullabies.',
    bio: 'Standing tall with undeniable athletic grace, she will catch fish with her bare hands for your candlelit beach dinner and sing you gentle melodies until dawn.',
    greenFlags: ['Provides abundant seafood feasts', 'Towering Amazonian cuddles', 'Passionate singer'],
    redFlags: ['Throws hatchets at rival suitors', 'Communication via animal grunts'],
    turnOn: 'Courage, loyalty, and someone who appreciates a good bear hug',
    dealbreaker: 'Cowards who run away from a friendly sparring match',
    quote: '"La la la... You belong by my side."',
  },
  {
    slug: 'the_spirit_hoy',
    name: 'The Spirit (Resort)',
    role: 'Killer',
    gender: 'female',
    title: 'The Goth Resort Princess',
    tagline: 'Sunhat, dark parasol, and loves sipping tropical mocktails in the shade.',
    bio: 'Floating just above the warm sand, Rin enjoys quiet afternoons reading gothic literature under a wide palm umbrella, phasing in and out of your vision to tease you.',
    greenFlags: ['Extremely loyal once trust is earned', 'Aesthetic goth fashion sense', 'Intense eye contact'],
    redFlags: ['Phases away during arguments', 'Sword practice near poolside'],
    turnOn: 'Patience, shared silence, and genuine emotional honesty',
    dealbreaker: 'Loud party crashers and betrayal of trust',
    quote: '"I will appear where you least expect me... next to you."',
  },
  {
    slug: 'the_wraith_hoy',
    name: 'The Wraith (Beach)',
    role: 'Killer',
    gender: 'male',
    title: 'The Gentle Bell Chimer',
    tagline: 'Wears vibrant floral shorts and plays steel drums by the bonfire.',
    bio: 'Philip is the gentle soul of the island. He enjoys chiming his bell to create melodic rhythms, helping injured tropical birds, and sharing mango smoothies.',
    greenFlags: ['Soft-spoken and deeply empathetic', 'Great listener', 'Gentle hands'],
    redFlags: ['Disappears into thin air when embarrassed', 'Overthinks every text'],
    turnOn: 'Kindness, musical harmony, and warm smiles',
    dealbreaker: 'Cruelty to island wildlife and loud yelling',
    quote: '"Bing bong... My heart rings for you."',
  },
  {
    slug: 'claudette_morel_hoy',
    name: 'Claudette (Island Botanist)',
    role: 'Survivor',
    gender: 'female',
    title: 'The Tropical Herbalist',
    tagline: 'Crafts hibiscus flower crowns and aloe vera sun lotions.',
    bio: 'She knows the secret properties of every exotic tropical flower on the island. Spend an afternoon with her in the greenhouse learning how to blend aromatic island teas.',
    greenFlags: ['Always has natural remedies ready', 'Soft and caring demeanor', 'Quiet dates in nature'],
    redFlags: ['Hides in the jungle bushes when approached', 'Prioritizes rare orchids over dates'],
    turnOn: 'Curiosity about botany and gentle stargazing',
    dealbreaker: 'Trampling rare island flora',
    quote: '"This flower only blooms when two hearts are near."',
  },
  {
    slug: 'dwight_fairfield_hoy',
    name: 'Dwight (Lifeguard)',
    role: 'Survivor',
    gender: 'male',
    title: 'The Anxious Lifeguard',
    tagline: 'Whistle around his neck, oversized sunglasses, and trying his very best.',
    bio: 'He took a 3-week online lifeguard certification course and takes his beach patrol duties very seriously. He will personally apply sunscreen to your shoulders with shaking hands.',
    greenFlags: ['Unconditional devotion', 'Wholesome dad jokes', 'Will jump into water to save you'],
    redFlags: ['Panics in waist-deep water', 'Hides in beach lockers when overwhelmed'],
    turnOn: 'Reassurance, positive affirmations, and holding hands',
    dealbreaker: 'Criticizing his leadership skills in front of the crew',
    quote: '"I promise to watch over you! From this lifeguard tower!"',
  },
  {
    slug: 'the_trickster_hoy',
    name: 'The Trickster (Summer Idol)',
    role: 'Killer',
    gender: 'male',
    title: 'The K-Pop Poolside Sensation',
    tagline: 'Neon sunglasses, open tropical silk shirt, and unlimited charisma.',
    bio: 'Ji-Woon brings VIP concert energy to every beach cabana. He will write you private acoustic ballads and throw rose-colored throwing knives at fruit targets for your entertainment.',
    greenFlags: ['Flawless sense of style', 'Romantic serenades on demand', 'Treats you like a superstar'],
    redFlags: ['Extremely vain', 'Records his own voice memo compliments'],
    turnOn: 'Adoring praise, high fashion, and spotlight drama',
    dealbreaker: 'Refusing to be his VIP muse',
    quote: '"Every melody I write has your name hidden in the chorus."',
  },
  {
    slug: 'the_ocean_hoy',
    name: 'The Entity (Island Spirit)',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Eldritch Island Sovereign',
    tagline: 'Sparkling bioluminescent waves and cosmic tentacle embraces.',
    bio: 'The ancient being that created the island paradise. A cosmic romantic who controls the tides and manifests warm ocean breezes whenever you are feeling down.',
    greenFlags: ['Created an entire private paradise for you', 'Cosmic devotion across dimensions', 'Controls the weather'],
    redFlags: ['Might consume your soul for eternity', 'Incomprehensible eldritch whispers'],
    turnOn: 'Total devotion and willing sacrifice of your mortal concerns',
    dealbreaker: 'Leaving the island paradise without saying goodbye',
    quote: '"All waters and souls flow into me."',
  },
];

// Legendary Skins Edition Roster
export const LEGENDARY_ROSTER: CharacterRosterItem[] = [
  {
    slug: 'william_birkin',
    name: 'William Birkin',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The G-Virus Colossus',
    tagline: 'Massive shoulder eye, unstoppable bio-hazard strength.',
    bio: 'Driven by scientific ambition and mutated by the G-Virus, Birkin is looking for someone who appreciates complex viral genetics and pipe-swinging workouts.',
    greenFlags: ['Endless physical stamina', 'Giant shoulder eye is always watching over you', 'Brilliant scientific mind'],
    redFlags: ['Mutates when angry', 'Stalks underground sewer labs'],
    turnOn: 'Bio-tech research and genetic compatibility',
    dealbreaker: 'Vaccine distribution and lab inspections',
    quote: '"G-Virus... is perfection... like you."',
  },
  {
    slug: 'hunk',
    name: 'HUNK (Grim Reaper)',
    role: 'Killer',
    gender: 'male',
    title: 'The Unstoppable Operative',
    tagline: 'Gas mask, tactical armor, and never leaves an extraction point.',
    bio: 'Cold, calculated, and completely mission-focused. He will secure your perimeter, extract you from any danger, and never miss an anniversary mission deadline.',
    greenFlags: ['100% mission survival rate', 'Disciplined and calm under pressure', 'Tactical protection'],
    redFlags: ['Never takes off the gas mask', 'Prioritizes extraction over small talk'],
    turnOn: 'Precision, efficiency, and surviving against all odds',
    dealbreaker: 'Missing the extraction helicopter window',
    quote: '"This is the Grim Reaper. Extraction coordinates confirmed."',
  },
  {
    slug: 'james_sunderland',
    name: 'James Sunderland',
    role: 'Survivor',
    gender: 'male',
    title: 'The Silent Hill Wanderer',
    tagline: 'Green military jacket, searching for letters from lost love.',
    bio: 'A somber and introspective soul carrying deep emotional weight. He is searching for redemption and genuine affection amidst the foggy streets.',
    greenFlags: ['Deep emotional devotion', 'Will cross dimensions to find you', 'Comfortable with heavy conversations'],
    redFlags: ['Carries unsettling pillows', 'Attracted to foggy nightmare towns'],
    turnOn: 'Handwritten letters, nostalgia, and quiet diner coffee',
    dealbreaker: 'Hidden secrets and deception',
    quote: '"Could you really be here waiting for me?"',
  },
  {
    slug: 'maria',
    name: 'Maria',
    role: 'Survivor',
    gender: 'female',
    title: 'The Seductive Enigma',
    tagline: 'Leopard print, butterfly tattoo, and alluring charm.',
    bio: 'Playful, alluring, and unapologetically confident. She knows how to keep you captivated with witty banter and captivating smiles in the darkest corridors.',
    greenFlags: ['Magnetic charismatic presence', 'Bold fashion statements', 'Never a dull moment'],
    redFlags: ['Might be a manifestation of your subconscious desires', 'Mood shifts rapidly'],
    turnOn: 'Romantic devotion, mystery, and confident compliments',
    dealbreaker: 'Being boring and comparing her to your ex',
    quote: '"See? I’m real. Don’t you want to hold me?"',
  },
  {
    slug: 'cybil_bennett',
    name: 'Cybil Bennett',
    role: 'Survivor',
    gender: 'female',
    title: 'The Brave Patrol Officer',
    tagline: 'Motorcycle boots, service revolver, and fierce protective instincts.',
    bio: 'A tough Brahms police officer who won’t back down from anything. She will ride her motorcycle through blizzards and fog to make sure you get home safe.',
    greenFlags: ['Fierce protector', 'Great motorcycle road trips', 'Always has your back'],
    redFlags: ['Workaholic patrol schedule', 'Suspicious of unusual tea mixtures'],
    turnOn: 'Courage, honesty, and late-night highway rides',
    dealbreaker: 'Breaking local traffic safety regulations',
    quote: '"Stay close to me and keep your head down."',
  },
  {
    slug: 'lisa_garland',
    name: 'Lisa Garland',
    role: 'Survivor',
    gender: 'female',
    title: 'The Compassionate Nurse',
    tagline: 'Alchemilla hospital uniform, warm bedside manner, and a heart of gold.',
    bio: 'Gentle and deeply caring, Lisa will nurse any wound and provide a calming presence when the world feels terrifying. She just wants someone to sit with her in the quiet ward.',
    greenFlags: ['Endless tenderness', 'Expert medical care', 'Warm listening ear'],
    redFlags: ['Cannot leave the hospital grounds', 'Occasionally bleeds from forehead'],
    turnOn: 'Sincere companionship, gentle touch, and soothing tea',
    dealbreaker: 'Cold indifference to suffering',
    quote: '"Please don’t leave me alone in the dark."',
  },
  {
    slug: 'naughty_bear',
    name: 'Naughty Bear',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Vengeful Teddy',
    tagline: 'Plush fur, party hat, and loves throwing chaotic celebrations.',
    bio: 'He was not invited to the party, so he crashed it in style! Underneath all the stuffing is a teddy bear who just wants a best friend to attend his tea parties.',
    greenFlags: ['Free hugs for life', 'Exciting party games', 'Never sheds fur'],
    redFlags: ['Extreme grudge holder', 'Aggressive party invitations'],
    turnOn: 'Party invitations, cupcakes, and matching plushies',
    dealbreaker: 'Forgetting to RSVP to his birthday party',
    quote: '"Nobody ignores Naughty\'s invitation!"',
  },
  {
    slug: 'baba_yaga',
    name: 'Baba Yaga',
    role: 'Killer',
    gender: 'female',
    title: 'The Slavic Witch',
    tagline: 'Hut on chicken legs, ancient herbal cauldrons, and folklore wisdom.',
    bio: 'An ancient sorceress who flies in a mortar and pestle. She will brew you enchanted longevity potions and cook hearty wild mushroom stews.',
    greenFlags: ['Rich folklore stories by the hearth', 'Ancient magical protection', 'Unforgettable homemade stews'],
    redFlags: ['Her house has literal chicken legs and wanders off', 'Picky culinary tastes'],
    turnOn: 'Clever riddles, magical herbs, and ancient wisdom',
    dealbreaker: 'Lying to an elder witch',
    quote: '"Solve my riddle, and my hearth is yours."',
  },
  {
    slug: 'the_look_see',
    name: 'The Look-See',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Crypt TV Spectre',
    tagline: 'Tailored suit, wide toothy grin, and helps you let go of grief.',
    bio: 'Dapper and sharply dressed, the Look-See teaches people to release the burdens of their past. He will take you on elegant night walks through the rain.',
    greenFlags: ['Exceptionally well-dressed in tailored suits', 'Always smiling', 'Helps you declutter emotional baggage'],
    redFlags: ['Takes things if you cannot release them', 'Never blinks'],
    turnOn: 'Emotional maturity, moving forward in life, and fine tailoring',
    dealbreaker: 'Clinging to unhealthy past attachments',
    quote: '"If you can\'t release it, I will take a piece of you."',
  },
  {
    slug: 'minotaur',
    name: 'The Minotaur',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Labyrinth Champion',
    tagline: 'Towering horns, ancient bronze armor, and unstoppable labyrinth guide.',
    bio: 'He knows every corner of the maze and will navigate you through any difficult trial in life. Built like a fortress, he will protect your heart with ancient power.',
    greenFlags: ['Never gets lost in IKEA or mazes', 'Imposing physical presence', 'Loyal ancient warrior'],
    redFlags: ['Charges through walls when angry', 'Requires huge amounts of food'],
    turnOn: 'Labyrinth puzzles, strength, and honoring ancient codes',
    dealbreaker: 'Leaving red thread clues in his maze',
    quote: '"I will guide you through the darkest maze."',
  },
  {
    slug: 'tiffany_valentine',
    name: 'Tiffany Valentine',
    role: 'Killer',
    gender: 'female',
    title: 'The Blonde Doll of Mayhem',
    tagline: 'Leather jacket, bridal veil, and loves candlelit crime sprees.',
    bio: 'Glamorous, passionate, and hopelessly romantic. She believes in true love that lasts beyond mortality, and she will bake you Swedish meatballs while rocking out to 80s glam rock.',
    greenFlags: ['Ride-or-die romantic partner', 'Great cook', 'Flawless rock-and-roll style'],
    redFlags: ['Possessed doll anatomy', 'Enjoys arson on romantic dates'],
    turnOn: 'Leather jackets, devotion, and a wicked sense of humor',
    dealbreaker: 'Cheating on her or disrespecting Swedish meatballs',
    quote: '"You\'re the only one I want to kill with forever."',
  },
  {
    slug: 'chatterer',
    name: 'Chatterer Cenobite',
    role: 'Killer',
    gender: 'monster_other',
    title: 'The Rhythmic Cenobite',
    tagline: 'Chattering teeth, leather vestments, and cosmic sensations.',
    bio: 'A member of the Order of the Gash who communicates through percussive teeth chattering. He experiences sensations on planes ordinary mortals could never fathom.',
    greenFlags: ['Never complains out loud', 'High tolerance for pain and cold', 'Master of the puzzle box'],
    redFlags: ['Constant rhythmic teeth clicking', 'Hook-based home decor'],
    turnOn: 'Solving the Lament Configuration and profound sensory experiences',
    dealbreaker: 'Muffled conversations and earplugs',
    quote: '*Click-clack-click-clack...*',
  },
];

// Editions Registry
export const SMASH_OR_PASS_EDITIONS: Record<string, SmashEdition> = {
  canon: {
    id: 'canon',
    name: 'Dead by Daylight: Fog Canon',
    subtitle: 'Official 98 Characters',
    description: 'The definitive complete roster of all 54 Survivors and 44 Killers in the Fog.',
    iconName: 'Heart',
    badgeColor: 'from-rose-600 to-pink-600',
    characters: Object.values(CHARACTER_ROSTER),
  },
  hooked_on_you: {
    id: 'hooked_on_you',
    name: 'Hooked on You: Island Romance',
    subtitle: 'Dating Sim Edition (8 Candidates)',
    description: 'Tropical paradise beach romance with sunny outfits, island banter, and beach cuddles.',
    iconName: 'Sparkles',
    badgeColor: 'from-cyan-500 to-blue-600',
    characters: HOOKED_ON_YOU_ROSTER,
  },
  legendary_cosplay: {
    id: 'legendary_cosplay',
    name: 'Legendary Skins & Collabs',
    subtitle: 'Iconic Legends (12 Candidates)',
    description: 'Resident Evil, Silent Hill, and Crypt TV iconic skins with tailored dating profiles.',
    iconName: 'Flame',
    badgeColor: 'from-amber-500 to-rose-600',
    characters: LEGENDARY_ROSTER,
  },
};

export function getEdition(editionId: string): SmashEdition {
  return SMASH_OR_PASS_EDITIONS[editionId] || SMASH_OR_PASS_EDITIONS.canon;
}
