# backend/app/services/gauntlet/__init__.py
from app.services.gauntlet.constants import (
    BUILD_SIZE,
    CHECKPOINT_INTERVAL,
    DEFAULT_GAME_MODE,
    GAME_MODES,
    GENERAL_CHARACTER,
    PICK_CHARACTER_MODES,
    get_characters_per_match,
    get_players_per_character,
    is_checkpoint,
    KILLER_TIERS,
    ORIGINAL_KILLER_ROSTER_LIMIT,
    ORIGINAL_SURVIVOR_ROSTER_LIMIT,
    SURVIVOR_TIERS,
    get_tier_info,
)
from app.services.gauntlet.roller import (
    get_character_teachable_perks,
    get_owned_character_ids,
    get_owned_character_names,
    build_loadout,
    build_team_loadout,
    pick_initial_target,
    pick_initial_targets,
    resolve_character_names_by_ids,
    roll_gauntlet_target,
    roll_gauntlet_team,
)
from app.services.gauntlet.stats import fetch_gauntlet_user_stats

__all__ = [
    "CHECKPOINT_INTERVAL",
    "BUILD_SIZE",
    "GENERAL_CHARACTER",
    "GAME_MODES",
    "PICK_CHARACTER_MODES",
    "get_characters_per_match",
    "get_players_per_character",
    "is_checkpoint",
    "DEFAULT_GAME_MODE",
    "ORIGINAL_KILLER_ROSTER_LIMIT",
    "ORIGINAL_SURVIVOR_ROSTER_LIMIT",
    "SURVIVOR_TIERS",
    "KILLER_TIERS",
    "get_tier_info",
    "get_owned_character_names",
    "get_owned_character_ids",
    "resolve_character_names_by_ids",
    "get_character_teachable_perks",
    "build_loadout",
    "build_team_loadout",
    "pick_initial_targets",
    "roll_gauntlet_team",
    "pick_initial_target",
    "roll_gauntlet_target",
    "fetch_gauntlet_user_stats",
]
