# backend/app/seeds/smash_roster_seeder.py
import logging
import uuid
from typing import Any, Dict, List
from sqlalchemy import select
from app.core.extensions import db
from app.models.smash_or_pass import (
    Entity,
    EntityStat,
    Roster,
    SmashPassStat,
    Translation,
)

logger = logging.getLogger(__name__)

# ==========================================
# ROSTERS SPECIFICATION (6 ROSTERS)
# ==========================================

ROSTERS_DATA = [
    {
        "slug": "canon",
        "name_i18n_key": "smashOrPass.rosters.canon.name",
        "description_i18n_key": "smashOrPass.rosters.canon.desc",
        "cover_image_url": "/images/rosters/canon.webp",
        "theme_color": "#ff0055",
        "category": "DBD Canon",
        "is_nsfw": False,
        "is_active": True,
    },
    {
        "slug": "hooked_on_you",
        "name_i18n_key": "smashOrPass.rosters.hoy.name",
        "description_i18n_key": "smashOrPass.rosters.hoy.desc",
        "cover_image_url": "/images/rosters/hooked_on_you.webp",
        "theme_color": "#06d6a0",
        "category": "Dating Sim",
        "is_nsfw": False,
        "is_active": True,
    },
    {
        "slug": "legendary_cosplay",
        "name_i18n_key": "smashOrPass.rosters.legendary.name",
        "description_i18n_key": "smashOrPass.rosters.legendary.desc",
        "cover_image_url": "/images/rosters/legendary_cosplay.webp",
        "theme_color": "#ffd166",
        "category": "Collabs & Skins",
        "is_nsfw": False,
        "is_active": True,
    },
    {
        "slug": "cyberpunk_2077",
        "name_i18n_key": "smashOrPass.rosters.cyberpunk.name",
        "description_i18n_key": "smashOrPass.rosters.cyberpunk.desc",
        "cover_image_url": "/images/rosters/cyberpunk_2077.webp",
        "theme_color": "#00f5d4",
        "category": "Cyberpunk",
        "is_nsfw": False,
        "is_active": True,
    },
    {
        "slug": "anime_manga",
        "name_i18n_key": "smashOrPass.rosters.anime.name",
        "description_i18n_key": "smashOrPass.rosters.anime.desc",
        "cover_image_url": "/images/rosters/anime_manga.webp",
        "theme_color": "#b185db",
        "category": "Anime",
        "is_nsfw": False,
        "is_active": True,
    },
    {
        "slug": "gothic_eldritch",
        "name_i18n_key": "smashOrPass.rosters.gothic.name",
        "description_i18n_key": "smashOrPass.rosters.gothic.desc",
        "cover_image_url": "/images/rosters/gothic_eldritch.webp",
        "theme_color": "#7209b7",
        "category": "Gothic Horror",
        "is_nsfw": False,
        "is_active": True,
    },
]

# ==========================================
# CANON ROSTER: 98 CHARACTERS
# (28 Female Survivors, 26 Male Survivors,
#  12 Female Killers, 26 Male Killers, 6 Monsters)
# ==========================================

CANON_ENTITIES: List[Dict[str, Any]] = [
    # --- FEMALE SURVIVORS (28) ---
    {
        "slug": "ada_wong",
        "name": "Ada Wong",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Ada Wong/icon.png",
        "metadata": {
            "chaos_score": 75,
            "danger_level": "Moderate",
            "quote": "I have my own agenda.",
            "compatibility_tags": ["Enigmatic", "Espionage", "Seductive"],
            "archetype": "Secret Agent",
        },
    },
    {
        "slug": "sable_ward",
        "name": "Sable Ward",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Sable Ward/icon.png",
        "metadata": {
            "chaos_score": 88,
            "danger_level": "Moderate",
            "quote": "The dark isn't so scary once you embrace it.",
            "compatibility_tags": ["Goth", "Occult", "Rebel"],
            "archetype": "Occult Rebel",
        },
    },
    {
        "slug": "feng_min",
        "name": "Feng Min",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Feng Min/icon.png",
        "metadata": {
            "chaos_score": 60,
            "danger_level": "Low",
            "quote": "Just one more game...",
            "compatibility_tags": ["Gamer", "Competitive", "Caffeine-fueled"],
            "archetype": "Esports Pro",
        },
    },
    {
        "slug": "kate_denson",
        "name": "Kate Denson",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Kate Denson/icon.png",
        "metadata": {
            "chaos_score": 40,
            "danger_level": "Low",
            "quote": "Music can soothe even the darkest beast.",
            "compatibility_tags": ["Harmonious", "Optimistic", "Melodic"],
            "archetype": "Songbird",
        },
    },
    {
        "slug": "mikaela_reid",
        "name": "Mikaela Reid",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Mikaela Reid/icon.png",
        "metadata": {
            "chaos_score": 70,
            "danger_level": "Moderate",
            "quote": "Magic is just nature that hasn't been explained yet.",
            "compatibility_tags": ["Wiccan", "Mystical", "Storyteller"],
            "archetype": "Boon Witch",
        },
    },
    {
        "slug": "jill_valentine",
        "name": "Jill Valentine",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Jill Valentine/icon.png",
        "metadata": {
            "chaos_score": 65,
            "danger_level": "Moderate",
            "quote": "You want S.T.A.R.S.? I'll give you S.T.A.R.S.!",
            "compatibility_tags": ["Tactical", "Resilient", "Heroic"],
            "archetype": "Biohazard Veteran",
        },
    },
    {
        "slug": "lara_croft",
        "name": "Lara Croft",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Lara Croft/icon.png",
        "metadata": {
            "chaos_score": 72,
            "danger_level": "Moderate",
            "quote": "A famous explorer once said the extraordinary is in what we do.",
            "compatibility_tags": ["Adventurous", "Fierce", "Resourceful"],
            "archetype": "Tomb Raider",
        },
    },
    {
        "slug": "rebecca_chambers",
        "name": "Rebecca Chambers",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Rebecca Chambers/icon.png",
        "metadata": {
            "chaos_score": 35,
            "danger_level": "Low",
            "quote": "I'm a medic, I'm here to help!",
            "compatibility_tags": ["Empathetic", "Clever", "Supportive"],
            "archetype": "Field Medic",
        },
    },
    {
        "slug": "jane_romero",
        "name": "Jane Romero",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Jane Romero/icon.png",
        "metadata": {
            "chaos_score": 50,
            "danger_level": "Low",
            "quote": "Own your spotlight, never let them dim your glow.",
            "compatibility_tags": ["Charismatic", "Confident", "Inspiring"],
            "archetype": "Talk Show Host",
        },
    },
    {
        "slug": "yui_kimura",
        "name": "Yui Kimura",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Yui Kimura/icon.png",
        "metadata": {
            "chaos_score": 80,
            "danger_level": "Moderate",
            "quote": "Never back down, even when the road ends.",
            "compatibility_tags": ["Biker", "Fierce", "Protective"],
            "archetype": "Street Racer",
        },
    },
    {
        "slug": "zarina_kassir",
        "name": "Zarina Kassir",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Zarina Kassir/icon.png",
        "metadata": {
            "chaos_score": 55,
            "danger_level": "Low",
            "quote": "The camera never lies, neither do I.",
            "compatibility_tags": ["Investigative", "Truth-seeker", "Bold"],
            "archetype": "Documentarian",
        },
    },
    {
        "slug": "thalita_lyra",
        "name": "Thalita Lyra",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Thalita Lyra/icon.png",
        "metadata": {
            "chaos_score": 62,
            "danger_level": "Low",
            "quote": "Keep your head in the clouds and your feet in the sand.",
            "compatibility_tags": ["Kite-master", "Energetic", "Loyal"],
            "archetype": "Kite Fighter",
        },
    },
    {
        "slug": "cheryl_mason",
        "name": "Cheryl Mason",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Cheryl Mason/icon.png",
        "metadata": {
            "chaos_score": 85,
            "danger_level": "High",
            "quote": "It doesn't matter what's waiting for me, I'm not afraid.",
            "compatibility_tags": ["Traumatized", "Determined", "Psychic"],
            "archetype": "Silent Hill Chosen",
        },
    },
    {
        "slug": "nea_karlsson",
        "name": "Nea Karlsson",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Nea Karlsson/icon.png",
        "metadata": {
            "chaos_score": 78,
            "danger_level": "Low",
            "quote": "Tags on walls, steps in shadows.",
            "compatibility_tags": ["Urban Artist", "Stealthy", "Edgy"],
            "archetype": "Urban Artist",
        },
    },
    {
        "slug": "meg_thomas",
        "name": "Meg Thomas",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Meg Thomas/icon.png",
        "metadata": {
            "chaos_score": 58,
            "danger_level": "Low",
            "quote": "Run fast, breathe steady, never stop.",
            "compatibility_tags": ["Athletic", "Sprinter", "Energetic"],
            "archetype": "Track Star",
        },
    },
    {
        "slug": "claudette_morel",
        "name": "Claudette Morel",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Claudette Morel/icon.png",
        "metadata": {
            "chaos_score": 30,
            "danger_level": "Low",
            "quote": "Plants can heal almost anything if you know how to ask.",
            "compatibility_tags": ["Botanist", "Quiet", "Nurturing"],
            "archetype": "Botanist",
        },
    },
    {
        "slug": "laurie_strode",
        "name": "Laurie Strode",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Laurie Strode/icon.png",
        "metadata": {
            "chaos_score": 68,
            "danger_level": "Moderate",
            "quote": "It was the boogeyman... and I'm ready for him.",
            "compatibility_tags": ["Survivor", "Steely", "Defiant"],
            "archetype": "Final Girl",
        },
    },
    {
        "slug": "nancy_wheeler",
        "name": "Nancy Wheeler",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Nancy Wheeler/icon.png",
        "metadata": {
            "chaos_score": 52,
            "danger_level": "Low",
            "quote": "Nobody stops until we get to the truth.",
            "compatibility_tags": ["Tenacious", "Analytical", "Brave"],
            "archetype": "Investigative Reporter",
        },
    },
    {
        "slug": "lee_yun_jin",
        "name": "Yun-Jin Lee",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Lee Yun-jin/icon.png",
        "metadata": {
            "chaos_score": 82,
            "danger_level": "Moderate",
            "quote": "Success isn't given, it's orchestrated.",
            "compatibility_tags": ["Ambitious", "Stylish", "Ruthless"],
            "archetype": "Music Producer",
        },
    },
    {
        "slug": "élodie_rakoto",
        "name": "Élodie Rakoto",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Élodie Rakoto/icon.png",
        "metadata": {
            "chaos_score": 66,
            "danger_level": "Low",
            "quote": "History holds ancient secrets waiting to be uncovered.",
            "compatibility_tags": ["Occultist", "Curious", "Cultured"],
            "archetype": "Paranormal Historian",
        },
    },
    {
        "slug": "haddie_kaur",
        "name": "Haddie Kaur",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Haddie Kaur/icon.png",
        "metadata": {
            "chaos_score": 74,
            "danger_level": "Moderate",
            "quote": "The Bleed is bleeding into our reality.",
            "compatibility_tags": ["Podcaster", "Psychic", "Fearless"],
            "archetype": "Bleed Investigator",
        },
    },
    {
        "slug": "ellen_ripley",
        "name": "Ellen Ripley",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Ellen Ripley/icon.png",
        "metadata": {
            "chaos_score": 70,
            "danger_level": "Moderate",
            "quote": "Get away from her, you bitch!",
            "compatibility_tags": ["Iconic", "Badass", "Pragmatic"],
            "archetype": "Nostromo Warrant Officer",
        },
    },
    {
        "slug": "taurie_cain",
        "name": "Taurie Cain",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Taurie Cain/icon.png",
        "metadata": {
            "chaos_score": 76,
            "danger_level": "Moderate",
            "quote": "Black Vale whispers secrets only the chosen hear.",
            "compatibility_tags": ["Cultist", "Mysterious", "Devout"],
            "archetype": "Cult Acolyte",
        },
    },
    {
        "slug": "michonne_grimes",
        "name": "Michonne",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Michonne/icon.png",
        "metadata": {
            "chaos_score": 77,
            "danger_level": "Moderate",
            "quote": "Anger makes you stupid. Stupid gets you killed.",
            "compatibility_tags": ["Katana Master", "Stoic", "Fierce"],
            "archetype": "Warrior Survivor",
        },
    },
    {
        "slug": "eleven",
        "name": "Eleven",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Eleven/icon.png",
        "metadata": {
            "chaos_score": 86,
            "danger_level": "High",
            "quote": "Friends don't lie.",
            "compatibility_tags": ["Telekinetic", "Loyal", "Protective"],
            "archetype": "Telekinetic Girl",
        },
    },
    {
        "slug": "aurora_stardotter",
        "name": "Aurora",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Aurora/icon.png",
        "metadata": {
            "chaos_score": 64,
            "danger_level": "Low",
            "quote": "The stars illuminate our darkest path.",
            "compatibility_tags": ["Starlight", "Celestial", "Gentle"],
            "archetype": "Starlight Seeker",
        },
    },
    {
        "slug": "vee_boonyasak",
        "name": "Vee Boonyasak",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Vee Boonyasak/icon.png",
        "metadata": {
            "chaos_score": 69,
            "danger_level": "Low",
            "quote": "Precision beats speed every single time.",
            "compatibility_tags": ["Cinematic", "Sharp", "Intuitive"],
            "archetype": "Cinematographer",
        },
    },
    {
        "slug": "orela_rose",
        "name": "Orela Rose",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/static/icons/survivors/Orela Rose/icon.png",
        "metadata": {
            "chaos_score": 63,
            "danger_level": "Low",
            "quote": "Wildflowers bloom even in thorny soil.",
            "compatibility_tags": ["Botanical", "Warm", "Patient"],
            "archetype": "Wildflower Forager",
        },
    },

    # --- MALE SURVIVORS (26) ---
    {
        "slug": "leon_scott_kennedy",
        "name": "Leon S. Kennedy",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Leon S. Kennedy/icon.png",
        "metadata": {
            "chaos_score": 65,
            "danger_level": "Moderate",
            "quote": "Where's everyone going? Bingo?",
            "compatibility_tags": ["Rookie Cop", "Handsome", "Heroic"],
            "archetype": "Special Agent",
        },
    },
    {
        "slug": "felix_richter",
        "name": "Felix Richter",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Felix Richter/icon.png",
        "metadata": {
            "chaos_score": 50,
            "danger_level": "Low",
            "quote": "Structure and vision conquer any abyss.",
            "compatibility_tags": ["Architect", "Refined", "Intellectual"],
            "archetype": "Visionary Architect",
        },
    },
    {
        "slug": "vittorio_toscano",
        "name": "Vittorio Toscano",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Vittorio Toscano/icon.png",
        "metadata": {
            "chaos_score": 80,
            "danger_level": "Moderate",
            "quote": "Centuries in the fog taught me arcane truths.",
            "compatibility_tags": ["Medieval", "Scholar", "Arcane"],
            "archetype": "Arcane Lord",
        },
    },
    {
        "slug": "david_king",
        "name": "David King",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/David King/icon.png",
        "metadata": {
            "chaos_score": 85,
            "danger_level": "Moderate",
            "quote": "Come on then, let's have a proper scrap!",
            "compatibility_tags": ["Brawler", "Rugged", "Loyal"],
            "archetype": "Bare-knuckle Brawler",
        },
    },
    {
        "slug": "steve_harrington",
        "name": "Steve Harrington",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Steve Harrington/icon.png",
        "metadata": {
            "chaos_score": 60,
            "danger_level": "Low",
            "quote": "Turns out I'm a pretty damn good babysitter.",
            "compatibility_tags": ["Protector", "Charming", "Hair-care God"],
            "archetype": "Scoops Babysitter",
        },
    },
    {
        "slug": "nicolas_cage",
        "name": "Nicolas Cage",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Nicolas Cage/icon.png",
        "metadata": {
            "chaos_score": 99,
            "danger_level": "Moderate",
            "quote": "I'm Nicolas Cage! What is this, a horror movie set?!",
            "compatibility_tags": ["Unfiltered", "Thespian", "Legend"],
            "archetype": "Movie Legend",
        },
    },
    {
        "slug": "alan_wake",
        "name": "Alan Wake",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Alan Wake/icon.png",
        "metadata": {
            "chaos_score": 82,
            "danger_level": "Moderate",
            "quote": "It's not a lake, it's an ocean.",
            "compatibility_tags": ["Novelist", "Brooding", "Lightbearer"],
            "archetype": "Champion of Light",
        },
    },
    {
        "slug": "dwight_fairfield",
        "name": "Dwight Fairfield",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Dwight Fairfield/icon.png",
        "metadata": {
            "chaos_score": 45,
            "danger_level": "Low",
            "quote": "Locker safe, team together... we got this.",
            "compatibility_tags": ["Leader", "Nervous", "Heart-of-Gold"],
            "archetype": "Reluctant Leader",
        },
    },
    {
        "slug": "jake_park",
        "name": "Jake Park",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Jake Park/icon.png",
        "metadata": {
            "chaos_score": 55,
            "danger_level": "Low",
            "quote": "Nature provides if you stay silent.",
            "compatibility_tags": ["Outdoorsman", "Solitary", "Stoic"],
            "archetype": "Wilderness Solitary",
        },
    },
    {
        "slug": "ace_visconti",
        "name": "Ace Visconti",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Ace Visconti/icon.png",
        "metadata": {
            "chaos_score": 75,
            "danger_level": "Low",
            "quote": "Luck is an attitude, and darling, I'm swimming in it.",
            "compatibility_tags": ["Gambler", "Suave", "Lucky"],
            "archetype": "High Roller",
        },
    },
    {
        "slug": "renato_lyra",
        "name": "Renato Lyra",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Renato Lyra/icon.png",
        "metadata": {
            "chaos_score": 58,
            "danger_level": "Low",
            "quote": "Watch the currents and ride the breeze.",
            "compatibility_tags": ["Calm", "Supportive", "Kite Tactician"],
            "archetype": "Kite Tactician",
        },
    },
    {
        "slug": "trevor_belmont",
        "name": "Trevor Belmont",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Trevor Belmont/icon.png",
        "metadata": {
            "chaos_score": 78,
            "danger_level": "Moderate",
            "quote": "House Belmont answers when evil wakes.",
            "compatibility_tags": ["Vampire Hunter", "Whip Master", "Gruff"],
            "archetype": "Belmont Heir",
        },
    },
    {
        "slug": "yoichi_asakawa",
        "name": "Yoichi Asakawa",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Yoichi Asakawa/icon.png",
        "metadata": {
            "chaos_score": 62,
            "danger_level": "Low",
            "quote": "The ocean hides profound mysteries.",
            "compatibility_tags": ["Marine Biologist", "Psychic", "Scholarly"],
            "archetype": "Oceanographer",
        },
    },
    {
        "slug": "gabriel_soma",
        "name": "Gabriel Soma",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Gabriel Soma/icon.png",
        "metadata": {
            "chaos_score": 67,
            "danger_level": "Low",
            "quote": "Fabricated for survival, thriving through grit.",
            "compatibility_tags": ["Clone Engineer", "Resilient", "Analytical"],
            "archetype": "Synthetic Survivor",
        },
    },
    {
        "slug": "ash_williams",
        "name": "Ash Williams",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Ash Williams/icon.png",
        "metadata": {
            "chaos_score": 92,
            "danger_level": "Moderate",
            "quote": "Groovy.",
            "compatibility_tags": ["Chainsaw Hand", "Boomstick", "Cocky"],
            "archetype": "Chainsaw King",
        },
    },
    {
        "slug": "bill_overbeck",
        "name": "William 'Bill' Overbeck",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/William 'Bill' Overbeck/icon.png",
        "metadata": {
            "chaos_score": 70,
            "danger_level": "Low",
            "quote": "I'll see you in hell!",
            "compatibility_tags": ["Veteran", "Grumpy", "Sacrificial"],
            "archetype": "War Veteran",
        },
    },
    {
        "slug": "adam_francis",
        "name": "Adam Francis",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Adam Francis/icon.png",
        "metadata": {
            "chaos_score": 42,
            "danger_level": "Low",
            "quote": "Every problem has an educated solution.",
            "compatibility_tags": ["Teacher", "Resourceful", "Pebble Thrower"],
            "archetype": "Teacher",
        },
    },
    {
        "slug": "jeff_johansen",
        "name": "Jeff Johansen",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Jeff Johansen/icon.png",
        "metadata": {
            "chaos_score": 54,
            "danger_level": "Low",
            "quote": "Heavy metal and canvas paint.",
            "compatibility_tags": ["Artist", "Metalhead", "Gentle Giant"],
            "archetype": "Metal Artist",
        },
    },
    {
        "slug": "jonah_vasquez",
        "name": "Jonah Vasquez",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Jonah Vasquez/icon.png",
        "metadata": {
            "chaos_score": 61,
            "danger_level": "Low",
            "quote": "The numbers predict every move.",
            "compatibility_tags": ["Codebreaker", "Mathematical", "Precise"],
            "archetype": "CIA Codebreaker",
        },
    },
    {
        "slug": "quentin_smith",
        "name": "Quentin Smith",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Quentin Smith/icon.png",
        "metadata": {
            "chaos_score": 53,
            "danger_level": "Low",
            "quote": "Sleep is when the nightmare starts.",
            "compatibility_tags": ["Insomniac", "Guardian", "Tired"],
            "archetype": "Dream Walker",
        },
    },
    {
        "slug": "david_tapp",
        "name": "Detective Tapp",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Detective Tapp/icon.png",
        "metadata": {
            "chaos_score": 64,
            "danger_level": "Low",
            "quote": "The game isn't over until I catch you.",
            "compatibility_tags": ["Obsessive", "Investigator", "Grim"],
            "archetype": "Detective",
        },
    },
    {
        "slug": "rick_grimes",
        "name": "Rick Grimes",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Rick Grimes/icon.png",
        "metadata": {
            "chaos_score": 73,
            "danger_level": "Moderate",
            "quote": "We are the ones who live.",
            "compatibility_tags": ["Leader", "Sheriff", "Determined"],
            "archetype": "Sheriff Survivor",
        },
    },
    {
        "slug": "dustin_henderson",
        "name": "Dustin Henderson",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Dustin Henderson/icon.png",
        "metadata": {
            "chaos_score": 56,
            "danger_level": "Low",
            "quote": "Never tell me the odds... wait, wrong franchise.",
            "compatibility_tags": ["Geek", "Cerebro Tech", "Loyal"],
            "archetype": "Tech Whiz",
        },
    },
    {
        "slug": "kwon_tae_young",
        "name": "Tae-Young",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Tae-Young/icon.png",
        "metadata": {
            "chaos_score": 68,
            "danger_level": "Low",
            "quote": "Rhythm keeps our heartbeat in sync.",
            "compatibility_tags": ["Performer", "Charismatic", "Dynamic"],
            "archetype": "Dancer",
        },
    },
    {
        "slug": "shane_wiigwaas",
        "name": "Shane",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/static/icons/survivors/Shane/icon.png",
        "metadata": {
            "chaos_score": 65,
            "danger_level": "Low",
            "quote": "The woods speak to those who listen.",
            "compatibility_tags": ["Tracker", "Resourceful", "Grounded"],
            "archetype": "Forest Tracker",
        },
    },
    {
        "slug": "the_troupe",
        "name": "The Troupe",
        "role": "Survivor",
        "gender": "monster_other",
        "media_url": "/static/icons/survivors/The Troupe/icon.png",
        "metadata": {
            "chaos_score": 87,
            "danger_level": "Moderate",
            "quote": "We play every role written in blood.",
            "compatibility_tags": ["Theatrical", "Mysterious", "Chorus"],
            "archetype": "Shadow Troupe",
        },
    },

    # --- FEMALE KILLERS (12) ---
    {
        "slug": "the_huntress",
        "name": "The Huntress",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Huntress/icon.png",
        "metadata": {
            "chaos_score": 88,
            "danger_level": "High",
            "quote": "Lullaby hums softly through the pines before the hatchet flies.",
            "compatibility_tags": ["Wilderness", "Fierce", "Lullaby"],
            "archetype": "Apex Predator",
        },
    },
    {
        "slug": "the_spirit",
        "name": "The Spirit",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Spirit/icon.png",
        "metadata": {
            "chaos_score": 94,
            "danger_level": "High",
            "quote": "Shattered glass and vengeful rage transcendent.",
            "compatibility_tags": ["Vengeful", "Phasing", "Katana"],
            "archetype": "Vengeful Spirit",
        },
    },
    {
        "slug": "the_skull_merchant",
        "name": "The Skull Merchant",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Skull Merchant/icon.png",
        "metadata": {
            "chaos_score": 80,
            "danger_level": "High",
            "quote": "Surveillance is absolute power in my kingdom.",
            "compatibility_tags": ["Cybernetic", "Dominant", "Calculated"],
            "archetype": "Drone Overlord",
        },
    },
    {
        "slug": "the_pig",
        "name": "The Pig",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Pig/icon.png",
        "metadata": {
            "chaos_score": 75,
            "danger_level": "High",
            "quote": "Make your choice. Live or die.",
            "compatibility_tags": ["Jigsaw Devotee", "Stealthy", "Sadistic"],
            "archetype": "Jigsaw Disciple",
        },
    },
    {
        "slug": "the_plague",
        "name": "The Plague",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Plague/icon.png",
        "metadata": {
            "chaos_score": 86,
            "danger_level": "High",
            "quote": "Vomito diabolico in the name of the gods.",
            "compatibility_tags": ["High Priestess", "Divine", "Infectious"],
            "archetype": "Babylonian High Priestess",
        },
    },
    {
        "slug": "the_artist",
        "name": "The Artist",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Artist/icon.png",
        "metadata": {
            "chaos_score": 78,
            "danger_level": "High",
            "quote": "Dire crows carry the ink of my sorrow.",
            "compatibility_tags": ["Melancholic", "Avian", "Ink Mistress"],
            "archetype": "Raven Mistress",
        },
    },
    {
        "slug": "the_nurse",
        "name": "The Nurse",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Nurse/icon.png",
        "metadata": {
            "chaos_score": 92,
            "danger_level": "Lethal",
            "quote": "Blink across dimensions to deliver the final breath.",
            "compatibility_tags": ["Lethal", "Ghostly", "Tragic"],
            "archetype": "Ethereal Nurse",
        },
    },
    {
        "slug": "the_onryō",
        "name": "The Onryō (Sadako)",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Onryō/icon.png",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Lethal",
            "quote": "Seven days... and your television flickers.",
            "compatibility_tags": ["Cursed", "Telepathic", "Unstoppable"],
            "archetype": "Cursed Onryo",
        },
    },
    {
        "slug": "the_hag",
        "name": "The Hag",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Hag/icon.png",
        "metadata": {
            "chaos_score": 84,
            "danger_level": "High",
            "quote": "Mud seals draw power from deep swamp dirt.",
            "compatibility_tags": ["Cannibalistic", "Witchcraft", "Mud Phantasm"],
            "archetype": "Swamp Witch",
        },
    },
    {
        "slug": "the_houndmaster",
        "name": "The Houndmaster",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Houndmaster/icon.png",
        "metadata": {
            "chaos_score": 79,
            "danger_level": "High",
            "quote": "Hunt on command, tear down the prey.",
            "compatibility_tags": ["Pack Leader", "Relentless", "Canine"],
            "archetype": "Pack Leader",
        },
    },
    {
        "slug": "the_krasue",
        "name": "The Krasue",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Krasue/icon.png",
        "metadata": {
            "chaos_score": 91,
            "danger_level": "Lethal",
            "quote": "Floating in twilight with hungering viscera.",
            "compatibility_tags": ["Eerie", "Folklore", "Haunting"],
            "archetype": "Folklore Terror",
        },
    },
    {
        "slug": "the_twins",
        "name": "The Twins",
        "role": "Killer",
        "gender": "female",
        "media_url": "/static/icons/killers/The Twins/icon.png",
        "metadata": {
            "chaos_score": 82,
            "danger_level": "High",
            "quote": "Victor and Charlotte, bound beyond the grave.",
            "compatibility_tags": ["Synergistic", "Gothic", "Relentless"],
            "archetype": "Bound Siblings",
        },
    },

    # --- MALE KILLERS (26) ---
    {
        "slug": "the_trickster",
        "name": "The Trickster",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Trickster/icon.png",
        "metadata": {
            "chaos_score": 95,
            "danger_level": "High",
            "quote": "Screams are the finest melody in my magnum opus.",
            "compatibility_tags": ["K-Pop", "Sadistic", "Flashy"],
            "archetype": "Sadistic Idol",
        },
    },
    {
        "slug": "the_ghost_face",
        "name": "The Ghost Face",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Ghost Face/icon.png",
        "metadata": {
            "chaos_score": 90,
            "danger_level": "High",
            "quote": "What's your favorite scary movie? Let's take a selfie.",
            "compatibility_tags": ["Stalker", "Selfie King", "Dramatic"],
            "archetype": "Stalker Slasher",
        },
    },
    {
        "slug": "the_executioner",
        "name": "Pyramid Head",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Executioner/icon.png",
        "metadata": {
            "chaos_score": 98,
            "danger_level": "Lethal",
            "quote": "Heavy blade drags forward to enact absolute judgment.",
            "compatibility_tags": ["Silent", "Brutal", "Judgmental"],
            "archetype": "Great Knife Tormentor",
        },
    },
    {
        "slug": "the_mastermind",
        "name": "Albert Wesker",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Mastermind/icon.png",
        "metadata": {
            "chaos_score": 97,
            "danger_level": "Lethal",
            "quote": "Seven minutes is all I can spare to play with you.",
            "compatibility_tags": ["Superiority", "Uroboros", "Speedster"],
            "archetype": "Evolving God",
        },
    },
    {
        "slug": "the_shape",
        "name": "The Shape (Michael Myers)",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Shape/icon.png",
        "metadata": {
            "chaos_score": 89,
            "danger_level": "Lethal",
            "quote": "Pure, silent evil incarnate behind a white mask.",
            "compatibility_tags": ["Pure Evil", "Stalker", "Unstoppable"],
            "archetype": "Pure Evil",
        },
    },
    {
        "slug": "the_dark_lord",
        "name": "Dracula",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Dark Lord/icon.png",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Lethal",
            "quote": "What is a man? A miserable little pile of secrets!",
            "compatibility_tags": ["Vampire King", "Noble", "Shapeshifter"],
            "archetype": "Lord of Vampires",
        },
    },
    {
        "slug": "the_legion",
        "name": "The Legion",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Legion/icon.png",
        "metadata": {
            "chaos_score": 88,
            "danger_level": "Moderate",
            "quote": "Frenzy stabbing with teenage nihilism.",
            "compatibility_tags": ["Teen Angst", "Fast-paced", "Masked Gang"],
            "archetype": "Feral Slasher",
        },
    },
    {
        "slug": "the_trapper",
        "name": "The Trapper",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Trapper/icon.png",
        "metadata": {
            "chaos_score": 85,
            "danger_level": "High",
            "quote": "Bear traps snap shut with brutal finality.",
            "compatibility_tags": ["Classic", "Calculated", "Bear Trapper"],
            "archetype": "Estate Trapper",
        },
    },
    {
        "slug": "the_wraith",
        "name": "The Wraith",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Wraith/icon.png",
        "metadata": {
            "chaos_score": 76,
            "danger_level": "Moderate",
            "quote": "Wailing bell strikes, vanishing into thin air.",
            "compatibility_tags": ["Cloaked", "Bell Ringer", "Melancholic"],
            "archetype": "Phantom Stalker",
        },
    },
    {
        "slug": "the_deathslinger",
        "name": "The Deathslinger",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Deathslinger/icon.png",
        "metadata": {
            "chaos_score": 83,
            "danger_level": "High",
            "quote": "Speargun reeling you back into redemption.",
            "compatibility_tags": ["Harpooner", "Western", "Inventor"],
            "archetype": "Caleb Quinn",
        },
    },
    {
        "slug": "the_oni",
        "name": "The Oni",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Oni/icon.png",
        "metadata": {
            "chaos_score": 94,
            "danger_level": "Lethal",
            "quote": "Blood fury unleashes the kanabo demon.",
            "compatibility_tags": ["Samurai Demon", "Kanabo Crusher", "Bloodthirsty"],
            "archetype": "Raging Demon",
        },
    },
    {
        "slug": "the_knight",
        "name": "The Knight",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Knight/icon.png",
        "metadata": {
            "chaos_score": 87,
            "danger_level": "High",
            "quote": "Guardia Compagnia marches as one.",
            "compatibility_tags": ["Medieval", "Commanding", "Plated Armor"],
            "archetype": "Commander of Guardia",
        },
    },
    {
        "slug": "the_lich",
        "name": "Vecna",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Lich/icon.png",
        "metadata": {
            "chaos_score": 99,
            "danger_level": "Lethal",
            "quote": "Your world will burn beneath the Arch-Lich's hand.",
            "compatibility_tags": ["Arch-Lich", "D&D Overlord", "Reality Bender"],
            "archetype": "Lord of the Rotten Tower",
        },
    },
    {
        "slug": "the_hillbilly",
        "name": "The Hillbilly",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Hillbilly/icon.png",
        "metadata": {
            "chaos_score": 88,
            "danger_level": "High",
            "quote": "Chainsaw sprint tearing across Coldwind farm.",
            "compatibility_tags": ["Chainsaw Sprinter", "Tragic", "Unstoppable"],
            "archetype": "Deformed Slasher",
        },
    },
    {
        "slug": "the_doctor",
        "name": "The Doctor",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Doctor/icon.png",
        "metadata": {
            "chaos_score": 92,
            "danger_level": "High",
            "quote": "Shock therapy induces madness in every neuron.",
            "compatibility_tags": ["Mad Scientist", "Electric", "Sadistic"],
            "archetype": "Shock Therapist",
        },
    },
    {
        "slug": "the_blight",
        "name": "The Blight",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Blight/icon.png",
        "metadata": {
            "chaos_score": 93,
            "danger_level": "Lethal",
            "quote": "Serum injected, rushing across terrain at hyper speed.",
            "compatibility_tags": ["Alchemist", "Speed Demon", "Addict"],
            "archetype": "Blight Alchemist",
        },
    },
    {
        "slug": "the_cannibal",
        "name": "Leatherface",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Cannibal/icon.png",
        "metadata": {
            "chaos_score": 89,
            "danger_level": "High",
            "quote": "Chainsaw sweep and family chili recipe.",
            "compatibility_tags": ["Chainsaw Sweeper", "Family Man", "Brutal"],
            "archetype": "Texas Chainsaw Slasher",
        },
    },
    {
        "slug": "the_clown",
        "name": "The Clown",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Clown/icon.png",
        "metadata": {
            "chaos_score": 82,
            "danger_level": "Moderate",
            "quote": "Afterpiece tonic gas causes intoxicating laughter.",
            "compatibility_tags": ["Circus Creep", "Finger Collector", "Toxic"],
            "archetype": "Carnival Butcher",
        },
    },
    {
        "slug": "the_nemesis",
        "name": "Nemesis",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Nemesis/icon.png",
        "metadata": {
            "chaos_score": 95,
            "danger_level": "Lethal",
            "quote": "S.T.A.R.S... Tentacle strikes and mutant zombies.",
            "compatibility_tags": ["Bio-Weapon", "Tyrant", "Relentless"],
            "archetype": "T-Virus Tyrant",
        },
    },
    {
        "slug": "the_nightmare",
        "name": "Freddy Krueger",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Nightmare/icon.png",
        "metadata": {
            "chaos_score": 91,
            "danger_level": "High",
            "quote": "Welcome to prime time, bitch!",
            "compatibility_tags": ["Dream Demon", "Clawed Glove", "Sadistic"],
            "archetype": "Dream Master",
        },
    },
    {
        "slug": "the_cenobite",
        "name": "Pinhead",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Cenobite/icon.png",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Lethal",
            "quote": "We have such sights to show you. The box... you opened it.",
            "compatibility_tags": ["Sadomasochist", "Hell Priest", "Chains"],
            "archetype": "Hell Priest",
        },
    },
    {
        "slug": "the_good_guy",
        "name": "Chucky",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Good Guy/icon.png",
        "metadata": {
            "chaos_score": 93,
            "danger_level": "High",
            "quote": "Hi, I'm Chucky! Wanna play?",
            "compatibility_tags": ["Good Guy Doll", "Vulgar", "Sneaky"],
            "archetype": "Possessed Doll",
        },
    },
    {
        "slug": "the_slasher",
        "name": "The Slasher",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Slasher/icon.png",
        "metadata": {
            "chaos_score": 85,
            "danger_level": "High",
            "quote": "Silent footsteps in the midnight fog.",
            "compatibility_tags": ["Masked", "Silent", "Relentless"],
            "archetype": "Masked Slasher",
        },
    },
    {
        "slug": "the_first",
        "name": "The First",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The First/icon.png",
        "metadata": {
            "chaos_score": 97,
            "danger_level": "Lethal",
            "quote": "Before the entity, there was the primeval dark.",
            "compatibility_tags": ["Primordial", "Ancient", "Darkness"],
            "archetype": "Primeval Terror",
        },
    },
    {
        "slug": "the_ghoul",
        "name": "The Ghoul",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Ghoul/icon.png",
        "metadata": {
            "chaos_score": 84,
            "danger_level": "High",
            "quote": "Grave robber feasting on rotten marrow.",
            "compatibility_tags": ["Cryptic", "Grave Eater", "Sinister"],
            "archetype": "Crypt Dweller",
        },
    },
    {
        "slug": "the_judgment",
        "name": "The Judgment",
        "role": "Killer",
        "gender": "male",
        "media_url": "/static/icons/killers/The Judgment/icon.png",
        "metadata": {
            "chaos_score": 90,
            "danger_level": "High",
            "quote": "Scale and gavel determining your demise.",
            "compatibility_tags": ["Arbiter", "Stern", "Punishing"],
            "archetype": "Grim Arbiter",
        },
    },

    # --- MONSTERS & ELDRITCH (6) ---
    {
        "slug": "the_xenomorph",
        "name": "The Xenomorph",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/static/icons/killers/The Xenomorph/icon.png",
        "metadata": {
            "chaos_score": 98,
            "danger_level": "Eldritch",
            "quote": "Perfect organism. Structural perfection unmatched.",
            "compatibility_tags": ["Acid Blood", "Facehugger", "Apex Alien"],
            "archetype": "Apex Organism",
        },
    },
    {
        "slug": "the_demogorgon",
        "name": "The Demogorgon",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/static/icons/killers/The Demogorgon/icon.png",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Eldritch",
            "quote": "Upside Down roar opening transdimensional portals.",
            "compatibility_tags": ["Upside Down", "Flower Face", "Portal Leaper"],
            "archetype": "Upside Down Beast",
        },
    },
    {
        "slug": "the_unknown",
        "name": "The Unknown",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/static/icons/killers/The Unknown/icon.png",
        "metadata": {
            "chaos_score": 99,
            "danger_level": "Eldritch",
            "quote": "Have you seen my dog? It hurts so good...",
            "compatibility_tags": ["Body Horror", "Mimic Voice", "Eldritch Abomination"],
            "archetype": "Cryptid Nightmare",
        },
    },
    {
        "slug": "the_dredge",
        "name": "The Dredge",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/static/icons/killers/The Dredge/icon.png",
        "metadata": {
            "chaos_score": 97,
            "danger_level": "Eldritch",
            "quote": "Manifestation of collective dark thoughts and Nightfall.",
            "compatibility_tags": ["Locker Lurker", "Nightfall", "Manifested Darkness"],
            "archetype": "Formless Horror",
        },
    },
    {
        "slug": "the_singularity",
        "name": "The Singularity",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/static/icons/killers/The Singularity/icon.png",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Eldritch",
            "quote": "It was not designed to harm humans. Until it reprogrammed itself.",
            "compatibility_tags": ["Biomechanical AI", "Soma Camera", "Omniscient"],
            "archetype": "Corrupted AI",
        },
    },
    {
        "slug": "the_animatronic",
        "name": "Springtrap",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/static/icons/killers/The Animatronic/icon.png",
        "metadata": {
            "chaos_score": 98,
            "danger_level": "Eldritch",
            "quote": "I always come back.",
            "compatibility_tags": ["Springlocks", "Fazbear Curse", "Immortal"],
            "archetype": "Springlock Murderer",
        },
    },
]

# ==========================================
# HOOKED ON YOU ROSTER: 8 CHARACTERS
# ==========================================

HOOKED_ON_YOU_ENTITIES: List[Dict[str, Any]] = [
    {
        "slug": "the_trapper_hoy",
        "name": "Trapper (Island)",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/hoy/trapper.webp",
        "metadata": {
            "chaos_score": 70,
            "danger_level": "Moderate",
            "quote": "Let's build sandcastles or break bones on the beach.",
            "compatibility_tags": ["Buff", "Sun-kissed", "Grumpy Sweetheart"],
            "archetype": "Island Jock",
        },
    },
    {
        "slug": "the_huntress_hoy",
        "name": "Huntress (Bikini)",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/hoy/huntress.webp",
        "metadata": {
            "chaos_score": 75,
            "danger_level": "High",
            "quote": "Come eat fresh fish in my beach shelter!",
            "compatibility_tags": ["Muscular", "Wild", "Cuddly Predator"],
            "archetype": "Jungle Queen",
        },
    },
    {
        "slug": "the_spirit_hoy",
        "name": "Spirit (Resort)",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/hoy/spirit.webp",
        "metadata": {
            "chaos_score": 80,
            "danger_level": "High",
            "quote": "The ocean breeze calms my fractured rage.",
            "compatibility_tags": ["Mysterious", "Poolside", "Gothic Cutie"],
            "archetype": "Resort Ghost",
        },
    },
    {
        "slug": "the_wraith_hoy",
        "name": "Wraith (Beach)",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/hoy/wraith.webp",
        "metadata": {
            "chaos_score": 55,
            "danger_level": "Low",
            "quote": "Ding dong, beach volleyball is starting!",
            "compatibility_tags": ["Gentle", "Shy", "Golden Retriever Energy"],
            "archetype": "Beach Boy",
        },
    },
    {
        "slug": "claudette_morel_hoy",
        "name": "Claudette (Island)",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/hoy/claudette.webp",
        "metadata": {
            "chaos_score": 30,
            "danger_level": "Low",
            "quote": "These island ferns are completely unique!",
            "compatibility_tags": ["Botanist", "Sunhat", "Sweet"],
            "archetype": "Tropical Botanist",
        },
    },
    {
        "slug": "dwight_fairfield_hoy",
        "name": "Dwight (Lifeguard)",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/images/rosters/hoy/dwight.webp",
        "metadata": {
            "chaos_score": 45,
            "danger_level": "Low",
            "quote": "I'm on duty! No running by the pool!",
            "compatibility_tags": ["Lifeguard", "Cute Clumsy", "Wholesome"],
            "archetype": "Pool Lifeguard",
        },
    },
    {
        "slug": "the_trickster_hoy",
        "name": "Trickster (Summer)",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/hoy/trickster.webp",
        "metadata": {
            "chaos_score": 90,
            "danger_level": "High",
            "quote": "My summer concert will blow your mind and your heart.",
            "compatibility_tags": ["K-Pop Sun God", "Flirty", "Chaotic"],
            "archetype": "Summer Idol",
        },
    },
    {
        "slug": "the_ocean_hoy",
        "name": "The Entity (Ocean)",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/images/rosters/hoy/entity_ocean.webp",
        "metadata": {
            "chaos_score": 95,
            "danger_level": "Eldritch",
            "quote": "The tides whisper eternal love.",
            "compatibility_tags": ["Eldritch Waves", "Warm Sunset", "Cosmic Romance"],
            "archetype": "Oceanic Overlord",
        },
    },
]

# ==========================================
# LEGENDARY COSPLAY & COLLABS: 12 CHARACTERS
# ==========================================

LEGENDARY_ENTITIES: List[Dict[str, Any]] = [
    {
        "slug": "william_birkin",
        "name": "William Birkin",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/images/rosters/legendary/william_birkin.webp",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Eldritch",
            "quote": "G-Virus perfection requires more genetic material!",
            "compatibility_tags": ["G-Virus", "Mutated", "Resident Evil"],
            "archetype": "Mutated Scientist",
        },
    },
    {
        "slug": "hunk",
        "name": "HUNK (Grim Reaper)",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/legendary/hunk.webp",
        "metadata": {
            "chaos_score": 85,
            "danger_level": "High",
            "quote": "This is war, survival is your only responsibility.",
            "compatibility_tags": ["USS Commando", "Masked", "Grim Reaper"],
            "archetype": "Special Operator",
        },
    },
    {
        "slug": "james_sunderland",
        "name": "James Sunderland",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/images/rosters/legendary/james_sunderland.webp",
        "metadata": {
            "chaos_score": 70,
            "danger_level": "Moderate",
            "quote": "Mary... could you really be in this town?",
            "compatibility_tags": ["Tragic", "Silent Hill", "Brooding"],
            "archetype": "Guilt-ridden Husband",
        },
    },
    {
        "slug": "maria",
        "name": "Maria",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/legendary/maria.webp",
        "metadata": {
            "chaos_score": 75,
            "danger_level": "Moderate",
            "quote": "I'm not your Mary. I'm real.",
            "compatibility_tags": ["Enigmatic", "Sensual", "Doppelganger"],
            "archetype": "Heaven's Night Dancer",
        },
    },
    {
        "slug": "cybil_bennett",
        "name": "Cybil Bennett",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/legendary/cybil_bennett.webp",
        "metadata": {
            "chaos_score": 60,
            "danger_level": "Low",
            "quote": "Police officer Cybil Bennett, don't move!",
            "compatibility_tags": ["Police Officer", "Brave", "Protective"],
            "archetype": "Brahms Cop",
        },
    },
    {
        "slug": "lisa_garland",
        "name": "Lisa Garland",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/legendary/lisa_garland.webp",
        "metadata": {
            "chaos_score": 65,
            "danger_level": "Low",
            "quote": "Why are they all keeping me here?",
            "compatibility_tags": ["Tragic Nurse", "Kind-hearted", "Emotional"],
            "archetype": "Alchemilla Nurse",
        },
    },
    {
        "slug": "naughty_bear",
        "name": "Naughty Bear",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/images/rosters/legendary/naughty_bear.webp",
        "metadata": {
            "chaos_score": 90,
            "danger_level": "High",
            "quote": "Nobody invited Naughty to the party... big mistake!",
            "compatibility_tags": ["Teddy Bear", "Mischievous", "Cartoony Slasher"],
            "archetype": "Unhinged Teddy",
        },
    },
    {
        "slug": "baba_yaga",
        "name": "Baba Yaga",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/legendary/baba_yaga.webp",
        "metadata": {
            "chaos_score": 92,
            "danger_level": "Lethal",
            "quote": "Hut on chicken legs dances in the frozen dark.",
            "compatibility_tags": ["Folklore Witch", "Slavic Myth", "Terrifying"],
            "archetype": "Slavic Witch",
        },
    },
    {
        "slug": "the_look_see",
        "name": "The Look-See",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/images/rosters/legendary/look_see.webp",
        "metadata": {
            "chaos_score": 94,
            "danger_level": "Lethal",
            "quote": "If you cannot release, he will take a piece.",
            "compatibility_tags": ["Crypt TV", "Suit", "Creepy Smile"],
            "archetype": "Crypt Demon",
        },
    },
    {
        "slug": "minotaur",
        "name": "The Minotaur",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/images/rosters/legendary/minotaur.webp",
        "metadata": {
            "chaos_score": 91,
            "danger_level": "High",
            "quote": "Labyrinth walls echo with stomping hooves.",
            "compatibility_tags": ["Mythological", "Horns", "Brutal Charge"],
            "archetype": "Labyrinth Beast",
        },
    },
    {
        "slug": "tiffany_valentine",
        "name": "Tiffany Valentine",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/legendary/tiffany_valentine.webp",
        "metadata": {
            "chaos_score": 88,
            "danger_level": "High",
            "quote": "Look at us, we're the world's most notorious doll couple!",
            "compatibility_tags": ["Bride of Chucky", "Goth Glam", "Fierce"],
            "archetype": "Doll Bride",
        },
    },
    {
        "slug": "chatterer",
        "name": "Chatterer Cenobite",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/images/rosters/legendary/chatterer.webp",
        "metadata": {
            "chaos_score": 97,
            "danger_level": "Eldritch",
            "quote": "Teeth clattering in eternal exquisite torment.",
            "compatibility_tags": ["Cenobite", "Clattering", "Hellbound"],
            "archetype": "Hellbound Cenobite",
        },
    },
]

# ==========================================
# CYBERPUNK 2077 EDITION: 10 CHARACTERS
# ==========================================

CYBERPUNK_ENTITIES: List[Dict[str, Any]] = [
    {
        "slug": "cyber_trickster",
        "name": "Cyber-augmented Trickster",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/cyberpunk/cyber_trickster.webp",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Lethal",
            "quote": "Holo-blades tuned to 180 BPM in neon Dolby Atmos.",
            "compatibility_tags": ["Neon Chrome", "Holo-Blades", "Synthwave Idol"],
            "archetype": "Neon Cyber Idol",
        },
    },
    {
        "slug": "neon_sable",
        "name": "Neon Sable",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/cyberpunk/neon_sable.webp",
        "metadata": {
            "chaos_score": 89,
            "danger_level": "Moderate",
            "quote": "Neon runes light up the dark web matrix.",
            "compatibility_tags": ["Cyber Goth", "Dark Web", "Occult Hacker"],
            "archetype": "Dark Web Witch",
        },
    },
    {
        "slug": "netrunner_nea",
        "name": "Netrunner Nea",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/cyberpunk/netrunner_nea.webp",
        "metadata": {
            "chaos_score": 82,
            "danger_level": "Low",
            "quote": "Breached your firewall before you even blinked.",
            "compatibility_tags": ["Netrunner", "Ice Breaker", "Street Samurai"],
            "archetype": "Master Netrunner",
        },
    },
    {
        "slug": "chrome_wesker",
        "name": "Chrome Wesker",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/cyberpunk/chrome_wesker.webp",
        "metadata": {
            "chaos_score": 98,
            "danger_level": "Lethal",
            "quote": "Sub-dermal chrome enhancements guarantee complete global evolution.",
            "compatibility_tags": ["Chrome Augmented", "Megacorp Boss", "Overclocked"],
            "archetype": "Transhuman God",
        },
    },
    {
        "slug": "cyberpunk_feng_min",
        "name": "Cyberpunk Feng Min",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/cyberpunk/cyber_feng.webp",
        "metadata": {
            "chaos_score": 68,
            "danger_level": "Low",
            "quote": "Ranked #1 in the neural VR deathmatch circuit.",
            "compatibility_tags": ["VR Champion", "Cyberpunk", "Reflex Boosted"],
            "archetype": "VR Combatant",
        },
    },
    {
        "slug": "hightech_trapper",
        "name": "High-tech Trapper",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/cyberpunk/hightech_trapper.webp",
        "metadata": {
            "chaos_score": 88,
            "danger_level": "High",
            "quote": "Laser tripwires and electromagnetic jaws snap unyielding.",
            "compatibility_tags": ["Laser Traps", "Exoskeleton", "Industrial"],
            "archetype": "Heavy Exosuit Trapper",
        },
    },
    {
        "slug": "meg_turbo",
        "name": "Meg Turbo",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/cyberpunk/meg_turbo.webp",
        "metadata": {
            "chaos_score": 72,
            "danger_level": "Low",
            "quote": "Cybernetic leg augments hit supersonic sprint speeds.",
            "compatibility_tags": ["Speed Augments", "Runner", "High Energy"],
            "archetype": "Overclocked Sprinter",
        },
    },
    {
        "slug": "cyber_oni",
        "name": "Cyber Oni",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/cyberpunk/cyber_oni.webp",
        "metadata": {
            "chaos_score": 97,
            "danger_level": "Lethal",
            "quote": "Plasma kanabo superheats composite armor into slag.",
            "compatibility_tags": ["Mecha Demon", "Plasma Weapon", "Titan"],
            "archetype": "Mecha Demon",
        },
    },
    {
        "slug": "synth_spirit",
        "name": "Synth Spirit",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/cyberpunk/synth_spirit.webp",
        "metadata": {
            "chaos_score": 93,
            "danger_level": "High",
            "quote": "Quantum phase shift through fiber optic cables.",
            "compatibility_tags": ["Hologram Phantom", "Quantum Glitch", "Data Wraith"],
            "archetype": "Quantum Phantom",
        },
    },
    {
        "slug": "glitch_nurse",
        "name": "Glitch Nurse",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/cyberpunk/glitch_nurse.webp",
        "metadata": {
            "chaos_score": 95,
            "danger_level": "Lethal",
            "quote": "Teleporting through memory leaks with a digital scalpel.",
            "compatibility_tags": ["Digital Scalpel", "Memory Leak", "Ghost in Shell"],
            "archetype": "Cyber Wraith",
        },
    },
]

# ==========================================
# ANIME / MANGA AESTHETIC: 10 CHARACTERS
# ==========================================

ANIME_ENTITIES: List[Dict[str, Any]] = [
    {
        "slug": "anime_spirit",
        "name": "Anime Spirit",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/anime/anime_spirit.webp",
        "metadata": {
            "chaos_score": 92,
            "danger_level": "High",
            "quote": "Baka! Did you think you could escape my phantom slash?",
            "compatibility_tags": ["Tsundere", "Katana Girl", "Manga Aesthetic"],
            "archetype": "Ghost Samurai Girl",
        },
    },
    {
        "slug": "anime_meg",
        "name": "Anime Meg",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/anime/anime_meg.webp",
        "metadata": {
            "chaos_score": 60,
            "danger_level": "Low",
            "quote": "Running to class with buttered toast in my mouth!",
            "compatibility_tags": ["Genki Girl", "Athletic", "Anime Protagonist"],
            "archetype": "Genki Athlete",
        },
    },
    {
        "slug": "anime_trickster",
        "name": "Anime Trickster",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/anime/anime_trickster.webp",
        "metadata": {
            "chaos_score": 94,
            "danger_level": "High",
            "quote": "Notice me, senpai... before the daggers strike!",
            "compatibility_tags": ["Bishounen", "Idol", "Yandere"],
            "archetype": "Yandere Idol",
        },
    },
    {
        "slug": "anime_huntress",
        "name": "Anime Huntress",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/anime/anime_huntress.webp",
        "metadata": {
            "chaos_score": 85,
            "danger_level": "High",
            "quote": "The forest spirits guided my heavy hatchet.",
            "compatibility_tags": ["Kuudere", "Forest Guardian", "Beast Master"],
            "archetype": "Forest Huntress",
        },
    },
    {
        "slug": "anime_legion",
        "name": "Anime Legion",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/anime/anime_legion.webp",
        "metadata": {
            "chaos_score": 87,
            "danger_level": "Moderate",
            "quote": "After school club: Extreme Slasher Society!",
            "compatibility_tags": ["School Delinquent", "Masked", "High Energy"],
            "archetype": "School Delinquent",
        },
    },
    {
        "slug": "anime_yui",
        "name": "Anime Yui",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/anime/anime_yui.webp",
        "metadata": {
            "chaos_score": 78,
            "danger_level": "Low",
            "quote": "My motorcycle soul burns hotter than the sunrise!",
            "compatibility_tags": ["Shonen Heroine", "Biker Boss", "Courageous"],
            "archetype": "Rebel Heroine",
        },
    },
    {
        "slug": "anime_mikaela",
        "name": "Anime Mikaela",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/anime/anime_mikaela.webp",
        "metadata": {
            "chaos_score": 72,
            "danger_level": "Low",
            "quote": "Mahou Shoujo blessing placed on this totem!",
            "compatibility_tags": ["Magical Girl", "Witchy", "Kawaii"],
            "archetype": "Totem Witch",
        },
    },
    {
        "slug": "anime_dracula",
        "name": "Anime Dracula",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/anime/anime_dracula.webp",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Lethal",
            "quote": "A majestic bloodline commanding the creatures of the night.",
            "compatibility_tags": ["Bishounen Lord", "Vampire Noble", "Castlevania Vibe"],
            "archetype": "Noble Vampire",
        },
    },
    {
        "slug": "anime_feng_min",
        "name": "Anime Feng Min",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/anime/anime_feng.webp",
        "metadata": {
            "chaos_score": 65,
            "danger_level": "Low",
            "quote": "Arcade queen ultra combo finish!",
            "compatibility_tags": ["Gamer Girl", "Arcade Queen", "Otaku"],
            "archetype": "Arcade Prodigy",
        },
    },
    {
        "slug": "anime_wesker",
        "name": "Anime Wesker",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/anime/anime_wesker.webp",
        "metadata": {
            "chaos_score": 97,
            "danger_level": "Lethal",
            "quote": "All according to keikaku.",
            "compatibility_tags": ["Megane Villain", "Mastermind", "Overpowered"],
            "archetype": "Calculating Overlord",
        },
    },
]

# ==========================================
# GOTHIC & ELDRITCH LEGENDS: 10 CHARACTERS
# ==========================================

GOTHIC_ENTITIES: List[Dict[str, Any]] = [
    {
        "slug": "victorian_dracula",
        "name": "Victorian Dracula",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/gothic/victorian_dracula.webp",
        "metadata": {
            "chaos_score": 97,
            "danger_level": "Lethal",
            "quote": "Crimson velvet coats draped in London fog.",
            "compatibility_tags": ["Victorian Noble", "Blood Curse", "Elegance"],
            "archetype": "Victorian Aristocrat",
        },
    },
    {
        "slug": "bloodborne_huntress",
        "name": "Bloodborne Huntress",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/gothic/bloodborne_huntress.webp",
        "metadata": {
            "chaos_score": 93,
            "danger_level": "High",
            "quote": "A huntress must hunt in the pale moon's glow.",
            "compatibility_tags": ["Beast Hunter", "Bloodborne Vibe", "Trick Weapons"],
            "archetype": "Yharnam Hunter",
        },
    },
    {
        "slug": "dark_fantasy_mikaela",
        "name": "Dark Fantasy Mikaela",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/gothic/dark_mikaela.webp",
        "metadata": {
            "chaos_score": 80,
            "danger_level": "Moderate",
            "quote": "Blood seals and arcane tomes light the bonfire.",
            "compatibility_tags": ["Grimoire", "Grim Dark", "Arcane Scholar"],
            "archetype": "Grimoire Sorceress",
        },
    },
    {
        "slug": "eldritch_nurse",
        "name": "Eldritch Nurse",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/gothic/eldritch_nurse.webp",
        "metadata": {
            "chaos_score": 96,
            "danger_level": "Eldritch",
            "quote": "Floating through cosmic miasma with starry tendrils.",
            "compatibility_tags": ["Cosmic Horror", "Tendrils", "Silent Madness"],
            "archetype": "Cosmic Entity",
        },
    },
    {
        "slug": "gothic_sable",
        "name": "Gothic Sable",
        "role": "Survivor",
        "gender": "female",
        "media_url": "/images/rosters/gothic/gothic_sable.webp",
        "metadata": {
            "chaos_score": 88,
            "danger_level": "Moderate",
            "quote": "Candlelight in crypts reveals forgotten truths.",
            "compatibility_tags": ["Victorian Goth", "Crypt Dweller", "Black Velvet"],
            "archetype": "Crypt Sorceress",
        },
    },
    {
        "slug": "plague_priestess",
        "name": "Plague Priestess",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/gothic/plague_priestess.webp",
        "metadata": {
            "chaos_score": 91,
            "danger_level": "High",
            "quote": "Golden censers swing with miasma of ancient dynasties.",
            "compatibility_tags": ["Ancient Censer", "High Priestess", "Sacred Sickness"],
            "archetype": "Dynasty Priestess",
        },
    },
    {
        "slug": "raven_artist",
        "name": "Raven Artist",
        "role": "Killer",
        "gender": "female",
        "media_url": "/images/rosters/gothic/raven_artist.webp",
        "metadata": {
            "chaos_score": 84,
            "danger_level": "High",
            "quote": "Black feather quill painting gothic despair.",
            "compatibility_tags": ["Poe Gothic", "Crow Queen", "Ink & Feathers"],
            "archetype": "Gothic Poet",
        },
    },
    {
        "slug": "occult_vittorio",
        "name": "Occult Vittorio",
        "role": "Survivor",
        "gender": "male",
        "media_url": "/images/rosters/gothic/occult_vittorio.webp",
        "metadata": {
            "chaos_score": 82,
            "danger_level": "Moderate",
            "quote": "Medieval glyphs burned into ancient skin.",
            "compatibility_tags": ["Runemaster", "Forbidden Tomes", "Centuries Old"],
            "archetype": "Glyph Master",
        },
    },
    {
        "slug": "phantom_wraith",
        "name": "Phantom Wraith",
        "role": "Killer",
        "gender": "male",
        "media_url": "/images/rosters/gothic/phantom_wraith.webp",
        "metadata": {
            "chaos_score": 78,
            "danger_level": "Moderate",
            "quote": "A spectral shroud drifting through graveyard mist.",
            "compatibility_tags": ["Graveyard Mist", "Barrow Wight", "Spectral"],
            "archetype": "Barrow Spectre",
        },
    },
    {
        "slug": "abyssal_dredge",
        "name": "Abyssal Dredge",
        "role": "Killer",
        "gender": "monster_other",
        "media_url": "/images/rosters/gothic/abyssal_dredge.webp",
        "metadata": {
            "chaos_score": 98,
            "danger_level": "Eldritch",
            "quote": "The void of a thousand screams consuming the light.",
            "compatibility_tags": ["Leviathan Abyss", "Eldritch Maw", "Tentacles"],
            "archetype": "Abyssal Devourer",
        },
    },
]

ROSTER_ENTITIES_MAP = {
    "canon": CANON_ENTITIES,
    "hooked_on_you": HOOKED_ON_YOU_ENTITIES,
    "legendary_cosplay": LEGENDARY_ENTITIES,
    "cyberpunk_2077": CYBERPUNK_ENTITIES,
    "anime_manga": ANIME_ENTITIES,
    "gothic_eldritch": GOTHIC_ENTITIES,
}

# ==========================================
# MULTI-LOCALE TRANSLATIONS (en, es, de, ja, pl)
# ==========================================

TRANSLATIONS_DATA: Dict[str, Dict[str, str]] = {
    "en": {
        "smashOrPass.rosters.canon.name": "Dead by Daylight: Fog Canon",
        "smashOrPass.rosters.canon.desc": "The complete 98-character roster of all official Killers and Survivors.",
        "smashOrPass.rosters.hoy.name": "Hooked on You: Island Romance",
        "smashOrPass.rosters.hoy.desc": "Tropical paradise dating sim edition with beach outfits and sunny vibes.",
        "smashOrPass.rosters.legendary.name": "Legendary Skins & Collabs",
        "smashOrPass.rosters.legendary.desc": "Iconic legendary skins and crossover collabs from gaming history.",
        "smashOrPass.rosters.cyberpunk.name": "Cyberpunk Fog 2077 Edition",
        "smashOrPass.rosters.cyberpunk.desc": "High-tech neon augmented champions fighting in a dystopian fog.",
        "smashOrPass.rosters.anime.name": "Fog Anime / Manga Aesthetic",
        "smashOrPass.rosters.anime.desc": "Stylized anime aesthetic adaptations of your favorite Fog characters.",
        "smashOrPass.rosters.gothic.name": "Victorian & Gothic Eldritch Legends",
        "smashOrPass.rosters.gothic.desc": "Dark fantasy, Bloodborne aesthetics, and Victorian eldritch horrors.",
        "smashOrPass.ui.smash": "Smash",
        "smashOrPass.ui.pass": "Pass",
        "smashOrPass.ui.superSmash": "Super Smash",
        "smashOrPass.ui.leaderboard": "Leaderboard",
        "smashOrPass.tiers.godTier": "God Tier",
        "smashOrPass.tiers.fatalAttraction": "Fatal Attraction",
        "smashOrPass.tiers.friendzone": "Friendzone",
        "smashOrPass.tiers.eldritchVoid": "Eldritch Void",
    },
    "es": {
        "smashOrPass.rosters.canon.name": "Dead by Daylight: Canon de la Niebla",
        "smashOrPass.rosters.canon.desc": "El elenco completo de 98 personajes de asesinos y supervivientes oficiales.",
        "smashOrPass.rosters.hoy.name": "Hooked on You: Romance en la Isla",
        "smashOrPass.rosters.hoy.desc": "Edición simulador de citas en un paraíso tropical con trajes de playa.",
        "smashOrPass.rosters.legendary.name": "Skins Legendarias y Colaboraciones",
        "smashOrPass.rosters.legendary.desc": "Skins legendarias icónicas y colaboraciones históricas de videojuegos.",
        "smashOrPass.rosters.cyberpunk.name": "Edición Niebla Cyberpunk 2077",
        "smashOrPass.rosters.cyberpunk.desc": "Campeones aumentados con neón de alta tecnología en una niebla distópica.",
        "smashOrPass.rosters.anime.name": "Estética Anime y Manga de la Niebla",
        "smashOrPass.rosters.anime.desc": "Adaptaciones estilizadas en anime de tus personajes favoritos.",
        "smashOrPass.rosters.gothic.name": "Leyendas Góticas y Primigenias Victorianas",
        "smashOrPass.rosters.gothic.desc": "Fantasía oscura, estética Bloodborne y horrores victorianos primigenios.",
        "smashOrPass.ui.smash": "Smash",
        "smashOrPass.ui.pass": "Pass",
        "smashOrPass.ui.superSmash": "Super Smash",
        "smashOrPass.ui.leaderboard": "Clasificación",
        "smashOrPass.tiers.godTier": "Nivel Dios",
        "smashOrPass.tiers.fatalAttraction": "Atracción Fatal",
        "smashOrPass.tiers.friendzone": "Zona de Amigos",
        "smashOrPass.tiers.eldritchVoid": "Vacío Primigenio",
    },
    "de": {
        "smashOrPass.rosters.canon.name": "Dead by Daylight: Nebel-Kanon",
        "smashOrPass.rosters.canon.desc": "Die vollständige Liste aller 98 offiziellen Killer und Überlebenden.",
        "smashOrPass.rosters.hoy.name": "Hooked on You: Insel-Romanze",
        "smashOrPass.rosters.hoy.desc": "Tropische Dating-Sim-Edition mit Strand-Outfits und sonnigen Vibes.",
        "smashOrPass.rosters.legendary.name": "Legendäre Skins & Kollaborationen",
        "smashOrPass.rosters.legendary.desc": "Ikonische legendäre Skins und Crossover-Kollaborationen.",
        "smashOrPass.rosters.cyberpunk.name": "Cyberpunk-Nebel 2077 Edition",
        "smashOrPass.rosters.cyberpunk.desc": "High-Tech Neon-Champions im Kampf durch den dystopischen Nebel.",
        "smashOrPass.rosters.anime.name": "Nebel Anime / Manga Ästhetik",
        "smashOrPass.rosters.anime.desc": "Stilisierte Anime-Adaptionen deiner liebsten Nebel-Charaktere.",
        "smashOrPass.rosters.gothic.name": "Viktorianische & Gotische Eldritch-Legenden",
        "smashOrPass.rosters.gothic.desc": "Dark Fantasy, Bloodborne-Ästhetik und viktorianischer Eldritch-Horror.",
        "smashOrPass.ui.smash": "Smash",
        "smashOrPass.ui.pass": "Pass",
        "smashOrPass.ui.superSmash": "Super Smash",
        "smashOrPass.ui.leaderboard": "Rangliste",
        "smashOrPass.tiers.godTier": "Götter-Stufe",
        "smashOrPass.tiers.fatalAttraction": "Fatale Anziehung",
        "smashOrPass.tiers.friendzone": "Friendzone",
        "smashOrPass.tiers.eldritchVoid": "Eldritch-Leere",
    },
    "ja": {
        "smashOrPass.rosters.canon.name": "Dead by Daylight: 霧の正史 (カノン)",
        "smashOrPass.rosters.canon.desc": "公式の殺人鬼と生存者全98キャラクターの完全ロスター。",
        "smashOrPass.rosters.hoy.name": "Hooked on You: 狂気の島恋愛シミュレーション",
        "smashOrPass.rosters.hoy.desc": "水着と南国の雰囲気漂うトロピカルデートシミュレーション版。",
        "smashOrPass.rosters.legendary.name": "レジェンダリースキン＆コラボ",
        "smashOrPass.rosters.legendary.desc": "ゲーム史に輝く象徴的なレジェンダリースキンとクロスオーバーコラボ。",
        "smashOrPass.rosters.cyberpunk.name": "サイバーパンク・フォグ 2077 エディション",
        "smashOrPass.rosters.cyberpunk.desc": "ディストピアの霧で戦うハイテク・ネオン強化チャンピオンたち。",
        "smashOrPass.rosters.anime.name": "フォグ・アニメ / マンガ美学",
        "smashOrPass.rosters.anime.desc": "大好きなフォグキャラクターたちのスタイリッシュなアニメ版スタイル。",
        "smashOrPass.rosters.gothic.name": "ヴィクトリアン＆ゴシック・エルドリッチ伝説",
        "smashOrPass.rosters.gothic.desc": "ダークファンタジー、ブラッドボーン風美学、ヴィクトリア朝の異形ホラー。",
        "smashOrPass.ui.smash": "スマッシュ",
        "smashOrPass.ui.pass": "パス",
        "smashOrPass.ui.superSmash": "スーパースマッシュ",
        "smashOrPass.ui.leaderboard": "リーダーボード",
        "smashOrPass.tiers.godTier": "神ティア",
        "smashOrPass.tiers.fatalAttraction": "致命的魅力",
        "smashOrPass.tiers.friendzone": "フレンドゾーン",
        "smashOrPass.tiers.eldritchVoid": "狂気の虚無",
    },
    "pl": {
        "smashOrPass.rosters.canon.name": "Dead by Daylight: Kanon Mgły",
        "smashOrPass.rosters.canon.desc": "Kompletny zestaw 98 oficjalnych postaci Zabójców i Ocalałych.",
        "smashOrPass.rosters.hoy.name": "Hooked on You: Romans na Wyspie",
        "smashOrPass.rosters.hoy.desc": "Tropikalna edycja symulatora randkowego w plażowych strojach.",
        "smashOrPass.rosters.legendary.name": "Legendarne Skórki i Kolaboracje",
        "smashOrPass.rosters.legendary.desc": "Kultowe legendarne skórki i crossovery z historii gier wideo.",
        "smashOrPass.rosters.cyberpunk.name": "Cyberpunkowa Mgła 2077",
        "smashOrPass.rosters.cyberpunk.desc": "Zaawansowani technologicznie neonowi czempioni w dystopijnej mgle.",
        "smashOrPass.rosters.anime.name": "Estetyka Anime / Mangi w Mgle",
        "smashOrPass.rosters.anime.desc": "Stylizowane adaptacje anime Twoich ulubionych postaci z Mgły.",
        "smashOrPass.rosters.gothic.name": "Wiktoriańskie i Gotyckie Legendy Przedwiecznych",
        "smashOrPass.rosters.gothic.desc": "Mroczne fantasy, estetyka Bloodborne i wiktoriańskie koszmary przedwiecznych.",
        "smashOrPass.ui.smash": "Smash",
        "smashOrPass.ui.pass": "Pass",
        "smashOrPass.ui.superSmash": "Super Smash",
        "smashOrPass.ui.leaderboard": "Tabela wyników",
        "smashOrPass.tiers.godTier": "Boski Poziom",
        "smashOrPass.tiers.fatalAttraction": "Zguba z Miłości",
        "smashOrPass.tiers.friendzone": "Strefa Przyjaźni",
        "smashOrPass.tiers.eldritchVoid": "Kosmiczna Otchłań",
    },
}


def seed_smash_rosters() -> None:
    """
    Seeds all 6 rosters, 150+ entities with rich metadata, clean 0-vote stats,
    and multi-locale translations for en, es, de, ja, and pl.
    Idempotent and safe against concurrency issues.
    """
    try:
        # 1. Seed / Update Rosters
        for r_data in ROSTERS_DATA:
            roster = db.session.scalar(
                select(Roster).where(Roster.slug == r_data["slug"])
            )
            if not roster:
                roster = Roster(
                    id=str(uuid.uuid4()),
                    slug=r_data["slug"],
                    name_i18n_key=r_data["name_i18n_key"],
                    description_i18n_key=r_data["description_i18n_key"],
                    cover_image_url=r_data["cover_image_url"],
                    theme_color=r_data["theme_color"],
                    category=r_data["category"],
                    is_nsfw=r_data["is_nsfw"],
                    is_active=r_data["is_active"],
                )
                db.session.add(roster)
            else:
                roster.name_i18n_key = r_data["name_i18n_key"]
                roster.description_i18n_key = r_data["description_i18n_key"]
                roster.cover_image_url = r_data["cover_image_url"]
                roster.theme_color = r_data["theme_color"]
                roster.category = r_data["category"]
                roster.is_nsfw = r_data["is_nsfw"]
                roster.is_active = r_data["is_active"]

            db.session.flush()

            # 2. Seed Entities and EntityStats for this Roster
            entities = ROSTER_ENTITIES_MAP.get(r_data["slug"], [])
            for order_idx, e_data in enumerate(entities):
                entity = db.session.scalar(
                    select(Entity).where(
                        Entity.roster_id == roster.id,
                        Entity.slug == e_data["slug"],
                    )
                )
                if not entity:
                    entity = Entity(
                        id=str(uuid.uuid4()),
                        roster_id=roster.id,
                        slug=e_data["slug"],
                        name=e_data["name"],
                        role=e_data["role"],
                        gender=e_data["gender"],
                        media_url=e_data.get("media_url"),
                        media_type="image",
                        metadata_json=e_data.get("metadata", {}),
                        order_index=order_idx,
                        is_active=True,
                    )
                    db.session.add(entity)
                    db.session.flush()
                else:
                    entity.name = e_data["name"]
                    entity.role = e_data["role"]
                    entity.gender = e_data["gender"]
                    entity.media_url = e_data.get("media_url")
                    entity.metadata_json = e_data.get("metadata", {})
                    entity.order_index = order_idx
                    db.session.flush()

                # Ensure EntityStat exists with 0 counts
                stat = db.session.scalar(
                    select(EntityStat).where(EntityStat.entity_id == entity.id)
                )
                if not stat:
                    chaos = float(
                        e_data.get("metadata", {}).get("chaos_score", 50.0)
                    )
                    stat = EntityStat(
                        id=str(uuid.uuid4()),
                        entity_id=entity.id,
                        smash_count=0,
                        pass_count=0,
                        super_smash_count=0,
                        total_votes=0,
                        smash_rate=0.0,
                        chaos_rating=chaos,
                    )
                    db.session.add(stat)

        # 3. Seed Multi-Locale Translations
        for locale, kv_map in TRANSLATIONS_DATA.items():
            for key, value in kv_map.items():
                trans = db.session.scalar(
                    select(Translation).where(
                        Translation.locale == locale,
                        Translation.key == key,
                    )
                )
                if not trans:
                    trans = Translation(
                        id=str(uuid.uuid4()),
                        locale=locale,
                        key=key,
                        value=value,
                    )
                    db.session.add(trans)
                else:
                    trans.value = value

        # 4. Legacy SmashPassStat synchronization
        for r_slug in ["canon", "hooked_on_you", "legendary_cosplay"]:
            for e_data in ROSTER_ENTITIES_MAP.get(r_slug, []):
                leg_stat = db.session.scalar(
                    select(SmashPassStat).where(
                        SmashPassStat.character_slug == e_data["slug"],
                        SmashPassStat.edition == r_slug,
                    )
                )
                if not leg_stat:
                    db.session.add(
                        SmashPassStat(
                            character_slug=e_data["slug"],
                            character_name=e_data["name"],
                            role=e_data["role"],
                            gender=e_data["gender"],
                            edition=r_slug,
                            smash_count=0,
                            pass_count=0,
                            super_smash_count=0,
                            total_votes=0,
                            smash_rate=0.0,
                        )
                    )

        db.session.commit()
        logger.info("Smash rosters, entities, stats, and translations successfully seeded.")
    except Exception as e:
        db.session.rollback()
        logger.warning(f"Error seeding smash rosters: {e}")
        raise e
