import json, sys, io

sys.stdout.reconfigure(encoding='utf-8')

PATH = "backend/app/seeds/data/content/perks.json"

# name -> curse_category
CLASSIFICATION = {
"A Place For Us": "altruism_healing",
"Ace in the Hole": "general",
"Adrenaline": "exhaustion",
"Aftercare": "aura_reading",
"Alert": "aura_reading",
"Any Means Necessary": "chase",
"Apocalyptic Ingenuity": "chase",
"Appraisal": "general",
"Autodidact": "altruism_healing",
"Babysitter": "altruism_healing",
"Background Player": "exhaustion",
"Bada Bada Boom": "chase",
"Balanced Landing": "exhaustion",
"Bardic Inspiration": "meme",
"Better Together": "aura_reading",
"Better than New": "altruism_healing",
"Bite the Bullet": "altruism_healing",
"Blast Mine": "chase",
"Blood Pact": "aura_reading",
"Blood Rush": "general",
"Boil Over": "chase",
"Bond": "aura_reading",
"Boon: Circle of Healing": "boon",
"Boon: Dark Theory": "boon",
"Boon: Exponential": "boon",
"Boon: Illumination": "boon",
"Boon: Shadow Step": "boon",
"Boon: Steadfast": "boon",
"Borrowed Time": "altruism_healing",
"Botany Knowledge": "altruism_healing",
"Breakdown": "altruism_healing",
"Breakout": "chase",
"Buckle Up": "altruism_healing",
"Built to Last": "general",
"Calm Spirit": "general",
"Camaraderie": "altruism_healing",
"Champion of Light": "chase",
"Change of Plan": "general",
"Chemical Trap": "chase",
"Clairvoyance": "aura_reading",
"Clean Break": "altruism_healing",
"Come and Get Me!": "altruism_healing",
"Conviction": "handicap",
"Corrective Action": "altruism_healing",
"Counterforce": "general",
"Cross-Examination": "general",
"Cut Loose": "chase",
"Dance With Me": "chase",
"Dark Sense": "aura_reading",
"Dead Hard": "exhaustion",
"Deadline": "general",
"Deception": "chase",
"Decisive Strike": "chase",
"Déjà Vu": "aura_reading",
"Deliverance": "handicap",
"Desperate Measures": "altruism_healing",
"Detective's Hunch": "aura_reading",
"Distortion": "general",
"Diversion": "chase",
"Do No Harm": "altruism_healing",
"Dramaturgy": "exhaustion",
"Duty of Care": "altruism_healing",
"Empathic Connection": "altruism_healing",
"Empathy": "aura_reading",
"Extrasensory Perception": "aura_reading",
"Exultation": "chase",
"Eyes of Belmont": "aura_reading",
"Fast Track": "general",
"Finesse": "chase",
"Five Moves Ahead": "chase",
"Fixated": "chase",
"Flashbang": "chase",
"Flip-Flop": "chase",
"Flow State": "altruism_healing",
"Fogwise": "aura_reading",
"For the People": "altruism_healing",
"Friendly Competition": "general",
"Fruits of Your Labor": "general",
"Ghost Notes": "general",
"Hardened": "aura_reading",
"Head On": "exhaustion",
"Hope": "general",
"Hyperfocus": "general",
"Inner Focus": "aura_reading",
"Inner Strength": "altruism_healing",
"Invocation: Treacherous Crows": "aura_reading",
"Invocation: Weaving Spiders": "handicap",
"Iron Will": "chase",
"Kindred": "aura_reading",
"Last Stand": "chase",
"Leader": "altruism_healing",
"Left Behind": "aura_reading",
"Lend a Hand": "altruism_healing",
"Light-Footed": "chase",
"Lightweight": "chase",
"Lithe": "exhaustion",
"Low Profile": "chase",
"Lucky Break": "chase",
"Lucky Star": "aura_reading",
"Made for This": "altruism_healing",
"Mettle of Man": "altruism_healing",
"Mirrored Illusion": "chase",
"Moment of Glory": "altruism_healing",
"No Mither": "handicap",
"No One Left Behind": "altruism_healing",
"Object of Obsession": "aura_reading",
"Off the Record": "altruism_healing",
"One-Two-Three-Four!": "general",
"Open-Handed": "aura_reading",
"Overcome": "exhaustion",
"Overzealous": "general",
"Parental Guidance": "chase",
"Pharmacy": "general",
"Plot Twist": "handicap",
"Plunderer's Instinct": "general",
"Poised": "aura_reading",
"Potential Energy": "general",
"Power Struggle": "chase",
"Premonition": "chase",
"Prove Thyself": "general",
"Quick & Quiet": "chase",
"Quick Gambit": "chase",
"Rapid Response": "exhaustion",
"Reactive Healing": "altruism_healing",
"Reassurance": "altruism_healing",
"Red Herring": "aura_reading",
"Repressed Alliance": "general",
"Residual Manifest": "chase",
"Resilience": "general",
"Resurgence": "altruism_healing",
"Road Life": "altruism_healing",
"Rookie Spirit": "aura_reading",
"Saboteur": "aura_reading",
"Salvation's Cry": "aura_reading",
"Scavenger": "general",
"Scene Partner": "aura_reading",
"Second Wind": "altruism_healing",
"Self-Care": "altruism_healing",
"Self-Preservation": "general",
"Shoulder the Burden": "altruism_healing",
"Slippery Meat": "general",
"Small Game": "general",
"Smash Hit": "exhaustion",
"Sole Survivor": "general",
"Solidarity": "altruism_healing",
"Soul Guard": "general",
"Specialist": "general",
"Spine Chill": "general",
"Sprint Burst": "exhaustion",
"Stake Out": "general",
"Still Sight": "aura_reading",
"Streetwise": "aura_reading",
"Strength in Shadows": "altruism_healing",
"Teamwork: Collective Stealth": "altruism_healing",
"Teamwork: Full Circuit": "general",
"Teamwork: Power of Two": "altruism_healing",
"Teamwork: Soft-Spoken": "general",
"Teamwork: Throw Down": "altruism_healing",
"Teamwork: Toughen Up": "general",
"Technician": "general",
"Tenacity": "general",
"This Is Not Happening": "general",
"Troubleshooter": "chase",
"Unbreakable": "general",
"Up the Ante": "general",
"Urban Evasion": "chase",
"Vigil": "general",
"Visionary": "aura_reading",
"Wake Up!": "general",
"We See You": "aura_reading",
"We'll Make It": "altruism_healing",
"We're Gonna Live Forever": "altruism_healing",
"Wicked": "general",
"Wide Open Throttle": "chase",
"Windows of Opportunity": "aura_reading",
"Wiretap": "aura_reading",
"A Nurse's Calling": "aura_reading",
"Agitation": "chase",
"Alien Instinct": "aura_reading",
"All-Shaking Thunder": "chase",
"Awakened Awareness": "aura_reading",
"Bamboozle": "chase",
"Barbecue & Chilli": "aura_reading",
"Batteries Included": "general",
"Beast of Prey": "chase",
"Bitter Murmur": "aura_reading",
"Blood Echo": "chase",
"Blood Warden": "general",
"Bloodhound": "chase",
"Brutal Strength": "gen_slowdown",
"Call of Brine": "gen_slowdown",
"Celestial Witness": "aura_reading",
"Corrupt Intervention": "gen_slowdown",
"Coulrophobia": "altruism_healing",
"Coup de Grâce": "chase",
"Cruel Limits": "chase",
"Dark Arrogance": "chase",
"Dark Devotion": "chase",
"Darkness Revealed": "aura_reading",
"Dead Man's Switch": "gen_slowdown",
"Deadlock": "gen_slowdown",
"Deathbound": "aura_reading",
"Deerstalker": "aura_reading",
"Discordance": "aura_reading",
"Dissolution": "chase",
"Distressing": "general",
"Dominance": "general",
"Dragon's Grip": "gen_slowdown",
"Dying Light": "gen_slowdown",
"Enduring": "chase",
"Eruption": "gen_slowdown",
"Fire Up": "gen_slowdown",
"Forced Hesitation": "chase",
"Forced Penance": "altruism_healing",
"Forever Entwined": "general",
"Franklin's Demise": "aura_reading",
"Friends 'til the End": "aura_reading",
"Furtive Chase": "chase",
"Game Afoot": "chase",
"Gearhead": "aura_reading",
"Genetic Limits": "chase",
"Grim Embrace": "gen_slowdown",
"Haywire": "general",
"Help Wanted": "general",
"Hex: Blood Favour": "hex",
"Hex: Crowd Control": "hex",
"Hex: Devour Hope": "hex",
"Hex: Face the Darkness": "hex",
"Hex: Haunted Ground": "hex",
"Hex: Hive Mind": "hex",
"Hex: Huntress Lullaby": "hex",
"Hex: No One Escapes Death": "hex",
"Hex: Nothing but Misery": "hex",
"Hex: Overture of Doom": "hex",
"Hex: Pentimento": "hex",
"Hex: Plaything": "hex",
"Hex: Retribution": "hex",
"Hex: Ruin": "hex",
"Hex: Scared to Death": "hex",
"Hex: The Third Seal": "hex",
"Hex: Thrill of the Hunt": "hex",
"Hex: Two Can Play": "hex",
"Hex: Under Your Thumb": "hex",
"Hex: Undying": "hex",
"Hex: Wretched Fate": "hex",
"Hoarder": "general",
"Hubris": "chase",
"Human Greed": "aura_reading",
"Hysteria": "chase",
"I'm All Ears": "aura_reading",
"Infectious Fright": "aura_reading",
"Insidious": "chase",
"Iron Grasp": "chase",
"Iron Maiden": "chase",
"Knock Out": "chase",
"Languid Touch": "chase",
"Lay Waste": "gen_slowdown",
"Lethal Pursuer": "aura_reading",
"Leverage": "altruism_healing",
"Lightborn": "general",
"Machine Learning": "gen_slowdown",
"Mad Grit": "chase",
"Make Your Choice": "chase",
"Merciless Storm": "gen_slowdown",
"Mindbreaker": "chase",
"Monitor & Abuse": "chase",
"Nemesis": "chase",
"No Quarter": "altruism_healing",
"No Way Out": "general",
"None Are Free": "chase",
"Nowhere to Hide": "aura_reading",
"Oppression": "gen_slowdown",
"Overcharge": "gen_slowdown",
"Overwhelming Presence": "aura_reading",
"Phantom Fear": "aura_reading",
"Play with Your Food": "chase",
"Pop Goes the Weasel": "gen_slowdown",
"Predator": "aura_reading",
"Rampage": "chase",
"Rancor": "chase",
"Rapid Brutality": "chase",
"Ravenous": "chase",
"Remember Me": "general",
"Save the Best for Last": "chase",
"Scourge Hook: Floods of Rage": "aura_reading",
"Scourge Hook: Gift of Pain": "altruism_healing",
"Scourge Hook: Hangman's Trick": "aura_reading",
"Scourge Hook: Jagged Compass": "aura_reading",
"Scourge Hook: Monstrous Shrine": "general",
"Scourge Hook: Pain Resonance": "gen_slowdown",
"Secret Project": "gen_slowdown",
"Septic Touch": "altruism_healing",
"Shadowborn": "general",
"Shattered Hope": "general",
"Silent Shadow": "chase",
"Sloppy Butcher": "altruism_healing",
"Spies from the Shadows": "general",
"Spirit Fury": "chase",
"Starstruck": "chase",
"Stridor": "chase",
"Superior Anatomy": "chase",
"Surge": "gen_slowdown",
"Surveillance": "aura_reading",
"THWACK!": "aura_reading",
"Terminus": "general",
"Territorial Imperative": "aura_reading",
"Thanatophobia": "gen_slowdown",
"Thrilling Tremors": "gen_slowdown",
"Tinkerer": "chase",
"Trail of Torment": "chase",
"Turn Back the Clock": "gen_slowdown",
"Ultimate Weapon": "chase",
"Unbound": "chase",
"Undone": "gen_slowdown",
"Unforeseen": "chase",
"Unnerving Presence": "gen_slowdown",
"Unrelenting": "chase",
"Wandering Eye": "aura_reading",
"Weave Attunement": "aura_reading",
"Whispers": "meme",
"Zanshin Tactics": "aura_reading",
}

VALID = {"exhaustion","gen_slowdown","hex","boon","chase","aura_reading",
         "altruism_healing","handicap","meme","general"}

with io.open(PATH, encoding="utf-8") as f:
    data = json.load(f)

perks = data["perks"]
missing = []
for p in perks:
    name = p["name"]
    cat = CLASSIFICATION.get(name)
    if cat is None:
        missing.append((p["id"], p["role"], name))
        continue
    assert cat in VALID, f"invalid category {cat} for {name}"
    p["curse_category"] = cat

if missing:
    print("MISSING CLASSIFICATIONS:")
    for m in missing:
        print(m)
    sys.exit(1)

with io.open(PATH, "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)
    f.write("\n")

from collections import Counter
counts = Counter(p["curse_category"] for p in perks)
print("Total perks:", len(perks))
for cat in sorted(counts, key=lambda c: -counts[c]):
    print(f"{cat}: {counts[cat]}")
